### ISSUE TITLE
5023/5024 login error on v15.dev

### ISSUE THREAD

**Issue by alechy** [DevilXD/TwitchDropsMiner#100]
There's a 5023 login error code returned when trying to log in on the latest master branch `v15.dev` build.

**Comment by matarife123** [comment]
i have this error :
![Sin título](https://user-images.githubusercontent.com/110930030/208233332-c534e480-ecfb-460c-b7eb-5009568ef6c1.png)

**Comment by Huiaei** [comment]
> i have this error : ![Sin título](https://user-images.githubusercontent.com/110930030/208233332-c534e480-ecfb-460c-b7eb-5009568ef6c1.png)

Only the network link is not stable enough.

**Comment by matarife123** [comment]
![Sin título](https://user-images.githubusercontent.com/110930030/208236119-db2466ea-bf93-4a3d-a4cf-1e75f0074677.png)
new error

**Comment by DevilXD** [comment]
@matarife123 There's already an issue open about that: #68  Also `v14` is not working and is not supported anymore, the current master branch has a `v15` in development, which avoids that error, but you'll need a working cookies file, since this issue is about not being able to log in.

@alechy Thank you for making an issue, I am aware of the 5023 error in the current `v15`, but there's no resolution to it right now. This grounds the project yet again, until someone can figure out how to do the login procedure a different way.

**Comment by matarife123** [comment]
> @matarife123Ya hay un problema abierto al respecto: [# 68](https://github.com/DevilXD/TwitchDropsMiner/issues/68) Además `v14`, no funciona y ya no es compatible, la rama maestra actual está `v15`en desarrollo, lo que evita ese error, pero necesita un archivo de cookies que funcione, ya que este problema es sobre no poder iniciar sesión.
> 
> @alechyGracias por crear un problema. Soy consciente del error 5023 en el actual `v15`, pero no hay solución en este momento. Esto fundamenta el proyecto una vez más, hasta que alguien pueda cómo realizar el procedimiento de inicio de sesión de una manera diferente.

where can i download v15?

**Comment by DevilXD** [comment]
@matarife123 As I said, `v15` is still in development. I wrote a guide on how to run and build the latest master branch yourself here: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running  If you're not keen on doing all of that, you'll need to just wait for an official `v15` release instead.

**Comment by JourneyOver** [comment]
> Also `v14` is not working

this isn't entirely true, I'm still running v14 and other than an occasional crash (very rare) it's still working just fine for me.

**Comment by DevilXD** [comment]
@JourneyOver The truth is that - it depends how you look at it. If someone has managed to stick to their old cookie file, that has an authentication token that doesn't trigger the GQL integrity system, then it's going to work. However, anyone who tried to login after the integrity system became live (since September this year), will encounter GQL errors when trying to claim drops or bonus points. Similarly, the login system has managed to change 2 times since `v14`, and it needs to be changed yet again to accommodate this error, because Twitch just keeps breaking things.

The authentication tokens from cookie files will expire after a year since the login happened (by what Twitch returns), after which time you will have to reauthenticate and generate a new cookie. If the login system doesn't work, then it's not possible to do that. For these very reasons, I don't support `v14` anymore, and you're using it on your own risk. The only errors you can get from it is the login one (because Twitch broke it several times now), and the GQL integrity one, if you'd still somehow have a cookie generated after the integrity changes, that'll appear when trying to claim drops or points (mining itself is unaffected).

**Comment by matarife123** [comment]
> @JourneyOverLa verdad es que - depende de cómo lo mires. Si alguien ha logrado mantener su antiguo archivo de cookies, que tiene un token de autenticación que no activa el sistema de integridad GQL, entonces funcionará. Sin embargo, cualquiera que haya intentado iniciar sesión después de que el sistema de integridad se pusiera en marcha (desde septiembre de este año), encontrará errores de GQL al intentar reclamar puntos de bonificación. Del mismo modo, el sistema de inicio de sesión ha logrado cambiar 2 veces desde `v14`, y debe cambiarse una vez más para adaptarse a este error, porque Twitch sigue rompiendo cosas.
> 
> Los tokens de autenticación de los archivos de cookies caducan después de un año desde que se produjo el inicio de sesión (por lo que Twitch devuelve), después de lo cual deberá volver a autenticarse y generar una nueva cookie. Si el sistema de inicio de sesión no funciona, entonces no es posible hacerlo. Por estas mismas razones, ya no apoyo `v14`, y lo estás usando bajo tu propio riesgo. Los únicos errores que puede obtener de él son el de inicio de sesión (porque Twitch lo rompió varias veces ahora) y el de integridad GQL, si de alguna manera todavía tiene una cookie generada después de los cambios de integridad, eso aparecerá cuando intente Reclama gotas o puntos (la minería en sí no se ve afectada).

**Comment by matarife123** [comment]
When could v15 be ready?

**Comment by DevilXD** [comment]
@matarife123 `v15` was already in the testing phase several times, but was delayed several times as well, due to Twitch changing things, and me then having to test these things. Also issues like #80, #89 and definitely #90. And now this.

**Comment by matarife123** [comment]
I hope you can finish it, you do a great job. There are many updates lately on everything, games, websites...

**Comment by Huiaei** [comment]
@DevilXD  Consider supporting manual cookie import? The previous login is still in normal use, but the new account cannot be logged in. Maybe you can extend or capture the network request of the twitter app through the browser edithiscookie? This is an attempt. I wanted to try it myself, but I can't program, so I don't know where to start.

**Comment by DevilXD** [comment]
@Huiaei I've already explained it multiple times before. The current login system and the cookie uses an android user agent from the Twitch's android app (along with the app's client ID), that could bypass the need for having to deal with the integrity system. There's no way for a non-developer person to obtain a cookie like that, as you'd need to install like an android system simulator on your PC (like BlueStacks), install the twitch app on it, somehow figure out how to capture the requests it makes, and extract the cookie from there. Alternatively, use a rooted phone to get into the files the twitch app saves and snoop around for the saved authentication token there (it has to remember it somehow).

If you login from a browser on your PC, you use the PC user agent, and use the website client ID, which is protected by the integrity system and disables the ability to claim drops or channel points. Even if you could enter the authentication token obtained from your browser (no need because PC login always worked), you'd just run into the integrity system and it'd break anyway. The way I used to be able to deal with it during Chrome login was to use a function that'd intercept the login request, and inject the android client ID into it: https://github.com/DevilXD/TwitchDropsMiner/blob/d100c4b7ff05d6bc53a1dfdb14b4d8b345c0e3e7/twitch.py#L133-L144

Again, there's no way for a non-developer person to do this. Besides, if you'd really want to "plug in" whatever authentication token you'd want, you could just edit the cookie file in a text editor - it's 30 characters long and uses digits and lowercase letters. Just backup the file first, please. Here's a pic from my Notepad++:

![token](https://user-images.githubusercontent.com/4180725/208836195-2d14c132-bb32-4dab-a25f-18ecc0777b41.png)

If I were to ever change back to using the web client ID and user agent, then there would still be no real need to provide a way to enter the authentication token, because normal PC login works. It's just that it being protected by the integrity system is the issue I tried to work around by using the android one.

**Comment by DevilXD** [comment]
This is now resolved by https://github.com/DevilXD/TwitchDropsMiner/commit/3892dfe59e8835486966cd668c9e128c36b7cd95

Ref issue: #104

If anyone would be having an issue with it, please open a new issue.
