### ISSUE TITLE
706cece: campaigns list missing most

### ISSUE THREAD

**Issue by Luckz** [DevilXD/TwitchDropsMiner#106]
On https://github.com/DevilXD/TwitchDropsMiner/tree/706cecec23ed8c0aae64d3ee85c3464c1c9ee4e8 , 

As you can see by the scrollbar size, one of two instances seems to have misplaced most of the list of active campaigns. This was after some days of uptime.
![image](https://user-images.githubusercontent.com/224748/209291395-40ce8448-d9d8-4b70-82c5-0a87e4a12e27.png)

**Comment by DevilXD** [comment]
Hello o/

I'm not sure if I'm getting this right. Are you asking why the scrollbar size differs? If so, I'd need more information and steps to be taken here, specifically:

1. Reload both instances, one right after the other. The reason is that, they could be "out of sync" by up to an hour, and reloading purges expired campaigns out of the memory. If one instance has expired campaigns and the other one doesn't, that can affect the scrollbar size like that. If doing so still causes the issue, see next point.
2. Make sure they have the same filters selected and the view is refreshed. Changing the filters does not immediately alter what's displayed, the "Refresh" button needs to be pressed for that. Switching away and back to the Inventory tab should perform an implicit refresh as well. Having differing filters selected and not refreshed like that will also change how many campaigns are displayed, and thus the scrollbar size. If doing so still causes the issue, see next point.
3. If the length would still differ after both of the above steps, please go to the https://www.twitch.tv/drops/campaigns page for each of the accounts, and then compare which campaigns are displayed for both of them. If they'd differ, that would explain the scrollbar size difference too. I haven't personally heard about campaigns being selectively available only for some twitch accounts, but I'm not ruling it out as a possibility either.

Please let me know how it went.

**Comment by DevilXD** [comment]
It's been two weeks and no response has been given, so I'm assuming this "bug" has never existed and came from the simple misunderstanding of how the reload system works, per above explanation. If you'd still have troubles, please refer to the instructions above or open another issue.
