### ISSUE TITLE
set browser path manually

### ISSUE THREAD

**Issue by Paradox92** [DevilXD/TwitchDropsMiner#108]
Im using Brave Browser based on Chrome and everytime i need the Twitch's device activation my Brave Browser is opening, would be nice if you can set the path manually.
I dont know but maybe when u can set the path manually, u can use Chrome Portable for more then one account?

edit//
after i set Chrome to default browser, it used Chrome for the activation

**Comment by DevilXD** [comment]
For opening up links, I'm using the standard lib `webbrowser` package: https://docs.python.org/3/library/webbrowser.html

Specifically: `webbrowser.open_new_tab("link_here")`

This delegates to whatever browser you have set as your default browser. If you want the links to open in a different one, just set it as your default, yes.

Now, regarding these:

> Im using Brave Browser based on Chrome and everytime i need the Twitch's device activation my Brave Browser is opening,

Sounds like it's working as intended then?

> would be nice if you can set the path manually.

So not working as intended then? Not sure what you're suggesting here then.

> u can use Chrome Portable for more then one account?

Again, not sure what you mean. I don't directly support mining with more than one account right now, what are you trying to suggest, exactly?

> after i set Chrome to default browser, it used Chrome for the activation

Yes, as explained in the first paragraph. Does this mean this issue is solved, or are you still trying to suggest something here?

**Comment by Paradox92** [comment]
after i wrote this, i found out that i just need to change the default browser to Chrome for the activation.
my intention was to use multiply accounts for each instance a seperate chrome portable browser, because i thought u can mine the drops and after that u can link the account, but sadly thats not working.

the issue is solved
thanks for the awesome program.
