### ISSUE TITLE
[v15] Blank Channels, Inventory, and only two Websockets

### ISSUE THREAD

**Issue by Alicyl** [DevilXD/TwitchDropsMiner#118]
To keep it short and sweet, I have precisely the same issue as this person: https://github.com/DevilXD/TwitchDropsMiner/issues/64

**Comment by DevilXD** [comment]
Hello o/

Well, have you tried any of the solutions from #64 as well? They'd apply here too. By "two websockets" I'm assuming you mean the "2/50" count that's displayed next to the single websocket connection that exists - that's expected, as there's two base topics the websocket subscribes to by default, and then any additional topics come from the tracked channels. No channels means only the two base topics remain.

The channel list contents themselves is dependent on the inventory, if the inventory is not there (there's no campaigns to mine), there won't be any channels worth watching either. My inventory is also empty right now, but simply because there's just no campaigns for the games I'm interested in mining.

To see all campaigns the application knows about, wait for it to get to the Idle state, and then please try this setup of filters (and click on Refresh of course):

![filters](https://user-images.githubusercontent.com/4180725/198507231-ca9917fe-399f-4e23-8b0c-487e336a81a5.png)

Also, please show me your entire Settings tab. You can censor out any proxy url if you'd be using one and would like to do that, I'm not interested in that, more about the priority list and other toggle-able settings in there.

Also also, please check out the [inventory section on the twitch website,](https://www.twitch.tv/drops/inventory) and ensure there are campaigns you can actually mine. Try mining one "the normal one", game of which you have setup on the priority list in the application. If you can progress it on the site, you should be able to progress it in the miner as well.

**Comment by Alicyl** [comment]
Hi there,

Of course, even though most of the solutions there had to do with that particular user being on an older "dev" version. The version I'm using is the latest that isn't a dev version—strangely, one version ahead of the one you've shown a screenshot of unless that's just an older screenshot you keep at the ready for these situations.

![Twitch_Drops_Miner_(by_DevilXD)_w2e4Ykn0Mt](https://user-images.githubusercontent.com/13776859/212531929-77fd8609-0473-4bcf-9168-f2ff9d86af95.png)

> The channel list contents themselves is dependent on the inventory, if the inventory is not there (there's no campaigns to mine), there won't be any channels worth watching either. My inventory is also empty right now, but simply because there's just no campaigns for the games I'm interested in mining.

I should have Overwatch 2's and SMITE's campaigns here which are currently active—connected—for my Twitch account.

> To see all campaigns the application knows about, wait for it to get to the Idle state, and then please try this setup of filters (and click on Refresh of course):

Those are the default filters for a fresh installation—at least they were for me when I opened TDM for the first time. I tried adjusting them as well after each refresh to no avail.

> Also, please show me your entire Settings tab.

These are the default settings (haven't changed anything since installation):

![Twitch_Drops_Miner_(by_DevilXD)_CdT9F2pJ2J](https://user-images.githubusercontent.com/13776859/212531884-3427c40c-b5f1-4430-ad7c-c0a4bb916a05.png)

> Also also, please check out the [inventory section on the twitch website,](https://www.twitch.tv/drops/inventory) and ensure there are campaigns you can actually mine.

![BVj6JdSRA8](https://user-images.githubusercontent.com/13776859/212532159-e21617ea-986f-4208-8ef5-dc15c122a460.png)
![msedge_kQPNZGVlk6](https://user-images.githubusercontent.com/13776859/212532166-7307abd1-35ce-4c85-a543-aa5b1d7ba8aa.png)

Also, I assume this is irrelevant since you mentioned that campaigns have to be active (I assume not closed or disconnected) to show up for selection, but TDM always loads up to sixty-eight campaigns before it idles.

**Comment by Alicyl** [comment]
Hi there,

I think I found the issue I unfortunately glossed over; it had to do with a game not being added to the 'Prority' list in the 'Settings' tab.

![Twitch_Drops_Miner_(by_DevilXD)_qs18C93Uwz](https://user-images.githubusercontent.com/13776859/212532534-d93b5c4b-efa0-470c-a2a6-8c5bdf2a9751.png)

I assumed that TDM would just load all of the campaigns, or just the active (connected) ones, without having to add games to the list of priorities which I also assumed only made TDM focus on an ordered list of games a user deems more important than the others. 

I didn't know that list actually determines rather a campaign is loaded into TDM or not.

**Comment by DevilXD** [comment]
> I assumed that TDM would just load all of the campaigns, or just the active (connected) ones, without having to add games to the list of priorities which I also assumed only made TDM focus on an ordered list of games a user deems more important than the others.
> 
> I didn't know that list actually determines rather a campaign is loaded into TDM or not.

This is also a functionality, possibly-slightly-cryptically hidden behind the "Priority Only" checkbox. It comes ticked by default, which makes the miner do nothing until you setup the priority list to the game of your choice, after which it'll only try to mine those and that's it - that was the "implied default" behavior in previous versions of the application. However, after the inventory sync functionality was added, the miner could now start any possible campaign on it's own, hence it was necessary to gate it behind an option.

Disabling the "Priority Only" option will disable this gate, allowing the miner to start any possible campaign it can determine as mineable for your account (active, account linked, available channels to watch), with the possibility for it to still trying to follow a priority list if there is one, mining "whatever it can" otherwise.
