### ISSUE TITLE
i can't login     ERROR:	Fatal error encountered: Traceback (most recent call last)

### ISSUE THREAD

**Issue by akirayoo** [DevilXD/TwitchDropsMiner#12]
China,Windows 11, Using v10
bro,can u add Proxy option ?

```
Please log in to continue.
2022-03-22 08:03:32.508:	  ERROR:	Fatal error encountered:
Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1175, in _create_direct_connection
  File "aiohttp\connector.py", line 986, in _wrap_create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "async_timeout\__init__.py", line 125, in __aexit__
  File "async_timeout\__init__.py", line 208, in _do_exit
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "twitch.py", line 792, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 539, in _request
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://passport.twitch.tv/login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 165, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 172, in run
  File "twitch.py", line 746, in check_login
  File "twitch.py", line 669, in _login
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 800, in request
exceptions.RequestException: Ran out of attempts while handling a request: (method='POST', url='https://passport.twitch.tv/login', attempts=5, kwargs={'json': {'client_id': 'kimne78kx3ncx6brgo4mv6wki5h1ko', 'undelete_user': False, 'remember_me': True, 'username': 'yuzusugar', 'password': '...'}})
Fatal error encountered:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1175, in _create_direct_connection
  File "aiohttp\connector.py", line 986, in _wrap_create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "async_timeout\__init__.py", line 125, in __aexit__
  File "async_timeout\__init__.py", line 208, in _do_exit
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "twitch.py", line 792, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 539, in _request
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://passport.twitch.tv/login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 165, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 172, in run
  File "twitch.py", line 746, in check_login
  File "twitch.py", line 669, in _login
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 800, in request
exceptions.RequestException: Ran out of attempts while handling a request: (method='POST', url='https://passport.twitch.tv/login', attempts=5, kwargs={'json': {'client_id': 'kimne78kx3ncx6brgo4mv6wki5h1ko', 'undelete_user': False, 'remember_me': True, 'username': 'yuzusugar', 'password': '...'}})

Exiting...

Application Terminated.
Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello o/

First of all, it appears that the traceback has included your Twitch's account password. I've edited it out, but since the edits history is publicly available, I'd recommend changing it as soon as you can, to avoid someone else stealing your account.

Second of all, proxy support isn't on my TODO list for now, `v11` will mostly include a settings file and maybe an inventory viewer as far as features go. I'll look into how hard would it be to implement, and then let you know what I think about it.

**Comment by akirayoo** [comment]
> Hello o/
> 
> First of all, it appears that the traceback has included your Twitch's account password. I've edited it out, but since the edits history is publicly available, I'd recommend changing it as soon as you can, to avoid someone else stealing your account.
> 
> Second of all, proxy support isn't on my TODO list for now, `v11` will mostly include a settings file and maybe an inventory viewer as far as features go. I'll look into how hard would it be to implement, and then let you know what I think about it.

thank you

**Comment by DevilXD** [comment]
@akirayoo What kind of proxy do you use? And how do you have it setup? I found some documentation that mentions `HTTP_PROXY` and `HTTPS_PROXY` environment variables, as well as what's called an "automatic proxy setup" stored somewhere within Windows settings, and config stored in PAC files. Would either of those work for you, or do you need a separate set of fields to input proxy URL, login and password?

**Comment by akirayoo** [comment]
> @akirayoo What kind of proxy do you use? And how do you have it setup? I found some documentation that mentions `HTTP_PROXY` and `HTTPS_PROXY` environment variables, as well as what's called an "automatic proxy setup" stored somewhere within Windows settings, and config stored in PAC files. Would either of those work for you, or do you need a separate set of fields to input proxy URL, login and password?

**socks5** and http , i use this https://github.com/Qv2ray/Qv2ray

**Comment by DevilXD** [comment]
I'm unable to get it to work consistently, the program says the requests are getting proxied, but the requests themselves usually don't get through at all, or end up with some weird EOF error. Does it need some specific configuration beyond just adding a proxy server and port it should be using? I've tried both HTTP and SOCKS proxies, using some free available.

Also, I found a v3.0.0 of the program you've linked: https://github.com/Shadowsocks-NET/Qv2ray Just letting you know.

Regardless of what I've tried, [pypac.get_pac](https://pypac.readthedocs.io/en/latest/api.html#pypac.get_pac) doesn't return anything about a proxy being in use, so that's out of the question. I could either tell `aiohttp.ClientSession` to [`trust_env`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.trust_env), which will make it possible to specify a proxy via `HTTP_PROXY` and `HTTPS_PROXY` environment variables, or just add an input for it somewhere on the Settings tab, with the env var format of `http://username:password@ip_or_address:port` (or 3 separate fields for address and port, username and password). I'd try adding this in, as long as I'd be able to test it consistently, but as I pointed out, I'm unable to do so.

I'm not sure what to do with this issue then, other than maybe just leaving it for now, and come back to the proxy topic in the future.

**Comment by akirayoo** [comment]
yep, i know 3.0, but not support xray.

i try use Qv2ray+Proxifier, it's work,but i don't want to open two software
![image](https://user-images.githubusercontent.com/50967145/161338016-21a734f4-1a3c-47b5-8c50-6b53770e9e98.png)

**Comment by DevilXD** [comment]
Unfortunately, I still cannot get a proxy to work on my side, and thus I can't just release an untested feature. Furthermore, the underlying library used by the application (`aiohttp`) to make web requests, says it only supports plain HTTP proxies: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support

From your picture, I can see that you're using a SOCKS5 proxy, which isn't supported by `aiohttp`. From all numerous attempts I made at making an HTTP proxy work, the closest I've got was getting a 503 from an HTTP server, while HTTPS servers simply refuse connection. The proxy server I'm using for testing is: `HTTP 80.48.119.28:8080` with these preferences:
![obraz](https://user-images.githubusercontent.com/4180725/161426676-8a351a01-0018-40d4-acc9-76799f554928.png)
![obraz](https://user-images.githubusercontent.com/4180725/161426703-89617fa4-3e47-4049-8388-52b236ad51b2.png)

You'll have to either help me somehow to get the HTTP proxy to work on my system (I have no experience with this what so ever, besides what I've learned while working on this issue), or I can add this feature to a temporary test branch (for which I actually have the code ready), from which you'll be able to run it as a source code and test it yourself - this will require installing Python though. Which one of those two options do you want to choose?

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/161478413-009c4702-2b14-46d8-8229-0c4ba78a29b2.png)
i try use http ,it's work too.

my qv2ray setting
![image](https://user-images.githubusercontent.com/50967145/161478657-c68d75d0-2192-4f18-aa4c-65075dc22fd0.png)
![image](https://user-images.githubusercontent.com/50967145/161478670-df787a73-5e21-40c5-869f-1eea99e7e306.png)

i think you need add rule "domain:twitch.tv" in here
![image](https://user-images.githubusercontent.com/50967145/161478836-2d3542d8-b3db-4d34-a898-628ce4d2cd2c.png)

**Comment by DevilXD** [comment]
It may be just me being behind a NAT that's interfering with proper proxy connection, because I'm still getting only 503s and nothing I tried, worked. This means that you will have to try if it works yourself, by running the application from source. Here's some simple instructions on how to proceed:

. Download (but not install yet!) Python 3.8.10 (specifically this version): https://www.python.org/downloads/release/python-3810/ Run the installer, but please follow the installation instructions below.

- Make sure to choose a "Custom" install.
- On this screen, make sure that "pip" and "tcl/tlk" options are selected. Rest doesn't matter, you can select everything if you're unsure.
![pic1](https://cdn.discordapp.com/attachments/565633053054074890/566961577430089728/unknown.png)
- On this screen, set selections to match the picture below. The installation path **cannot** have spaces in it, otherwise `pip` won't work (known bug). I recommend "C:/Python38" specifically, to avoid any surprises.
![pic2](https://cdn.discordapp.com/attachments/565633053054074890/566961630592761867/unknown.png)
- A restart is required to properly update the PATH env variable. Alternatively, you can relog into Windows if you know how to do it, it's faster than restarting.

2. Download the source code from the new `proxy` branch - make sure to switch to it first:
![obraz](https://user-images.githubusercontent.com/4180725/161598331-fa9c0636-2682-4981-966c-d3937247c85f.png)

3. Unpack the source code into it's own folder, then run `setup_env.bat`: this will install all required libraries.

4. Starting from the `TwitchDropsMiner` folder, open up `cmd` (for ex. by holding left SHIFT and right-clicking the empty space inside the folder, then selecting "Open Command Prompt here") and then run: `%CD%/env/Scripts/activate.bat` - this should add `(env) ...` at the beginning of the command prompt, indicating that you've properly activated the environment. Then just type in `pythonw main.py` to run the application.

5. Use the new Settings tab to input your proxy configuration URL - only plain HTTP is supported, so you should go with `http://127.0.0.1:20810`, reading from your pictures. Then restart the application to see if everything works like you wanted it to.

If you'd be having issues with any of these steps, please reply here and I'll try to assist you =)

**Comment by akirayoo** [comment]
`D:\Twitch\TwitchDropsMiner-proxy>python -m venv env

D:\Twitch\TwitchDropsMiner-proxy>D:\Twitch\TwitchDropsMiner-proxy/env/scripts/pip install -r D:\Twitch\TwitchDropsMiner-proxy/requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 258, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\index\collector.py", line 120, in _get_html_response
    resp = session.get(
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_internal\network\session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "d:\twitch\twitchdropsminer-proxy\env\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python38\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname`

**Comment by DevilXD** [comment]
This appears to be related to proxy usage - pip doesn't seem to like it. You'll need to disable the proxy and then try this command (I'm using absolute paths per your provided traceback):

`D:/Twitch/TwitchDropsMiner-proxy/env/scripts/pip install -r D:/Twitch/TwitchDropsMiner-proxy/requirements.txt`

If this would also fail (it can per a quick search I did, as PyPi might be blocked in China), try using the Chinese mirror index by adding this to the command: `-i https://pypi.tuna.tsinghua.edu.cn/simple`. Venv activation `(env) ...` and rest of the steps remain the same. Don't forget to reenable proxy for testing.

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/161876634-0c550edc-c401-4fa1-8a4b-117db1269073.png)
can't run application

**Comment by DevilXD** [comment]
Hmmmm, strange. `pythonw main.py` should start the application and show you the main GUI window and everything. You can try the normal console version via `python main.py` - this will start the application, but also show a console window, possibly with any errors preventing it from starting. It's possible that the error will only "flash by" and close the console window right away, but you should be able to make it stay by running `cmd /k` first. Also, please note that these commands are meant to be run inside standard Windows Command Line (`cmd`), not "Windows Powershell". These commands might (and usually will) not work inside Powershell.

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162076946-398115f2-e6fe-4dd4-b263-28c77cf6bdaa.png)
no gui

**Comment by DevilXD** [comment]
It seems you didn't read my message properly. Please try `python main.py` - there's no `w` at the end of `python` there.

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162178689-da4d85df-aa63-47e6-88a1-6e19078e42aa.png)

**Comment by DevilXD** [comment]
Yeah, just like I thought. I've pushed out a change to the `proxy` branch that fixes this issue. Please re-download the source code and continue from step #2 of my earlier instructions: https://github.com/DevilXD/TwitchDropsMiner/issues/12#issuecomment-1087831162

To avoid [having to deal with setting up the `(env)` again](https://github.com/DevilXD/TwitchDropsMiner/issues/12#issuecomment-1088197357), you can just copy it over from the existing source code folder you have - it should contain all required libraries already. Actually, the only file that got changed by the fix is the `constants.py` one, so you can also unzip just that one, and place it straight into the existing source code you have (overwrite the file of course). If you don't know how to do either of those two or you'd mess it up somehow along the way, just ignore the above and follow the instructions from step #2 - the process is the exact same as before.

Hopefully this time everything will work as it should :slightly_smiling_face:

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162286456-eb32acb6-251f-41ba-9e82-840ad94a32ed.png)
![image](https://user-images.githubusercontent.com/50967145/162286467-38b32fe7-3907-4ecd-883e-538974f39550.png)
![image](https://user-images.githubusercontent.com/50967145/162286472-716f2aad-2cd5-4035-bd1b-bf7252828986.png)
i think it's work, but how can start watch


http √
socks5 ×

**Comment by DevilXD** [comment]
> how can start watch

You have to setup the Priority List with the games you're interested in mining. You can either type their name directly, or use the little arrow to select them from the combobox list. Alternatively, just untick "Priority only" and use the Excluded section on games you don't want to mine. After modifying the games lists, you need to click on the "Reload" button for the application to recognize the changes.

The "Connecting..." websocket status concerns me a little. The inventory fetch appears to be successful, given everything on the Inventory tab has loaded. This means that the mining itself will be possible too, but without the websocket connection, the application won't be able to track the online/offline channel's statuses. This is probably why you're getting this "rejected" information in - what I'm assuming it's coming from - the Qv2ray application.

To solve this, I'll need to ensure that the websocket connection goes over the HTTP proxy as well. Since the `websockets` library doesn't appear to support proxies (yet), I'll try changing the entire websocket code to `aiohttp` websockets instead - it should be relatively easy, after giving the documentation a quick glance. I'll need some time to implement it. For now, please test if the mining itself works (the missing websocket shouldn't prevent it, if the drop timer starts to tick down, it means it works) - if so, please let me know and I'll merge the proxy branch into master, and it'll become a feature once `v11` is properly released :slightly_smiling_face:

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162522687-b48c4100-db76-49e1-8c91-ca19adbf5ad3.png)

**Comment by DevilXD** [comment]
Just pushed out a `master` branch merge into `proxy`, that includes the new websocket implementation, as well as a simple commit that passes in the proxy URL - so you should be able to test it again, now with the websocket going over the proxy as well. [The instructions remain the same,](https://github.com/DevilXD/TwitchDropsMiner/issues/12#issuecomment-1087831162) although this change is much more extensive than the last one, so you'll need to re-download and replace the entire source code. The "env" folder can still be copied over though - one of the libraries was removed / isn't used anymore, but it shouldn't matter. If you'd be unsure, you can recreate the "env" folder with `setup_env.bat` again.

Also, your message popped up *just* before I've managed to send this one, so to explain - the "no available channels to watch" issue after pressing the "Reload" button should be fixed now as well. `v11` isn't 100% stable yet, I'm still ironing out little issues like this one. Please try it again and hopefully it shouldn't happen anymore.

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162525877-020830be-ef32-40af-9637-8837e51b9a0a.png)

![image](https://user-images.githubusercontent.com/50967145/162525740-3fe512d4-89d7-4f3a-980d-9154150c6f2e.png)

**Comment by DevilXD** [comment]
It sounds like you've forgot to switch to the `proxy` branch first - the `master` branch does not contain a fix for this issue (yet), but it will once you can confirm it (hopefully) works. Please always ensure that you've switched to the `proxy` branch before downloading the source code for it (as the `master` branch has no proxy-related code added what so ever):
![obraz](https://user-images.githubusercontent.com/4180725/162527457-d7527ce8-f0e1-4c9b-b032-de24302d3bd3.png)

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162528669-77e78971-e210-4775-b3eb-0dda6d6fee20.png)
![image](https://user-images.githubusercontent.com/50967145/162528679-a840ef05-ebd7-4e02-8f78-c73c66baec5c.png)
![image](https://user-images.githubusercontent.com/50967145/162528685-262f5c52-582a-4605-971a-d61490a77f3f.png)

**Comment by DevilXD** [comment]
The "Connected" status tells me that the change was worth the effort. It also gets rid of a dependency which will lower the build time and may lower the release size as well, which is a nice bonus.

I'll need you to do one more thing. This is the "Viewers" column, on the "Main" tab: 
![obraz](https://user-images.githubusercontent.com/4180725/162561932-54843fe1-3e04-4d57-8f8f-8f201f4e1ca7.png)

Please verify that the "Viewers" column updates every about 30-60s - you can do so by observing it closely during that time and noticing if the numbers change. The updated viewer counts arrive over the websocket connection, and this will let me verify that everything regarding the websocket works correctly. If the numbers wouldn't change after more than 120 seconds of you staring at them, please let me know as well.

**Comment by akirayoo** [comment]
![image](https://user-images.githubusercontent.com/50967145/162562203-c7e9a5e5-99b0-4b59-826f-69832b27ccda.png)
![image](https://user-images.githubusercontent.com/50967145/162562231-7a1ceadd-eeb5-4f60-85a0-b6f4287c4caf.png)
![image](https://user-images.githubusercontent.com/50967145/162562249-ffca2ecc-fe7e-4e4a-83a3-083a4b36d53e.png)
![image](https://user-images.githubusercontent.com/50967145/162562256-5fae530f-4186-44ac-833f-cd81346c3e37.png)

**Comment by DevilXD** [comment]
They do - great! This concludes proxy support as a feature then. The `proxy` branch has been incorporated into `master` and deleted, since it's no longer needed. This means that proxy support will be included in `v11` once it releases.

If you want to continue using this test build of `v11`, you are more than welcome to do so :slightly_smiling_face: The merge doesn't add any code that you don't already have on your side, so there's no further actions from your side needed at this time. Once `v11` releases (which should hopefully be pretty soon), you can just switch to using the EXE version like before.

**Comment by akirayoo** [comment]
ok , thank you

**Comment by DevilXD** [comment]
Well, because it seems that I've nailed down every feature and bugfix I wanted for now, `v11` is live now: https://github.com/DevilXD/TwitchDropsMiner/releases
