### ISSUE TITLE
Option to manually add channel(s) to farm Twitch Points

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#128]
I have a couple channels that I want to farm points. This tool would be perfect for it, so I can free resources from my system :)

**Comment by lnx00** [comment]
#70

**Comment by DevilXD** [comment]
Yes, unfortunately I'm not willing to add any way to setup specific channels for watching, since the entire rest of the application is drops-oriented and wasn't made with that in mind. If someone would still like this feature, they're welcome to submit an issue stating they'd like to work on it, I can give some pointers on where to look for in the code and how it could work, and they'd need to implement it. PRs adding more than just translation files are welcome.

Fow now, this is a no-deal feature, at least from my side. There are more important features I'd like to add first.
