### ISSUE TITLE
Trojan:Script/Phonzy. A! ml detected when extracting

### ISSUE THREAD

**Issue by klept0** [DevilXD/TwitchDropsMiner#13]
Grabbed v11 and before it completed its extraction that popped up

Trojan:Script/Phonzy. A! ml

**Comment by DevilXD** [comment]
Hello o/

This is strange, and obviously a false-positive. Here's a VirusTotal scan of the file, at just 2/59 score: https://www.virustotal.com/gui/file/934c9153111307383bfc3ccec259ab19aa62a0e6f1869f4c048f788096cd8375

Which AntiVirus software are you using? A quick cursory Google search says that the `ml` at the end of the detection means the result comes from a machine learning / AI module, which are quite prone to false-positives: https://www.reddit.com/r/antivirus/comments/no917n/help_with_trojanscriptphonzyaml/h02734t/?context=3
Also, it could be due to me using PyInstaller to package the code into an executable as well. Strange that it popped up only now: https://www.reddit.com/r/techsupport/comments/of8vph/windows_defender_identified_my_own_program_as/

I personally had an issue with running `v11` on a workstation, featuring BitDefender Endpoint Security with pretty much zero configuration options available (like specifying a whitelist) or a way to turn it off. The executable was killed and quarantined as soon as I tried enabling the autostart option, which is when the registry is modified. The relevant code for this can be found in the [registry.py](https://github.com/DevilXD/TwitchDropsMiner/blob/master/registry.py) file, which serves as a wrapper around [standard lib Python's `winreg` module](https://docs.python.org/3/library/winreg.html), and the actual registry-modifying code comes from `gui.py`:

https://github.com/DevilXD/TwitchDropsMiner/blob/3bccbc45c3fb14420e6acf61542bd65cbe8a6eed/gui.py#L1148-L1162

The project is open source, so all code is available for review. I got it to work (and not get quarantined) on my workstation by running it as an Administrator. You may need to whitelist the application to avoid further problems.

**Comment by klept0** [comment]
Microsoft Defender on one machine and BitDefender on another both flagged it. Ill give it another shot and see if I can just let it do its thing sandboxed to see if it flags again

**Comment by DevilXD** [comment]
I also had to deal with BitDefender as I noted, but it ultimately let it run just fine, only quarantined it when I tried to enable autostart, and even then, when I brought it back from the quarantine and ran it as an Administrator, enabling autostart went through just fine.

I suspect it also has to do with the executable not being signed in any way, unlike most other commercially available software. I can look into signing, but from a quick search I did a while ago, it required buying a certificate - which I'd like to avoid if possible.

Alternatively, one can also just run the application straight from source, although this requires installing Python 3.8.10 (the one used to build this executable) on the target machine. The source code can then be downloaded and `setup_env.bat` ran to setup the environment, then it's just a matter of running `main.py` from that environment. More specific instructions on how to do this can be found under issue #12: https://github.com/DevilXD/TwitchDropsMiner/issues/12#issuecomment-1087831162

**Comment by klept0** [comment]
I will look at setting up a test env and seeing if I can duplicate the issue on a successful compile. Give me 24-48 hours to report back so I can get things setup and running correctly.

**Comment by Galaxtxc** [comment]
> I will look at setting up a test env and seeing if I can duplicate the issue on a successful compile. Give me 24-48 hours to report back so I can get things setup and running correctly.

any update?

**Comment by DevilXD** [comment]
I've added some building instructions to the README, under "Advanced Usage / Build Instructions" section: https://github.com/DevilXD/TwitchDropsMiner/blob/ddd689c5558ba42c01e52b322fa434a86bbda625/README.md?plain=1#L34-L40

**Comment by DevilXD** [comment]
It turns out that on my workstation, the user's autostart key was somehow not owned by me as the user. I got the miner to run without quarantine or other problems, by changing the registry key's ownership to me, and now it doesn't even need to be ran as an Administrator. My suspicion is that the last time I tried it, because I didn't own the key, the miner got the change denied, and that somehow upset BitDefender and caused it to quarantine.

I also thought about submitting the application for review as a false positive, apparently it can help mitigate the issue. I'd need a list of affected AVs for this though. BitDefender appears to be generally fine with the app running after sandboxing, the only time it applied a quarantine was because of the missing permissions issue I described above, so there's no real issues from it's side. Is Windows Defender the only one affected here then?

[Btw, you can also submit the file for review to Windows Defender yourself,](https://www.microsoft.com/en-us/wdsi/filesubmission) but I'll do so as well once I get home today.

**Comment by klept0** [comment]
I took forever with life stuff but I did get it compiled and it seems as thought BitDefender is just being a PITA. I will submit it from your file and my file so they get as much info as possible and I do appreciate the back and forth so we could come up with a good resolution. Let me know if you need anything else you can close this out as a squished bug due to Windows and BitDefender being super awesome and spectacular!

**Comment by DevilXD** [comment]
Out of all of those, I felt like the only one worth looking into would be BitDefender. This is a result of my report:

![obraz](https://user-images.githubusercontent.com/4180725/164537628-f15c4134-834f-4724-8938-5fd09bc9bef0.png)

Other than this, as I said, I can't really do much about false positives, maybe besides contacting all of those other AV companies and telling them to stop recognizing apps built with PyInstaller as malicious. And if you or anyone else wouldn't trust the executable, you are always welcome to follow the Advanced Steps instructions and run it from source - this has an added benefit of the master branch always having the latest additions available. I'm only providing the executable for convenience's sake, as it's simpler to use for an average user, compared to doing all of those steps.
