### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by DuoZock** [DevilXD/TwitchDropsMiner#135]
Is it possible to prioritise the drops that expire the fastest or watch multiple streams. and is there a way to watch streams for drops where you are not connected to the game for the drop, since you can get the drop without connecting to the game.

**Comment by DevilXD** [comment]
Hello o/

> Is it possible to prioritise the drops that expire the fastest

Yes, by putting their game high up on the priority list, the drops will be mined first before other games.

> or watch multiple streams.

Please see #133 where I've just explained why that's not possible.

> is there a way to watch streams for drops where you are not connected to the game for the drop, since you can get the drop without connecting to the game.

There is not, and will never be, a way to use this miner without having a linked account - this is because it leads to abuse. For specifics of this, you can check out #84.

Does this answer your questions?

**Comment by DevilXD** [comment]
It's been two weeks and no answer has been given, so I'm assuming this explains what you've asked about, and this can be closed now.
