### ISSUE TITLE
VirusTotal Alerting

### ISSUE THREAD

**Issue by PESMIT** [DevilXD/TwitchDropsMiner#137]
Was there any particular reason why this EXE would appear as potentially malicious when checked against VirusTotal?

**Comment by DevilXD** [comment]
Hello o/

Please check out #13 for more information. The gist of it is that some AV engines have the PyInstaller bootloader signature added in their databases, most likely (imo) because one can make both "good and bad" scripts, and then package them with PyInstaller into an exe. More notable AV engines like ESET or Kaspersky know about this, and can specifically target other portions of the compiled exe, knowing the bootloader is there just to execute the script contents besides it, not some actual malicious code in itself.

This results in many of the inferior AV engines to just cut the corner and say that it's "at least suspicious", flagging the file as potentially harmful, which results in the "detections" you are seeing in VirusTotal. I specifically made all of the source code openly available, so that one can verify there's nothing "funky" going on. To verify the bootloader is the problem, you can try building an empty Python file (like a main.py with nothing in it, just empty text file), and then running the resulting exe through VirusTotal to see how many engines flag it. Here's the result from my quick test: https://www.virustotal.com/gui/file/50c380fa9a3d8da042ee9083da5d7828130dfcd775be207194f4d1881b04ae0a

Even with smarter detection logic implemented, this application accesses Windows registry, code to manipulate which is included in the exe. It's doing this to support the autostart feature, by adding an entry to the `HKCU/Microsoft/WindowsCurrentVersion/Run` registry folder, possibly prompting more detections. Again, notable AV engines like ESET or Kaspersky can figure out there's nothing bad going on, while lesser engines will simply raise flags and move on. BitDefender I have installed on my work computer will lock the executable and sandbox the miner for good 5-10m when I'd try to run it right after building, but then release the lock and say "all good" eventually, possibly due to the report I sent back in #13.

Does this answer your question?

**Comment by PESMIT** [comment]
It does, thank you. I had assumed as much as even in VirusTotal the domains interacted with were all Twitch as described in your README at the start. Just wanted to know in a bit more detail. Thank you!
