### ISSUE TITLE
Stuck on Expired Drop

### ISSUE THREAD

**Issue by scryptio** [DevilXD/TwitchDropsMiner#15]
I ran into an issue where the Miner is stuck on an expired drop at 32.9% (also showing so in the inventory). Restart fixed it as it seems. This might need another check.

No error shown. Unfortunately there is no active logging

**Comment by DevilXD** [comment]
Hello o/

> also showing so in the inventory

Do you mean the Twitch's inventory page, or the Inventory tab in the application? I've had a friend of mine run into an issue before, where they had sequential campaigns (second one started when the first one expired) with identical drops, and if they happened not to earn all the drops from the first campaign that expired, the first drop from the second campaign would start at the same percentage as the last drop that was being mined in the first campaign, and then continue to report said wrong percentage until it actually reached the same progress, at which point it'd "get unstuck" and work properly. The thing is, this is just how Twitch reported the progress, and thus I can't really do anything if the underlaying source data itself is wrong.

When this happened, both the [Twitch's Inventory page](https://www.twitch.tv/drops/inventory) and the in-app internal state still had the same (wrong) data, meaning that what was displayed in the app matched the webpage. If this was also the case for you, then as I said, I can't really do anything about it. If, however, the inventory page was showing a different percentage / progress than the application, then there might be an error somewhere. A quick glance I just did over the code, doesn't tell me where the issue may be - everything appears to be correct. Without more information on the conditions under this has happened (or repro steps), this may be impossible to "fix".

**Comment by scryptio** [comment]
Hey,

if I remember correctly the percentage was the same on the website and within the app. It was stuck in this state for almost 3 hours. I just restarted and it fixed itself.

The percentage was shown in "Inventory" but the campaign expired on "All Campaigns" IIRC.

So it seems the internal maintenance task didn't notice it either (or it didn't get called for whatever reason). Else it should have fixed it as per your comment on the code? Only a manual application restart allowed me to continue mining.

Maybe a check would be useful to check whether the percentage didn't change after two restarts or something like that. But even then, you already have a maintenance task implemented. I will keep an eye on this and report back when and if it happens again.

**Comment by DevilXD** [comment]
> the percentage was the same on the website and within the app. It was stuck in this state for almost 3 hours.

As I explained in my previous message, if both the website and the app report the same percentage, and the percentage is stuck - it's a Twitch bug, and there is literally nothing I can do about it. For example, let's take your 32.9%, which is about 79 minutes of progress on a 4 hours drop. The app asks Twitch for current inventory state on startup, and Twitch then reports 79/240 minutes for the drop's progress. Then every minute, there's a progress update that says the drop's progress is still 79/240, which will appear in the app as the progress is stuck - but as I said, this can happened if you happened to have a sequential campaign that had partially mined drops. Nowhere here I can tell with the amount of data given, that the drop's "real" progress starts at zero - it will just continue doing this, until the real progress actually reaches those 79/240 minutes, at which point it'll start reporting correctly again. The maintenance task has nothing to do here, since it's Twitch itself returning incorrect data. Here, I made this simple graph to help you understand the issue:
![obraz](https://user-images.githubusercontent.com/4180725/163925052-7acdbceb-1c7b-4d29-8ec0-808dab456412.png)

Again, this is just how Twitch reports the progress for some reason, and since I can't deduce the real progress of the next drop there, this is a "can't fix" issue. The good news is that it's purely visual, and you're not actually losing any progress, it's just reported in an incorrect way. It also only happens when there's an expired campaign that has a new campaign following it, that both happen to have similar / identical drops as well. The condition is very specific, so this will happen rarely, albeit will still happen nonetheless. 

> I just restarted and it fixed itself.

I'd call this a coincidence, since normally this Twitch's state is independent of whether or not you're watching / mining anything, and will just pass on it's own. In your case, it'd be stuck for exactly 79 minutes, so while it may appear that restarting did anything, it really just passed on it's own like I've explained.
