### ISSUE TITLE
Can you make it work on Android/Termux?

### ISSUE THREAD

**Issue by Verdugo-0** [DevilXD/TwitchDropsMiner#160]
There's a Drops farmer for LoLEsports, Capsule Farmer Evolved (https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Advanced-Installation-for-Android), i've been using this tool for 3 weeks by now and it works excellent, the only problem? Only for League of Legends. So if You could do a tutorial on how to make it work on Android it would be great. Thanks for the attention.

**Comment by DevilXD** [comment]
Hello o/

I gave it a cursory overlook, and it seems that a "console application" is required for it to work. This miner isn't one, instead of the console window, a proper UI has been added. You could try the virtual screen emulation trick from #17, but that's about it - you probably won't be able to setup the miner (maybe by editing the settings file) or check on the progress in any way.

If you're looking for an all-purpose console-based Twitch drops miner, you can try this one: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2  The instructions are the same as the ones you've linked, but instead of `main.py` you have to run whatever this miner requires. If you'd be having trouble, you can try making an issue under that project instead.
