### ISSUE TITLE
Opening the UI causes NVIDIA Control Panel to show up

### ISSUE THREAD

**Issue by XtramCZ** [DevilXD/TwitchDropsMiner#168]
When I have the miner minimized to tray and I double click it, sometimes NVIDIA Control Panel launches with it.

**Comment by DevilXD** [comment]
Hello there o/

Hmm, well... There's obviously nothing in the miner that'd interact with other applications on your computer (since Chrome login method doesn't work anymore), especially anything from Nvidia. Even link opening isn't directed at any particular browser, it just tells the system to "open this in a browser" and the rest is left up to the system.

I imagine what's happening is that the icon disappears after you click it for the first time, and then you click on Nvidia's icon in the traybar right after with the second click. Only a single click is needed to bring back the application window - please avoid double clicking to avoid this issue.
