### ISSUE TITLE
Why is there no ID input box after installation

### ISSUE THREAD

**Issue by 1279494766** [DevilXD/TwitchDropsMiner#169]
May I ask how to solve the problem where an open program cannot input an ID and password after building an executable file.

**Comment by DevilXD** [comment]
Hello there o/

The old login method doesn't work anymore and has been removed. Now you have to login through the provided code. Have you tried pressing the Login button?

**Comment by 1279494766** [comment]
It does not have a text box for entering password and ID, and the login button cannot be grayed out.

**Comment by DevilXD** [comment]
That's because the current login method requires you to enter a code here: http://twitch.tv/activate  This page should automatically open in your default browser when you'd click on the Login button. Pressing the login button also tells you the code, that you can grab from the Output section of the application's window.

**Comment by 1279494766** [comment]
Thank you very much. May I ask if this miner can have multiple Twitch accounts?That would feel very good！

**Comment by Totesfleisch** [comment]
> Thank you very much. May I ask if this miner can have multiple Twitch accounts?That would feel very good！

This Tool is intended for personal Use only, which means one Account only, your own!

**Comment by 1279494766** [comment]
Okay, thank you very much for your help. This tool makes people feel very good！
