### ISSUE TITLE
Dont mine drop when remaining time is insufficient

### ISSUE THREAD

**Issue by aalbouy** [DevilXD/TwitchDropsMiner#171]
Drops are being mined even if the remaining time to get the drop is superior to the remaining time of the campaign, and it results in time being "lost" for an unminable drop

Would be nice to skip those drops I guess

**Comment by DevilXD** [comment]
Hello there o/

Yes, I was aware of this. However, most of the time this does not matter - my experience tells me that campaigns lasting about a week, on average, are completed within 4-5 days already. Even in the worst case scenario of cutting down 3 hours off a drop, it'd still let you finish it fully.

Besides, short campaigns often get extended. For example, there was recently a case where there was two 60m drops on a stream that was supposed to last 2.5 hours, but there was some difficulties both with the stream, and with the drops campagin (times were right, but drops weren't enabled on the channel). This lead to over 30m of combined delay, and the campaign getting extended for an hour longer to compensate, Those drops (or at least the 2nd one) would be missed if such a system were to be implemented.

The current stance of mine on this remains the same - it's probably not worth complicating the logic even more to account for this, as the benefits are too small to justify me spending time on it. If someone would really need it, they're welcome to open a PR implementing this change. Otherwise, I'm leaving this as a NoFix, at least for now.
