### ISSUE TITLE
Usability ideas for the System Tray

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#180]
First, please add an outline for the icon, I have a purple themed OS and it's basically invisible.

And as a UX feature, when the app fully crashes, perhaps changing the icon color from purple to black or red would help, since currently we have no way to know when it stops working. I missed several drops because of this already.

Even calling an OS system notificacion would be helpful, too.

**Comment by DevilXD** [comment]
Hello o/

Outline for the icon sounds fair. I'll see what I can do to make it more noticeable. on a similarly shaded background. I worry a little bit that scaling will make the outline either too noticeable, nor barely noticeable, but if so, I can try remedying that with some proper icon sizing within the ICO file, I guess.

Regarding crashes and "knowing" when it stops working - there's a disclaimer on the README page specifying that this miner isn't "unmanned", and you're supposed to check on it every so often, for this very reason. Regardless, I can try making it so that a fatal error will restore the application back from a tray icon. It won't be always possible though, depending on the origin of the crash, but since the tray icon lives in a separate thread on itself, it should work in 99% of the cases anyway.

**Comment by DevilXD** [comment]
Would it be possible for you to take some screenshots of how the icon looks like for you, in the taskbar and then in the tray? I kinda want to see what would be the best way to approach this.

**Comment by notNSANE** [comment]
System Tray (issue is here): 
![image](https://user-images.githubusercontent.com/7162375/235325859-9618b0b3-13cf-4e49-a7b2-645df684dd03.png)

Taskbar:
![image](https://user-images.githubusercontent.com/7162375/235325866-e33843f8-4bbf-46a7-a689-d86800f988dc.png)

**Comment by DevilXD** [comment]
Hello,

Is this still something that should be worked on, or is the dynamic status icon that was added a while ago enough to resolve this?

I can try adding some kind of an outline to the icon, but I'm afraid it'd just end up looking ugly, when windows ends up down-scaling the icon to the tray size.

**Comment by notNSANE** [comment]
as it is right now, I think it's fantastic and does its job correctly, I
consider this issue solved
