### ISSUE TITLE
[Enhancements?]

### ISSUE THREAD

**Issue by LukysGaming** [DevilXD/TwitchDropsMiner#188]
Add option to ignore specific channel from drop campaign (eg: general drops from rust drops etc.)

**Comment by LukysGaming** [comment]
eg. possibility to remove specific streamers from this
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/49752472/30640c09-1b24-46cf-a99d-5de45102cdb1)

**Comment by letum00** [comment]
This specific drop campaign has multiple teams. There are five drops which are earned no matter who you watch, then nine "teams" who have two drops each. For each team there are multiple streamers you can watch for each drop, but the miner does not allow you to switch because it seems to believe certain streamers do not have the drop available.

For example: The streamer mewnfare was automatically selected by the miner. It unlocked that streamer's item and collected it as well as one of the generic drops. Then the miner moved on to summit1g like in LukysGaming's post, however summit is not on any of the nine teams and will only count for generic drops. The miner would hopefully have been able to recognize that Buddha and Mendo's streams are now available as the second drop for the team it just watched.

I'm not sure how the miner determines which streams are valid, but when the gift column has an X in it you cannot force it to switch, either.

**Comment by LukysGaming** [comment]
yup, just simple "ignore this streamer" would help

**Comment by letum00** [comment]
I agree, but I also think there's something wrong with how the miner is determining if drops are enabled or not. 

I wonder if, once you have all of the general drops, it will just stop watching altogether even though there would be many more drops available. I don't know anything about anything, just enough to pull and run using the author's instructions. I wish I could review the code myself to enable the Switch button to work on streams the miner thinks don't have drops enabled even though they clearly do.

**Comment by LukysGaming** [comment]
@letum00 I had to clone the whole repository and run the "dev version" because it wouldnt work for me

**Comment by Mirr0red** [comment]
> 

In twitch.py file, line 1166, you can comment that line using a #, and then recompile it, and you will be able to switch to any streamer.

**Comment by letum00** [comment]
@Mirr0red that's exactly what I just discovered myself. Most of the streamers are not setting the Drops Enabled tag. I'll comment it out and see if it'll do all streams.

@LukysGaming I also cloned and compiled like you. I am happy to have this miner. The last one I was using stopped getting updates. I am grateful to everyone involved.

**Comment by Mirr0red** [comment]
> That did the trick, the switch button works. I imagine for this campaign type we'll have to manually switch channels every two hours. Having the ability to ignore or disable certain streamers like this original request was for would definitely be helpful if the campaign is too complex for the miner.

I believe that with adding priorities to the compaigns, you would be able to ignore streamers, and it will also allow you to switch streamers automatically as soon as a campaign is fully claimed.

**Comment by CDeLeon94** [comment]
Seems clear to me that this is only considering 1 drop at a time. 
Familiarizing myself with the code, looking for a way to have it prioritize streamers that are eligible for multiple drops. 

Aside from that, having a Campaign priority list would also be useful in the case of Rust or any other game running similarly configured drops.

**Comment by legalcormorant** [comment]
This 'Twitch Drops Miner' is dogcrap in it's current form. Doesn't even work most of the time, errors out when trying to claim drops (the other open issue), have to compile it and edit code to even work half-assed, DevilXD won't even take a minute to compile it and push the most recent updates live. Absolutely useless for this Rust campaign: after it finishes one (the 5-drop main one) the campaign tab shows at least 10 it could do but since the first campaign is completed, "No available channels to watch. Waiting for an ONLINE channel..." .

**For anyone reading and wanting to use with this Rust campaign don't even bother.**

**Comment by DevilXD** [comment]
> DevilXD won't even take a minute to compile it and push the most recent updates live, instead expecting users to install Python and Git to compile it yourself, zzzzzz.

This is because I don't want to push out a half-done release that's still far away from anything I can call "good enough" for a release candidate. It isn't working like it should, and this issue (among many others) makes it quite clear. And also I'm way too much overloaded with IRL work to find time and move forward with any of the existing issues. This project needs a maintainer, or at least someone willing to help with development.

I also want to remind you that this project is entirely free. You're welcome to not use it if you don't find it good enough for your use case.

For everyone else here, the issue of the "drops enabled" tag not updating is now tracked under #189. The ability to ignore drops (and thus their associated channels) is tracked under #170. Both are in a pending state of me (or someone else) finding the time to work on them. Given these, I see no reason for ignoring channels as a feature, so this one is getting closed. If you'd have anything to add to this topic, please do so under one of the two relevant issues I've just linked.
