### ISSUE TITLE
Unable to mine Rust Campaign

### ISSUE THREAD

**Issue by ihunterj** [DevilXD/TwitchDropsMiner#198]
I've installed the Twitch Drops Miner (master) and compiled this myself. The app seems to think I'm not linked to FacePunch for the drops when I've signed in and am definitely earning the drops (I have been manually doing so), yet it says not linked.

Is there anything else I need to do for this to work?

**Comment by ihunterj** [comment]
Mine is different, they seem to get the streamers come through and they get recognized as linked to the drop event.

`08:42:16: No active campaigns to mine drops for. Waiting for an active campaign...`

**Comment by Stiphr** [comment]
Download the new master build, compile it and use it, Dev has already fixed it. (Temp Fix)

**Comment by ihunterj** [comment]
I did do this, same outcome.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/8628149/b647a3b0-e752-41ea-93d1-bdec23f63943)

**Comment by DevilXD** [comment]
Hello o/

I've had someone report a similar thing over discord yesterday. The problem was, they haven't linked their Rust account properly.

Please go to the campaigns page, find the Rust campaigns, then scroll all the way to the bottom portion of the last Rust campaign. You should see two extra sections there, called "Progress & Redemption" and "Connection".

If your account isn't linked properly, you'll see a "Connect" button like this:
![connect](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/5aa7d799-e810-4d63-a714-1a5c140ab2bb)

If it is linked properly, you'll see a green indicator stating so:
![indicator](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/8487bcf7-4b6b-4564-85f2-16d9016825e1)

If you can see the Connect button, please try using it to ensure your account is properly linked, and you can see the green indicator. If the linking would seemingly succeed, but the indicator wouldn't appear, try logging out of the game platform account (Facepunch in this case) first, then clicking on the Connect button and logging back in during the linking process. The same can be repeated by relogging to Twitch first - both of these actions ensure the linking process is able to work with fresh session tokens.

Once you can see the indicator, press the Reload button in the miner's Settings tab to let it pickup on the linking change. Or you can just restart it, your choice. As an additional verification step, you can try finding the Rust campaigns on the Inventory tab and confirming they all say "Linked" as expected.

**Comment by ihunterj** [comment]
On the inventory tab it now shows as Linked for all of the Rust streams, however, no channels are appearing and the output remains the same.

`11:34:40: No active campaigns to mine drops for. Waiting for an active campaign...
`

**Comment by ihunterj** [comment]
Weird, took some playing about but now this is working - thank you for your help!
