### ISSUE TITLE
No active campaigns.

### ISSUE THREAD

**Issue by zuvii** [DevilXD/TwitchDropsMiner#203]
Hi there, i was wondering on how to use this miner because i connect my account and still it says theres no campaigns i can do.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134121948/ed7f8454-1b94-4a2c-9e71-ab0ed18e4e06)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134121948/debe1b71-bd40-4640-870f-1fe68e412b1f)

**Comment by zuvii** [comment]
accounts are also linked but it doesnt say so in the thingy 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134121948/57de6377-87e8-4273-8266-e59f7ed6cd75)

**Comment by zuvii** [comment]
looked around and saw that its supposed to say connected here:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134121948/aa21331d-98f8-4884-bf1a-4847077c9842)
But im connected and clicked refresh many times nothing happens any idea?

**Comment by afda1** [comment]
I am confused too as for some reason it doesn't register active channels when they are active.

For example hjune is online now but the bot says that there are no streams online for drops now. What do I do?

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/118804612/eabad045-57d5-4478-86ef-b06a8b7681b6)

**Comment by DevilXD** [comment]
@afda1 This is related to #189, and it's entirely different from this issue, which is an account linking problem. Please check out the discussion there.

**Comment by DevilXD** [comment]
@zuvii Hello o/

Yes, the issue you're experiencing is most likely related to the missing "Connected" indicator/badge/status. The most likely cause of this is stale sessions causing the linking process to remain incomplete. Please try doing the following:

- Disconnect your Facepunch account from Twitch. This should be possible to do somewhere on the Facepunch account management page. On the Twitch side, go to the [Connections tab in the settings,](https://www.twitch.tv/settings/connections) find Facepunch and hit "Disconnect". If disconnecting both or either sides is not possible, it's fine - it's recommended to disconnect first if possible though.
- Log out of Twitch and Facepunch accounts.
- Log back into Twitch - this gives you a fresh Twitch session token.
- Click on the "Connect" button under the Rust campaigns, then proceed with the linking. You'll need to log back into your Facepunch account somewhere during the process. This logging back gives you a fresh Facepunch session token.
- With both session tokens refreshed, the linking process should complete fully, and the green "Connected" badge should be visible now.

Please let me know how it went.

**Comment by zuvii** [comment]
> 

Hey again, it worked! thanks alot for that. wasnt in the connections tab it was in the rust drops page for the game itself but still.
thank you :)

**Comment by zuvii** [comment]
Could i ask one more thing please?
i wanna play valorant while this thing is running and they usually ban for 3rd party programs that run and stuff.
is there a chance that i could get banned for that or like what does it do in the background? (sorry for the dumb questions)

**Comment by DevilXD** [comment]
> Could i ask one more thing please?
i wanna play valorant while this thing is running and they usually ban for 3rd party programs that run and stuff.
is there a chance that i could get banned for that or like what does it do in the background? (sorry for the dumb questions)

There should be no issue. The only thing running in the background would be Python interpreter, hidden within the compiled executable. If you'd be too worried, you can also run it from source, with only `pythonw.exe` running. As long as the interpreter won't try to access the game's process, no Anti-Cheat software or Anti-Virus should ever have a problem with the miner. Some poor quality AV engines will flag the executable as a "virus", most likely due to some actually malicious programs being compiled with PyInstaller as well, the exact same way I use to package the Python script into an executable. You can read up more on this topic in #13.

> Also, is there a way this could work for league drops?

Any timed Twitch drops should work just fine. Event-based drops are not supported, I've never even seen one before. Unless you mean some other kind of "league drops", there should be no issue here either.

Also, since this issue is now solved, I forgot to close it. Doing it now.

**Comment by DabzD** [comment]
hi this happened to me even when rust drops are connected tried to log out and log back it still saying no active campaingns

**Comment by DevilXD** [comment]
@DabzD This issue is already closed. See #189 as it'd most likely apply to you.
