### ISSUE TITLE
Stopped working? 

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#205]
Warframe has a drop right now, but TDM isn't reading that it has a drop:

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/7162375/d0dfb147-fd3c-4ed5-b689-bdba1360dc5f)

proof: 

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/7162375/573d8781-2bf0-435e-98ae-068536536c11)

**Comment by DevilXD** [comment]
Hello o/

There's no "drops enabled" tag on the channel, so no drops can be earned on it, even if it's ONLINE: 
![obraz](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/699ab966-b279-4d18-98fa-acc2a1f25415)

Are you using the latest master build? There was a temporary change put in place to ignore the missing tag for now. since apparently the tags changed a little and the drops tag is no longer required to be there. More info can be found in #189. A development build created from the latest changes can also now be found as as Pre-release in https://github.com/DevilXD/TwitchDropsMiner/releases

Please git it a try and tell me if it worked or not.

**Comment by notNSANE** [comment]
I created a build some months ago that was working until I checked that specific stream. Perhaps they forgot to enable it... well, it's fixed now with the new build, and I also saved 15M of space, so, thanks!
