### ISSUE TITLE
No channels, status always Idle

### ISSUE THREAD

**Issue by LoneKnightz** [DevilXD/TwitchDropsMiner#208]
HI DevilXD, 

Thanks for providing this tools. 

It works fine servel weeks ago but recently it cannot find any channel or campaigns. And the output are always: output always No active campaigns to mine drops for. Waiting for an active campaign...

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/22530228/d3a6f083-0903-4cf1-a457-02e127621679)

I checked the issue 189 but mine did not have any channel in that windows. 

I tried new pre-release version, re-login, compiled version from issue 189 but all of them seems are not working. 

Can you help with this ? 

Thanks

**Comment by DevilXD** [comment]
Hello o/

Please check out #118 to see if that could be helpful. For a campaign to qualify for mining, you have to have your account linked to the campaign's game first too. Use the Inventory tab and adjust the filters to search for the campaign you want to mine, and ensure it says "Linked" next to it.

**Comment by AirHeadsbuirse** [comment]
Im having the same issue actually. Have games added. In inventory it says the campaign is linked. Let it run for 4 hours and still no change or activity.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/66130186/6102f90d-8a7e-499b-989a-cbbe69d1e46b)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/66130186/3f2d93b6-3222-4451-b624-f6c223342a06)

**Comment by DevilXD** [comment]
@AirHeadsbuirse Your issue is entirely different, because you already have the channels added and displayed on the channel list. This issue is about "no channels, status always idle" as it's title says. Please make sure your issue actually matches the original report before adding to the issue next time.

From what your channel list displays, none of the channels have the "drops enabled" tag, so neither of them can be used for mining: 
![obraz](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/696a70a8-f653-414d-94b3-46467c2edb4f)

Check out #189 for the current discussion, explanation and progress on that issue. Pre-release builds that bypass the tag requirement are available in the Releases section.

**Comment by LoneKnightz** [comment]
> Hello o/
> 
> Please check out #118 to see if that could be helpful. For a campaign to qualify for mining, you have to have your account linked to the campaign's game first too. Use the Inventory tab and adjust the filters to search for the campaign you want to mine, and ensure it says "Linked" next to it.

Hi DevilXD,

Thanks for the reply. 

That works ! Thanks for your help. 

I am not sure what's going on I linked them before but seems it unlinked for unknown reason. 

Thanks

**Comment by DevilXD** [comment]
Glad it's resolved =)

**Comment by AirHeadsbuirse** [comment]
> 
I misread, sorry.
