### ISSUE TITLE
Trojan.PSW.Python.iv False positive?

### ISSUE THREAD

**Issue by Deputy1389** [DevilXD/TwitchDropsMiner#209]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/15461586/8f2336be-5965-472e-b44d-21d92732def9)

**Comment by DevilXD** [comment]
Hello o/

Yes, if you use a shitty antivirus, you can expect shitty results. You can get a non-zero score from many others programs, just google "discord virustotal" as an example. PyInstaller the miner is packaged with, uses a pre-compiled bootloader, a signature of which can and will be detected by shitty AV engines, because there's many malicious programs out there that also use PyInstaller to hide whatever malware Python script someone else thought of at one point in their lives.

This program being open source if one of the benefits of this project - anyone can have a look at the source code and see what it does. False positives were reported as early as #13 before. At that time, I considered Bitdefender to be one of the better AV engines out there, hence I actually reported it as a false-positive and Bitdefender cleared up their signatures at the time.

There's nothing in the existing code base that does anything malicious. If you don't trust the pre-built executable, you can build one yourself from the source code, or simply install Python and run the entire thing from source code without building.

Does this answer your question?
