### ISSUE TITLE
[Feature Request] Automatic pick up

### ISSUE THREAD

**Issue by Suz1e** [DevilXD/TwitchDropsMiner#21]
I tried it last night. After opening the software, I went to sleep. When I woke up in the morning, I found that only one task was completed. The second task could not be started automatically.

**Comment by DevilXD** [comment]
Hello o/

That's not enough information to work with. There's multiple reasons why this could be the case, including online channel and game unavailability, and not having your account linked beforehand. Please verify that your account is linked and there's an online channel streaming an applicable game, that enables progress of a drop, before reporting it as an "issue". The application is unable to do it's job otherwise.

**Comment by Suz1e** [comment]
![QQ截图20220618102429](https://user-images.githubusercontent.com/52779408/174419001-37706f96-7d72-4a8f-b6b9-2ba5c7e84a4e.png)
You can see here is 1/7
I think it can be set that if it refreshes "Claim Now" then it will be clicked, like this script
![QQ截图20220618102551](https://user-images.githubusercontent.com/52779408/174419041-a6128de4-d8c6-4517-b503-d08b7dea6ab7.png)

**Comment by DevilXD** [comment]
This doesn't answer anything for me. The code presented seems to be all about claiming a drop, which is already implemented, and the claiming is rechecked every hour to further ensure it won't miss anything. Again, please ensure that there is an available channel streaming an applicable game, with drops being enabled - if it fails to claim a drop again, please take a picture of the application main window (channel list included, you can blur out the user ID if you want to), and include which games you have selected via the priority list.

**Comment by DevilXD** [comment]
Please also check out #23 for another explanation of what the cause of "not mining" may be.
