### ISSUE TITLE
When choosing one game, it gives other games in general

### ISSUE THREAD

**Issue by f1sd** [DevilXD/TwitchDropsMiner#214]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/125303846/5291675d-6990-48f7-9f4f-1e1c46024fa7)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/125303846/2282ff55-8c26-4aa2-8f29-6eb27f10d093)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/125303846/1e1b8c53-b9cd-4180-aba9-aaa20fd21b98)
What should I do?

**Comment by DevilXD** [comment]
Hello o/

Nothing. This is not a bug. Channels and games they're playing, aren't tied to campaigns. Campaigns contain ACL channel lists, which channels are expected to stream the campaign's game, but they're obviously not required to. Nothing stops a campaign from listing a streamer in their ACL, and nothing stops said streamer from streaming a different game. The channel is still going to be tracked, because the entire ACL is always tracked, regardless of what games those channels are playing. Only non-ACL channels could get removed during a channel cleanup, if they happen to play a game that has no associated drops to it. That's about it.

Channels streaming a game that cannot earn any drops won't be selected, and cannot be switched to. You can ignore it's presence on the list. That's it.

**Comment by f1sd** [comment]
Ahhh got it
Why are there no channels that stream New World

**Comment by DevilXD** [comment]
Most likely because of #212. But this already has an open issue, so all you can do is just wait.
