### ISSUE TITLE
Doesn't handle allowed channels

### ISSUE THREAD

**Issue by scryptio** [DevilXD/TwitchDropsMiner#23]
hey there, it looks like the Miner has problems if "Allowed Channels" is not "All". I noticed this because it was mining Paladins (not in Priority) but simply doesn't mine drops which are related to "mizkif" while nothing else could be mined at the time given. Meaning it was idling instead of mining him despite being online.

![image](https://user-images.githubusercontent.com/35927526/174431219-57425751-05bd-4279-9aa7-b5cb42524460.png)

In this case I noticed "Upcoming" in the text despite the drop being active.

I then tried the same for LoL: Wild Rifts to see whether this happens again. As you can see it is in the priority list and currently there are 8 active streams with drops enabled

"No active campaigns to mine drops for. Waiting for an active campaign..." if "Priority only" is enabled

![image](https://user-images.githubusercontent.com/35927526/174431274-09b87922-5711-4771-a91c-ff74aab4b1ba.png)
![image](https://user-images.githubusercontent.com/35927526/174431281-2355a7a2-aac6-4abe-91ea-8de2e72c1118.png)

It is mining paladins instead which is not in the priority list

![image](https://user-images.githubusercontent.com/35927526/174431291-e1635e13-6841-46b5-a1f4-8db3239cf90e.png)

**Comment by DevilXD** [comment]
If a campaign is tagged as "Upcoming", that means its drops aren't active yet. The application will refresh the list of all campaigns it can handle, every about an hour or so. If a campaign becomes active during that time, it's new status won't be reflected in the application until the next reload happens. You can force one to happen immediately by using the "Reload" button located on the Settings tab, or just restarting the application.

Other than that, in `v12`, mousing over the "Ends: ..." part of a campaign, should change the label to "Starts: ...", allowing you to see the campaigns start time in your local timezone. The reload loop will also time itself so that a reload happens right as a campaign becomes active, with a maximum time between reloads still being capped at 1 hour - this just means the time can be shorter sometimes. This should maximize the mining potential, assuming there will be online channels capable of helping the cause.

`v12` is available as source code via the master repo branch - if you'd be interested in getting immediate access to this feature, please follow the `Advanced Usage / Build Instructions` section of the repo description.

**Comment by DevilXD** [comment]
Does this still happen, is is this solved for you?

**Comment by DevilXD** [comment]
Well, since there seems to be no further information on the issue, and I don't see the cause of this, I feel like this can be closed, unless more information would follow later.
