### ISSUE TITLE
Roblox client crashes

### ISSUE THREAD

**Issue by Tsprnay** [DevilXD/TwitchDropsMiner#232]
Why my roblox client crashes when i playing w TwitchDropsMiner ?

**Comment by Padiider** [comment]
first of all thanks because i couldnt figure out why my roblox wouldnt open and that probably happens because of roblox's new anticheat it causes a lot of problems so i guess you'll have to close it when playing roblox until they fix their anticheat

**Comment by DevilXD** [comment]
> Why my roblox client crashes when i playing w TwitchDropsMiner ?

There is nothing in the miner that'd interact with any 3rd party application you may have installed on your PC. The only exception to this may be whatever web browser you have set as the default in your system, and even then, everything related to that is handled by the Python's standard library for opening links - nothing "automatic" from my side.

My best guess is that something else is causing the crashes you're experiencing. The miner is definitely not the culprit here.

> I have VPS and it will be very comfortable to use Twitch drops miner on it.

This project has been created with a graphical interface and user experience in mind, and does not support systems without a display. For more information, please see the project goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals

**Comment by Walter-o** [comment]
I would like to add that it's possible to run the drops miner without a GUI, by using xvfb which is a virtual display.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/33218378/4b395ff2-da5c-44bf-b8f1-d6e2f3d7d403)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/33218378/f619deac-428b-4648-b05e-50497420fb01)
It's kind of hard to set up but i figured i'd post that it's possible for people who want to optimize or have low budget
