### ISSUE TITLE
it wont start watching any livestream no matter what

### ISSUE THREAD

**Issue by Yurkhun** [DevilXD/TwitchDropsMiner#241]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/95500637/d54aa77f-5407-440f-af8b-35a1973e39b5)
I doesn't connect to livestreams even if they have drops enabled, I don't know why but It wont start  watching any livestream at all doesnt matter the game

**Comment by guihkx** [comment]
Version 15 is borked at the moment. You can either use the [development version](https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build), or wait for the [next stable release](https://github.com/DevilXD/TwitchDropsMiner/issues/234).

**Comment by DevilXD** [comment]
Hello o/

First of all, the "DropsEnabled" tag you've circled on the picture, has no meaning anymore. Twitch has changed it's tags system to incorporate "free form" tags, meaning that you seeing the tag, does not prove anything anymore. The most important information for the miner is the one about a particular streamer having the drops enabled in the stream settings. The stream tags used to reflect this setting before, but they don't do so anymore, so whatever tags you may see, are merely a user suggestion, and don't prove anything otherwise.

Second of all, the v15 version you're using is broken due to #138 and #189, so your best bet is to either compile and use the latest master branch version yourself, or use the prebuilt pre-releases from here: https://github.com/DevilXD/TwitchDropsMiner/releases
