### ISSUE TITLE
V15 seems to not work?

### ISSUE THREAD

**Issue by kurichar** [DevilXD/TwitchDropsMiner#245]
Hello, i've been trying to use the V15 and it seems to not load properly the channels and the ones it does display show that they don't have drops (where they actually do have drops on twitch site)
i have now tried using the dev version and it seems to work properly.
![twitchdrop](https://github.com/DevilXD/TwitchDropsMiner/assets/117365558/edecaaca-15f9-4660-97b9-6dffd1035d95)
![twitchdrop1](https://github.com/DevilXD/TwitchDropsMiner/assets/117365558/4d3f9214-36f6-4ae9-a630-2a6ff84d89f1)
![twitchdrop2](https://github.com/DevilXD/TwitchDropsMiner/assets/117365558/13a93055-b07b-4e6a-aa9b-678ee5360684)

this is the dev version:
![twitchdropdev](https://github.com/DevilXD/TwitchDropsMiner/assets/117365558/3ac22de2-5f55-40d3-98e7-be2e286fa2ae)

twitch account is linked and everything is set as it should.

**Comment by DevilXD** [comment]
The current "stable" release build is broken due to #138, #189 and #212. The current development build, which resolves most of these issues, is available as the latest master branch code, accessible also as a pre-release build from the Releases page.

Next stable build awaits #234 to resolve first. Until then, please use the pre-release build instead.
