### ISSUE TITLE
Suggestion: Mode priority Drops.

### ISSUE THREAD

**Issue by Diekion** [DevilXD/TwitchDropsMiner#255]
An interesting option would be to prioritize according to the drop deadline.
Based on the games indicated as preferred, but not in the order of this games, go first for the drop that ends before.
Thanks for app.

**Comment by Diekion** [comment]
<img width="410" alt="Image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/53855614/660b9a39-44e7-4ae0-9387-1f56fdd0d674">

**Comment by DevilXD** [comment]
Hello there o/

There already is a Priority List of games you can specify in the Settings tab, to tell the miner which game drops to mine first, according to your own personal preferences of caring more about one game than the other. Why a mode that specifically ignores this list would be needed?

**Comment by Diekion** [comment]
Ignore the order, not the list. Sorry for my English.
That the order is based on the deadline of the drops.
In this way it is better guaranteed to get the drops when they are for short periods. Some leave with just a few hours to get them in specific direct.
Let's say you first have a game with a drop of one week. Without realizing it, they take out a drop of one hour for a special live in a game that you have below. You're not going to get it because the program is getting the drop from the first game. If you notice, you have to change the order of games by hand to get it. If the program was based on the deadline, it would automatically get the one that has less time without having to wait or change the list by hand.
I hope I have explained myself better. Greetings.

**Comment by DevilXD** [comment]
> they take out a drop of one hour for a special live in a game that you have below. You're not going to get it because the program is getting the drop from the first game.

You are going to get it if the game this happens for is higher on the priority list. And you are not going to get it if it's lower, and there are drops with a higher priority. That's how priorities work: higher priority takes precedence. If you want to get this "short lived" drop, you need to raise the game's priority on the priority list, and the miner will take care of the rest.

This problem is easily solved by just changing the order of games on the priority list, and I still don't see how it'd require an additional mining mode to be added - especially one that'd need to ignore the priority list ordering to work.

**Comment by Diekion** [comment]
It is easy to solve if you realize it in time and change the order, but if you don't realize it, you lose it.
Ok, I see that you are not interested in the idea. Thank you anyway.

**Comment by DevilXD** [comment]
I get the idea, but I don't see the reason for implementing it. Personally, I mostly care about one game, yet it's at the very bottom of my Priority list. The reason for this is this very issue - the game I care about the most, has 28h of drops per week, while other games I care about less, barely have any drops. To avoid the miner being preoccupied to much with my main game, while missing out on "occasional drops" like you've explained, I moved my fav game to the very bottom.

The result of this is the solution to this issue. The occasional drops now have higher priority, so they're mined first, if they appear. Otherwise, my main game is going to get mined instead. Everything gets mined eventually, and I don't miss on anything. Just bump down the Priority on whatever games are preventing you from getting the occasional drops, **and don't change it back (as there's no reason to)** - and the problem is solved.
