### ISSUE TITLE
Feature request: Option to always minimize to tray instead of closing the program

### ISSUE THREAD

**Issue by jordyamc** [DevilXD/TwitchDropsMiner#261]
It would be a very useful QOL feature to add, the "Minimize to Tray" button is too close to the exit button, the users could click the wrong button and because visually both buttons do the same, users may think the program is still running in the background but in reality they closed the program.

You can add an "Always minimize to tray" option and an "Exit app" option to the settings so the users can control the behavior of the program

**Comment by DevilXD** [comment]
Hello o/

I cannot help users fat-fingering wrong buttons. The "Minimize to Tray" button placement is intentional, and this is to discourage accidental closing of the miner via :x:, and instead minimize it to tray where it can still run. I see no point for an additional option that literally does the same thing - just click on the other button. Simple.
