### ISSUE TITLE
"No available channels, waiting for Online channel" (but there IS an active drop campaign and available channels)

### ISSUE THREAD

**Issue by shatteredhalo** [DevilXD/TwitchDropsMiner#267]
Version: v15

I'm seeing an issue where even though I have an active drops campaign in my inventory, the Main tab does not _appear_ to be watching channels and it is saying that it cannot find any to watch:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/50034680/8d4ff362-0483-430b-84f0-22ab5eada128)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/50034680/19a1dc3b-8113-4f56-8973-92e3230aa721)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/50034680/b203e336-d04a-404b-a508-1e5cef299056)

**Comment by DevilXD** [comment]
v15 is broken due to #138, among many other things by now. Even the current in-development version of v16 is further broken by #264. In any case, you're much better off using the development version over v15. You can compile one yourself, or grab an already compiled pre-release version from the releases tab.

**Comment by shatteredhalo** [comment]
Can confirm building v16.dev fixed the issue! Thank you!
