### ISSUE TITLE
Your login attempt was denied by CAPTCHA.

### ISSUE THREAD

**Issue by Zoemmie** [DevilXD/TwitchDropsMiner#27]
Hi, I got this error today:

Please log in to continue.
2022-06-29 21:06:44.936:	  ERROR:	Your login attempt was denied by CAPTCHA.
Please try again in +12 hours.
Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 179, in run
  File "twitch.py", line 788, in check_login
  File "twitch.py", line 724, in _login
exceptions.CaptchaRequired: Captcha is required
Your login attempt was denied by CAPTCHA.
Please try again in +12 hours.
Exiting...

Application Terminated.
Close the window to exit the application.

Is there a way to solve that?

Thanks in advance

**Comment by DevilXD** [comment]
Hello o/

Yes, sort of. You just need to do what the error says:

```
exceptions.CaptchaRequired: Captcha is required
Your login attempt was denied by CAPTCHA.
Please try again in +12 hours.
```
Captcha solving is way out of the scope of this application. The good news is that, as long as you won't mess up the password, the captcha won't show at all, and the login should pass just fine. Otherwise, it takes about 12-24 hours for this "captcha state" to expire, after which you'll be able to login normally again. You just need to wait a bit for this to happen.
