### ISSUE TITLE
How to execute

### ISSUE THREAD

**Issue by urkoperez16** [DevilXD/TwitchDropsMiner#280]
I'm a newbie. I don't understand much about coding. I downloaded the zip file, but I don't know how to follow. If someone can explain me step by step or command by command. I would be very grateful.

**Comment by DevilXD** [comment]
Hello o/

It really depends on what you're trying to do. There's several ways to run the miner:

- Install Python and run it directly from source as a script.
- Use the source code to build a portable one-file executable, and run it from that.
- Download an already-built executable from the Releases page.

All of those end up with a running miner, with their own benefits and drawbacks. Running from source code is generally the best, as there's no overhead added by the executable form (makes things faster), but I'm providing the executable specifically for people who don't know much about installing and using Python to run scripts - you sound like one of those people.

If you want the simplest solution, just download the Development Build from the releases page, and use that: https://github.com/DevilXD/TwitchDropsMiner/releases

Otherwise, this wiki post covers how to install all needed prerequisites, and either run or build the application from source: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running
