### ISSUE TITLE
I can use SOCKS 5 type proxy addresses, but I can't use SOCKS 5 ports

### ISSUE THREAD

**Issue by LegendAdmin** [DevilXD/TwitchDropsMiner#29]
For example, the port number of my SOCKS 5 proxy is 2048, but I can only use HTTP port 2049 in the proxy address to produce results, which results in the proxy address only filling in `socks5://127.0.0.1:2049` or `http://127.0.0.1:2049`, making it impossible for me to tell whether I am using SOCKS 5 or an HTTP type proxy.

**Comment by DevilXD** [comment]
I'm pretty sure that SOCKS 5 proxies are not supported, and can't be supported due to the underlying http requests library not supporting them. Here's a doc explaining the current library capabilities: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support
Whatever you enter on the settings tab, gets passed as that `proxy` parameter per the doc.

If you have the HTTP proxy running on port `2049`, then you should use that port for the application as well: `http://127.0.0.1:2049`. There is a small bug in `v11` that may prevent you from saving the new URL, but you should be able to edit the `settings.json` file in a text editor, to change it. Make sure the application isn't running when doing so.

**Comment by LegendAdmin** [comment]
Thanks for the answer.
