### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by josephisticated** [DevilXD/TwitchDropsMiner#296]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/53388005/f86f8500-7aab-4411-a113-af0a575ecc47)

Even the options are on, it does not automatically.

**Comment by DevilXD** [comment]
Hello o/

The autostart feature puts a path to the executable, at the time it is ticked on. If you then move the folder with the miner somewhere else, the option will remain ticked on, but it'll no longer work since the path points to a non-existing executable now. Unchecking and rechecking the option will refresh the path with the new one.

As an extra consideration for me, I could add some code that will validate the autostart path, if the miner is launched with the option ticked, and then update the option (untick it) if the path doesn't match.

**Comment by DevilXD** [comment]
It's finally time. The https://github.com/DevilXD/TwitchDropsMiner/commit/14a9154366d2651dc2cf75903744553a64319eb3 commit contains a change, that will query the current autostart entry, to figure out if it points to the current executable. If it doesn't, it'll uncheck itself - note that this does not change/overwrite the existing entry, until you try to check/uncheck it yourself. The autostart status is thus now a transitive setting, so it's settings file entry has been removed - existing value in the file will be simply ignored/unused. The querying process has been made "smart" in a way that will perform the check ignoring whatever launch flags might be added to the entry. The only downside now is that the miner will query system registry (on Windows) / query autostart file existence (Linux) on each and every launch, but I consider it a small price to pay for this feature. May or may not lead to overzealous AV engines flagging the miner more, but oh well.
