### ISSUE TITLE
Windows Defender just removed the app 

### ISSUE THREAD

**Issue by siggijarl** [DevilXD/TwitchDropsMiner#308]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/81829230/d66c17a7-2c22-4674-ae17-c63c89e4da1c)

**Comment by guihkx** [comment]
From the README page:

>[Notes about the Windows build:](https://github.com/DevilXD/TwitchDropsMiner#notes-about-the-windows-build)
>- To achieve a portable-executable format, the application is packaged with PyInstaller into an `EXE`. Some non-mainstream antivirus engines might report the packaged executable as a trojan, because PyInstaller has been used by others to package malicious Python code in the past. These reports can be safely ignored. If you absolutely do not trust the executable, you'll have to install Python yourself and run everything from source.

There have been [a lot](https://github.com/DevilXD/TwitchDropsMiner/issues?q=is%3Aissue+%22windows+defender%22+is%3Aclosed) of other reports about this as well.

**Comment by siggijarl** [comment]
Ok, sorry.
Might want to update the documentation then, the built in antivirus in Windows is not exactly non-mainstream.

**Comment by DevilXD** [comment]
The "documentation" (README file) already covers this - just read it more carefully next time. Solving this issue would require packaging everything with something else other than PyInstaller, which is currently not possible due to the lack of time from my side, and general need too. Use a smarter AV engine.
