### ISSUE TITLE
miner Fatal error

### ISSUE THREAD

**Issue by irelandcat** [DevilXD/TwitchDropsMiner#337]
Fatal error encountered:
15:43:24: 
15:43:24: Traceback (most recent call last):
15:43:24:   File "main.py", line 158, in main
15:43:24:   File "twitch.py", line 764, in run
15:43:24:   File "twitch.py", line 817, in _run
15:43:24:   File "inventory.py", line 202, in claim
15:43:24:   File "inventory.py", line 120, in claim
15:43:24:   File "inventory.py", line 136, in _claim
15:43:24:   File "twitch.py", line 1548, in gql_request
15:43:24: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]

**Comment by DevilXD** [comment]
Hello. This is most likely related to #301. Claiming may or may not work properly, as Twitch is in the middle of drops system changes now.

**Comment by Queenhardt** [comment]
( Hey, first I had this error some days ago on the 21.10.23 version, but I think it's resolved now? (I post it so maybe you can tell me what caused it, or maybe help you when it didn't get fixed already, I don't know.): 

07:56:58: Fatal error encountered:
07:56:58: 
07:56:58: Traceback (most recent call last):
07:56:58:   File "main.py", line 158, in main
07:56:58:   File "twitch.py", line 764, in run
07:56:58:   File "twitch.py", line 974, in _run
07:56:58:   File "inventory.py", line 212, in display
07:56:58:   File "gui.py", line 2119, in display_drop
07:56:58:   File "gui.py", line 1114, in update_title
07:56:58:   File "pystray\_base.py", line 150, in title
07:56:58:   File "pystray\_win32.py", line 81, in _update_title
07:56:58:   File "pystray\_win32.py", line 337, in _message
07:56:58: ValueError: string too long (143, maximum length 128)
07:56:58: 
07:56:58: Exiting...
07:57:00: 
07:57:00: Application Terminated.
07:57:00: Close the window to exit the application.

)


But now I have the same issue as the original poster, but the problem is, that it worked properly like an hour ago, but I changed the order of games in the miner and maybe reloaded a little too often, and the error occurred like out of nowhere, that's why I think that my reloading caused it, otherwise it's really bad timing, and I don't know if it would have happened when I didn't do stuff in the miner at the time. I used the -then- latest version that came out on 21.10.23, and it worked fine, but then it had an error so I restarted the miner and after that also my PC. 
This was the error (the time is after the next/third error because I tried the same thing again with the older version to see if it may work and if not, to reproduce the error): 

18:24:34: Please log in to continue.
18:25:19: Enter this code on the Twitch's device activation page: DKTBNTLS
18:26:16: Fatal error encountered:
18:26:16: 
18:26:16: Traceback (most recent call last):
18:26:16:   File "main.py", line 158, in main
18:26:16:   File "twitch.py", line 764, in run
18:26:16:   File "twitch.py", line 817, in _run
18:26:16:   File "inventory.py", line 202, in claim
18:26:16:   File "inventory.py", line 120, in claim
18:26:16:   File "inventory.py", line 136, in _claim
18:26:16:   File "twitch.py", line 1548, in gql_request
18:26:16: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
18:26:16: 
18:26:16: Exiting...
18:26:16: 
18:26:16: Application Terminated.
18:26:16: Close the window to exit the application.


Then I looked up if there was any new version, and so I downloaded the -now- latest version (31.10.23). I unlinked Twitch & the Miner and tried everything from scrap. But I still got a Fatal error, but a little different than the last one: 

18:08:52: Fatal error encountered:
18:08:52: 
18:08:52: Traceback (most recent call last):
18:08:52:   File "main.py", line 158, in main
18:08:52:   File "twitch.py", line 764, in run
18:08:52:   File "twitch.py", line 817, in _run
18:08:52:   File "inventory.py", line 225, in claim
18:08:52:   File "inventory.py", line 131, in claim
18:08:52:   File "inventory.py", line 147, in _claim
18:08:52:   File "twitch.py", line 1548, in gql_request
18:08:52: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
18:08:52: 
18:08:52: Exiting...
18:08:53: 
18:08:53: Application Terminated.
18:08:53: Close the window to exit the application.


Now it doesn't mine at all. After launching the miner and loading all the channels and cache, this error pops out every time.

**Comment by MuffinzCat** [comment]
yeah I don't even have any items show up in my inventory, so I think it might be on twitch's side

**Comment by DevilXD** [comment]
The "service error" GQL error comes from Twitch itself, and indicates a problem on their side, not on the miner's side. There is nothing I can do about it, other than maybe ignoring it, but even then, it'll just keep retrying to claim drops it cannot claim, running into that error over and over again, which I'd like to avoid, so no ignore-logic will be added. Sorry.

If Twitch fixes the issue on their side, this error will go away on it's own - no action is needed, from neither your nor my side, other than waiting.
