### ISSUE TITLE
Can you add a new feature to mine all the priority list?

### ISSUE THREAD

**Issue by MrFutureV** [DevilXD/TwitchDropsMiner#349]
from now what i can see and my understanding,it can only finish mining the top first one then would be second one and etc,can you just make a new feature that allows mining all the ones in priority list at the same time?
![20231102144946](https://github.com/DevilXD/TwitchDropsMiner/assets/46783891/dbc35dd4-dac1-4006-a88b-3b33543a3bfc)
![20231102144858](https://github.com/DevilXD/TwitchDropsMiner/assets/46783891/ce36130f-206f-42de-aa47-8f244c4c71a4)

**Comment by DevilXD** [comment]
Hello.

> can you just make a new feature that allows mining all the ones in priority list at the same time?

I'm not entirely sure what you mean. If you mean mining all drops at the same time, then as @ThisIsCyreX said, Twitch forbids earning drops on more than one channel at a time.

However, if you simply mean that the entirety of the Priority list is considered for mining, then **that's already what happens.** The miner will try to mine the first game from your priority list, but if it can't do so right now, due to for ex. no channels playing said game being available, then it'll try the next game from your list, and so on. There's no "waiting" done to specifically finish the drops from the first game, in order to move to the second one, because that'd make no sense, if the first game cannot be progressed at that time.

If more than one game from the priority list can be mined at a given moment, then the order of those games on the list specifies which one is mined first. If that stops being possible (for ex. channel goes offline), then the miner will automatically move onto the next game from the list, and so on. If no games can currently be mined, it'll switch to an Idle state and wait until there is one that can be progressed.

Additionally, untoggling the "priority only" option will make the miner mine all campaigns possible, even those not specified on the priority list. The priority list still defines which campaigns are considered first, but if none of them are mine-able right now, it'll try to mine other games you have your account linked to, just so it "does something" when it'd normally don't do anything.

Does this explain it, or did you mean something else?

**Comment by MrFutureV** [comment]
> Hello.
> 
> > can you just make a new feature that allows mining all the ones in priority list at the same time?
> 
> I'm not entirely sure what you mean. If you mean mining all drops at the same time, then as @ThisIsCyreX said, Twitch forbids earning drops on more than one channel at a time.
> 
> However, if you simply mean that the entirety of the Priority list is considered for mining, then **that's already what happens.** The miner will try to mine the first game from your priority list, but if it can't do so right now, due to for ex. no channels playing said game being available, then it'll try the next game from your list, and so on. There's no "waiting" done to specifically finish the drops from the first game, in order to move to the second one, because that'd make no sense, if the first game cannot be progressed at that time.
> 
> If more than one game from the priority list can be mined at a given moment, then the order of those games on the list specifies which one is mined first. If that stops being possible (for ex. channel goes offline), then the miner will automatically move onto the next game from the list, and so on. If no games can currently be mined, it'll switch to an Idle state and wait until there is one that can be progressed.
> 
> Additionally, untoggling the "priority only" option will make the miner mine all campaigns possible, even those not specified on the priority list. The priority list still defines which campaigns are considered first, but if none of them are mine-able right now, it'll try to mine other games you have your account linked to, just so it "does something" when it'd normally don't do anything.
> 
> Does this explain it, or did you mean something else?

So "Twitch forbids earning drops on more than one channel at a time",does it mean Twitch forbids earning drops for one specific game on more than one channel at a time or all other dops for all other games mining on different channels at a time?
Because I found that after enabling priority only, I can only mine in order and cannot mine all the games in the priority list at the same time to obtain drops. This is the problem I found.

**Comment by MrFutureV** [comment]
> > does it mean Twitch forbids earning drops for one specific game on more than one channel at a time
> 
> I'm not sure where you've got the "one specific game" from. The statement: "Twitch forbids earning drops on more than one channel at a time" doesn't include the word "game", which means games/campaigns are irrelevant - you cannot earn more drops, or earn them faster, by watching more than a single channel at a time. Watching other channels, while possible (you can just open two tabs for ex.), won't give you progress for more campaigns, nor speed up the campaign you're currently earning.
> 
> > after enabling priority only, I can only mine in order and cannot mine all the games in the priority list at the same time to obtain drops.
> 
> Before enabling the "priority only" option, you still cannot "mine all games at the same time", so I'm not sure why you're even noting it here.
> 
> The "priority only" option works as described in my previous message. Please re-read it if you cannot understand how it works.
> 
> Is it clear now? If not, please ask a more specific question, so I can answer it in a way you'll hopefully understand.
i think i understand it ,twitch does not allow mine for multiple campaigns at the same time,it can only earn one drop at a time，simply just one campaign one channel at a time,so i get it,thanks for figuring out:d

**Comment by DevilXD** [comment]
I see, my bad for missing that then.
