### ISSUE TITLE
Not working since twitch urls changed

### ISSUE THREAD

**Issue by Yeetov** [DevilXD/TwitchDropsMiner#354]
I think the drops url has changed so it doesn't work

**Comment by DevilXD** [comment]
Hello.

"I think" doesn't get us anywhere. "Doesn't work" doesn't get us anywhere either. If you're reporting an issue, please actually state what the issue is. "It doesn't work" isn't a valid way to report an issue - for that, I'll need either a description of what problem you're experiencing, a traceback, output from the application, anything will do.

Before reporting an issue, please make sure you're using the latest version of the miner, which is the `v16.dev.5271d6a` version, available since yesterday. Everything works on my side.
