### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by lyxlucky** [DevilXD/TwitchDropsMiner#355]
os: Centos8
question:version `GLIBC_2.29' not found
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/59909125/edd68a89-3caf-4dc6-b7c9-be5111c2a41a)

**Comment by guihkx** [comment]
Based on a quick Google search, CentOS 8 (which apparently has been [end-of-life since 2021](https://www.centos.org/centos-linux-eol/)), still uses glibc 2.28.

However, as stated [in this section](https://github.com/DevilXD/TwitchDropsMiner#notes-about-the-linux-build) of this project's README page, the binary we build and distribute requires at least glibc 2.31, meaning it's impossible to make it work on such an old distro like CentOS 8.

That being said, you can probably still run the app run [from source](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running#manual-instructions).

**Comment by lyxlucky** [comment]
> Based on a quick Google search, CentOS 8 (which apparently has been [end-of-life since 2021](https://www.centos.org/centos-linux-eol/)), still uses glibc 2.28.
> 
> However, as stated [in this section](https://github.com/DevilXD/TwitchDropsMiner#notes-about-the-linux-build) of this project's README page, the binary we build and distribute requires at least glibc 2.31, meaning it's impossible to make it work on such an old distro like CentOS 8.
> 
> That being said, you can probably still run the app [from source](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running#manual-instructions).

thk
