### ISSUE TITLE
Added the periodic refresh function

### ISSUE THREAD

**Issue by coolingziyu** [DevilXD/TwitchDropsMiner#356]
The feature has been added to enable periodic refreshing of the lost link.  For instance, it allows for the drop list to be refreshed at 4:29 PM in order to accurately receive the drop treasure at 4:30 PM.  Alternatively, you can customize how frequently the treasure is automatically refreshed.

**Comment by DevilXD** [comment]
Hello.

I don't know what this issue is supposed to be. You're saying that a feature has been added, yet this is just a normal issue, not a PR. Your profile has no fork with a relevant commit adding this feature either. Besides, functionality like this already exists, so there's no need to add anything. This is thus an invalid issue.
