### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [DevilXD/TwitchDropsMiner#362]
The miner has been working fine, until I added the following games (by linking accounts) and restarted the application:
- Albion (Wild Blood Week 4 Campaign 5)
- Black Desert (BDO Drops (Nov. 10)
- NARAKA: BLADEPOINT (Weekly Drops 11.5, Partner Special Drops, Astral Cup - Tainted Die)
- Elite Dangerous (Halloween 2023, Elite Partner Program Halloween 2023)
- Kartrider Drift (Season 4 Chainiac Pack)
- Neon Abyss: Infinity (《霓虹深淵：無限》ｘ《Muse Dash》跨界夢幻聯動開啟！)
- DC Dual Force (Rd to Worlds Finest, Pt1 and Pt2)

I'm currently running the latest development build (https://github.com/DevilXD/TwitchDropsMiner/commit/5271d6aa2de4f26082467293ec0046fbd6a32dce)

My priority list is empty and priority only has been disabled.

```
14:05:44: Fatal error encountered:
14:05:44: 
14:05:44: Traceback (most recent call last):
14:05:44:   File "main.py", line 158, in main
14:05:44:   File "twitch.py", line 764, in run
14:05:44:   File "twitch.py", line 916, in _run
14:05:44:   File "twitch.py", line 1719, in get_live_streams
14:05:44: TypeError: 'NoneType' object is not subscriptable
14:05:44: 
14:05:44: Exiting...
14:05:44: 
14:05:44: Application Terminated.
14:05:44: Close the window to exit the application.
```

**Comment by RandomStrangerOnTheInternet** [comment]
Managed to resolve it by doing the following, but I'm a little lazy to create a fork 🥲

```
diff --git a/twitch.py b/twitch.py
index c12903f..8019a39 100644
--- a/twitch.py
+++ b/twitch.py
@@ -1713,13 +1713,18 @@ class Twitch:
                 },
             })
         )
-        if "game" in response["data"]:
+
+        if response is not None and "data" in response and response["data"]["game"] is not None:
+            streams_data = response["data"]["game"].get("streams", {}).get("edges", [])
             return [
                 Channel.from_directory(self, stream_channel_data["node"], drops_enabled=True)
-                for stream_channel_data in response["data"]["game"]["streams"]["edges"]
+                for stream_channel_data in streams_data
             ]
+
         return []

+
+
     async def claim_points(self, channel_id: str | int, claim_id: str) -> None:
         await self.gql_request(
             GQL_OPERATIONS["ClaimCommunityPoints"].with_variables(
```

**Comment by DevilXD** [comment]
Hello.

Thank you for the report. First of all, just adding a bunch of if statements isn't a good solution, without at least some explanation on why that was done in the first place, and why it has happened in the first place as well. Because of that, I'd prefer to figure out the problem myself first - the problem could be caused by something else entirely, like the `slug` generation code, that was the reason behind the existing `if "game" in response["data"]:` statement, that could appear when a game with a malformed or non-existing name would be added to the Priority list. 

Please remove all of the games you've just added, and then add them back one-by-one, pressing on reload after each added game, letting the miner to load back up fully before continuing. Once you encounter the error, take note of the game you've just added, remove it, then restart the application and continue on with the rest of the list. Once you add back all of the games you've listed, minus the games that had caused this issue, please post here the list of said games, and I'll look into it.

**Comment by RandomStrangerOnTheInternet** [comment]
`Neon Abyss: Infinity` seems to be the game that causes this issue, once blacklisted it works fine.

**Comment by DevilXD** [comment]
Just as predicted, the slug generation logic is still at culprit here.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/5f87f1a7-6f42-4bcf-affb-2d1b01efb0ba)

It looks like the `slug` is available as a campaign detail now though, so that should be easy to fix.

**Comment by DevilXD** [comment]
https://github.com/DevilXD/TwitchDropsMiner/commit/5167d95051097ad7f68e6a6cf52842cfc04d562b should resolve the issue. Please try the latest development build.

**Comment by RandomStrangerOnTheInternet** [comment]
Confirmed to be working, thanks!
