### ISSUE TITLE
Game: Temtem has the wrong channel(s)

### ISSUE THREAD

**Issue by GitThisAcc** [DevilXD/TwitchDropsMiner#37]
The Miner shows this:
![image](https://user-images.githubusercontent.com/13767589/188921577-b784abc6-438b-446b-8260-e7778ab16654.png)
Allowed channels: cremagames

But on twitch.tv/drops/campaigns
The Temtem infobox shows this:
![image](https://user-images.githubusercontent.com/13767589/188921989-71b91877-e546-4352-9a1f-567cbd77a2a0.png)
Go to a participating live channel (I guess every channel who streams the game).

The miner won't "mine". I need to open a stream manually.

**Comment by DevilXD** [comment]
Hello o/

That's strange. The campaign itself does appear to have an ACL in place:

![obraz](https://user-images.githubusercontent.com/4180725/188966221-f9f913a2-849c-4d15-92d7-cfb97ef9bdf2.png)

However, as you can see, the `isEnabled` field is `false`, meaning that it doesn't actually apply. There is a condition for this case in the application already, here: https://github.com/DevilXD/TwitchDropsMiner/blob/3cf083d9fe05428d728a99023c0508ac4c13b27e/inventory.py#L223-L226

Note the ACL is only populated if there are any channels on the list, and `allow.get("isEnabled, True)` results in `True`. This specific syntax will read and pass the field's value as-is, but will also treat the missing field condition as equivalent to it being `True`. Since the field exists and is "false", it should result in `False` and the ACL being replaced with an empty list instead, but that's clearly not what is happening.

I'll look into the logic to see what could be causing the discrepancy here.

**Comment by DevilXD** [comment]
I've investigated the issue, and it appears to work just fine:
![obraz](https://user-images.githubusercontent.com/4180725/189041118-9414e34b-fa85-44ac-b201-a31e3927a533.png)
What could have happened, is that - the game developer initially added the `cremagames` channel as the ACL, which enabled it, but then later decided to disable the list. Because this disabling change isn't communicated to the application, this state you've encountered would've lasted one hour at most, at which point the maintenance task would reload all campaigns and pick up on the change.

@ThisIsCyreX Please confirm that the application is showing this campaign correctly to you now.
