### ISSUE TITLE
Could you add or send the file for translation.

### ISSUE THREAD

**Issue by Kjerne** [DevilXD/TwitchDropsMiner#390]
Hey there would love to translate the app to Danish.

**Comment by DevilXD** [comment]
Hello there o/

Very well. There's a couple ways to go about it, but generally there's nothing preventing you from doing so already. It all depends on how tech-savvy you are with being able to run this project from source, in order to be able to test your translation efficiently. Otherwise, you can just do a blind translation, where I can send you the current template file, and you can send back the translation.

Here's some instructions on running the project from source: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running  Once you do so, it should generate an `English.json` translation file in the `lang` folder. Then it's just a matter of making a copy of it, giving the new copy a relevant name, then opening it and performing the translation. You can then launch the application from source and simply select your new language to test the translation. Once done, you can PR it to this project if you know how, or simply upload it here or anywhere else, and I'll introduce it into the project under your name.
