### ISSUE TITLE
Compiling on ARM

### ISSUE THREAD

**Issue by Alixey** [DevilXD/TwitchDropsMiner#397]
I am trying to compile the project from source on a Raspberry with ARM architecture, but I can't seem to succeed it. How could I do this?

**Comment by DevilXD** [comment]
Hello.

Why not just run it from source? Compiled version on ARM is not provided nor supported at this time.

**Comment by bmbeverst** [comment]
You can see some work other users have put in to get it working on Raspberry Pi here #221

**Comment by grain12** [comment]
is it realistic to make it for android?

**Comment by DevilXD** [comment]
@grain12 Any platform that can run Python and has a display should do. Android fits that definition, but I'm not sure how tkinter would work on Android - my best guess is that all you'd get is a "it's not supported" message. Otherwise, you should already be able to run it there.

As far as any official support for it goes, the answer is "probably no", as this project uses the unofficial "raw" Twitch API, that constantly changes and thus constantly breaks, making this project pretty "volatile". If it'd ever become too much for me to maintain, for example if Twitch decides to do some very drastic changes, I'd probably just declare it dead. That almost happened recently, with the drops system redesign Twitch recently did (see #301), but the changes seemed to be simple enough to work around for the time being, with proper fix and redesign coming in the future (hopefully, see #220 and #234).
