### ISSUE TITLE
"No active campaigns to mine drops for. Waiting for an active campaign..."

### ISSUE THREAD

**Issue by DealsBeam** [DevilXD/TwitchDropsMiner#398]
I logged in, it scanned the campaigns but it says "No active campaigns to mine drops for. Waiting for an active campaign..." and it's just earning points

I have my accounts linked for the campaigns that are active

I'm using the dev build on Windows https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build

Any assistance?

**Comment by DevilXD** [comment]
Hello.

Please use the Inventory tab of the miner to find the relevant campaign you're trying to mine. You may need to fiddle around the filters - to show all campaigns, simply check all of the options and hit Refresh. Once you find the campaign, take a picture/screenshot of it and post here.

Alternatively, ensure that the campaign you're trying to mine:

- Is active, so it already started and hasn't finished yet
- The drop within the campaign hasn't expired  
- Your account is linked to the campaign's game  
- There is at least one channel which can be watched to progress the campaign

**Comment by DealsBeam** [comment]
https://i.imgur.com/NimMfTb.png

**Comment by DevilXD** [comment]
Everything seems to be in order. Make sure you have setup your Priority list properly - you can find it in the Settings tab. Use it to setup a list of games you'd like to mine, then hit the Reload button and it should work.

**Comment by DealsBeam** [comment]
Thank you, I didn't even know you needed to add the games through the priority list.

**Comment by DevilXD** [comment]
> It would be great if the application just began mining the games that you have already linked.

You can do that by simply unticking the "Priority only" option. It's ticked by default specifically because I didn't want the miner to start mining seemingly random games/campaigns for a reason yet unknown for the user. Unticking this option though, is mentioned on the Help tab, in the usage instructional.

> I think games which don't have linked are default not priority for people mining.

Games that aren't linked, aren't mined at all. This is because mining unlinked games leads to abuse. You can read more about this in the project goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals

**Comment by biast12** [comment]
ngl the "Priority only" option should really not be ticked at default, it only made confusion for me and i started and is making confusion for others too

**Comment by DevilXD** [comment]
The only confusion I can see here, is the "no campaigns" message not being specific enough. If it said something like "none of the selected campaigns are able to be mined" (which is what it truly means), then the first thing you'd wonder as a new user, is how to select them in the first place. The current message is a result of continuous changes and development - it may have made sense at some point, but now it'd be good to change it.

I won't be making the "priority only" option unticked by default, because I don't want it to mine anything right after opening the application. The user should be able to first select what they're interested in, and *then* mine only what they want. Furthermore, the setup of Priority list is already explained in the Help tab, so I'll leave it at that.

**Comment by biast12** [comment]
I can see what you mean, it's just still really confusing as a new user to have it not just work when you start it up, even if you change the print

Would having a startup message box of some sort (one that only would show first time you open the app) maybe help with both making it more user-friendly and also allowing the user to select what games they're interested in before it starts, kinda like a popup window or a setup guide with the settings first time you open the app

**Comment by Techwolf** [comment]
Its been a while, but way back when I started using this. I too was trying to figure out why it was not working. Turns out the "Priority" list is not a "Priority" list, but a match these campaigns to watch list. Not reordering a matching list or downloaded matching linked games list from the server.

**Comment by Yeetov** [comment]
No active campaigns to mine drops for. Waiting for an active campaign...

Got this error, says that Overwatch 2 isn't ljnked when it is, I have reloaded the miner and everything and it still says no active campaigns.

**Comment by Yeetov** [comment]
> No active campaigns to mine drops for. Waiting for an active campaign...
> 
> Got this error, says that Overwatch 2 isn't ljnked when it is, I have reloaded the miner and everything and it still says no active campaigns.

Found a fix, sorry: #430

**Comment by DevilXD** [comment]
I think this issue can be closed now.
