### ISSUE TITLE
[Suggestion] Startup with windows option

### ISSUE THREAD

**Issue by maclanegamer** [DevilXD/TwitchDropsMiner#4]
I might have a brain delay when suggesting things, sorry for that, I wish I could suggest everything at once, I can't really help it 😂
How about a startup with windows option? Would be handy.

**Comment by DevilXD** [comment]
Hmm, this again calls for some kind of a configuration file being saved (startup or not, startup normally, minimized or to tray). I think I'm not ready for this one yet. Also, keep in mind that the application will select the very first game from the inventory to mine - if you have just one, it's not really a problem. With two tho, you'd need to bring up the app window after startup anyway, to make sure the "correct" game got selected. There is an argument option that can pre-select a game, but I'm not sure exactly how it'd need to be incorporated into autostart in order to work.

So, this is a soft "no" for now. But you can easily setup autostart for it yourself, by following this guide: https://www.howtogeek.com/208224/how-to-add-programs-files-and-folders-to-system-startup-in-windows-8.1/

The game selection argument is `-g` or `--game`, and it's a case-sensitive game name that should end up getting selected the first time the games list is populated. Arguments can be added into the shortcut after the executable path, with enclosing double-quotes if the argument contains spaces. Something like this:
```
".../Twitch Drops Miner (by DevilXD).exe" -g Paladins
```
or
```
".../Twitch Drops Miner (by DevilXD).exe" --game "Game with Spaces"
```

I'll probably add some kind of argument(s) to startup minimized or in tray in the next release, so you'll easily be able to add that to the startup shortcut.

I'll also keep this issue open until I'll be ready to implement some kind of configuration into the application. Could be next release, could be one of the later ones, I'm not sure yet. For now, there isn't much need for actual app configuration, so I'm postponing it.

**Comment by DevilXD** [comment]
This is now available in `v11`: https://github.com/DevilXD/TwitchDropsMiner/releases
