### ISSUE TITLE
Didn't claim/receive drop for overwatch

### ISSUE THREAD

**Issue by TomerGamerTV** [DevilXD/TwitchDropsMiner#401]
I saw the program mining hours and it should have finished watching it but after checking the inventory it didn't claim anything

Also the refresh button doesn't work in the inventory

**Comment by DevilXD** [comment]
Hello o/

The "Refresh" button in the inventory may not do what you think it does. It refreshes the current Inventory display. This is only useful if you've just changed any of the filtering options available right next to the button - otherwise it doesn't really do anything. The view is also automatically refreshed every time the user changes the tab to the Inventory one. To actually refresh the whole inventory and make it up to date with it's factual state, you need to reload the entire application via the Reload button available in the Settings tab. This is done automatically every hour, to keep everything updated as much as possible.

If your mining progress is inaccurate and the miner isn't claiming the drops, you're most likely running into #301. Since that's an ongoing issue, this makes this one a duplicate.
