### ISSUE TITLE
[Feature request] Drops mining order

### ISSUE THREAD

**Issue by Vadson159** [DevilXD/TwitchDropsMiner#406]
Is it possible to make miner farm drops in the order of campaigns ending time? So user didn't had to make a priority list based on ending time to farm all possible loot.

**Comment by DevilXD** [comment]
Hello o/

An interesting idea, but I don't see what that would be needed for. This isn't a "set and forget" miner. If you know about a campaign that's short, and would rather get the drops from it than a different campaign, game of which is higher on the priority list - just reorder the priority list beforehand, so that it will be mined first. All it needs is to be given sufficient priority via the already existing priority list. In most cases, you can even leave your reordered list as-is, and it should still work out for you as you'd want to later on. In my case, for example, my main, favorite game, is pretty much on the very last spot in my priority list, because there's 4 other games, which have shorter, but irregular campaigns. This makes it so that when they appear, they'll be mined first, before the miner "falls back" to the long and regular campaign my main game is usually having. No reordering back-n-forth required.

This was already extensively covered by me in #330, so I'd recommend checking it out for more explanation.
