### ISSUE TITLE
Stream AFK Only

### ISSUE THREAD

**Issue by Heyo7726** [DevilXD/TwitchDropsMiner#408]
Short explanation: if someone could make a python script to afk in a livestream simply just staying there and not doing nothing.

**Comment by DevilXD** [comment]
Hello.

I don't know what this issue is supposed to be. Are you asking for a new feature to be added? This is a drop-focused application, and not being able to "AFK in a livestream" is there by design - because that isn't needed, if you're not getting any drops.

If you're looking for a way to just watch whatever livestream you'd like to, there are other projects out there that can do that for you, like this one: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

This miner won't be adding such a feature anytime soon.

**Comment by Heyo7726** [comment]
The porpuse was z bot that counts how many time you watch the stream. The link above worked, thank you.
