### ISSUE TITLE
Multiaccounts

### ISSUE THREAD

**Issue by Killer99Man** [DevilXD/TwitchDropsMiner#412]
What is the maximum number of accounts that can be connected to the program at the same time?
i'm using this https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build (for windows)
I see a maximum of 8 accounts, but after connecting the first one, I can’t even connect the second one, because the login button is not active..

**Comment by DevilXD** [comment]
Hello o/

I think you're not understanding it. The websocket connection is responsible for keeping track of accurate status of Twitch channels, not for multiaccount support. The application can only handle one account at a time.

The websocket connection has to be sharded (split into multiple ones), because of the limits imposed by the Twitch API. Each shard can subscribe up to 50 websocket topics, and one can create up to 10 connections per client, giving you a 500 total topics pool to utilize. For account safety reasons, the application makes up to 8 connections, leaving the remaining 2 for simultaneous browser usage.

https://dev.twitch.tv/docs/pubsub/#api-limits

Actual multiaccount support is tracked via #31.

Is there anything more you'd need help with?

**Comment by Suz1e** [comment]
Are you using a VPN? It is recommended to try changing VPN

**Comment by DevilXD** [comment]
I'm assuming this is solved by now.
