### ISSUE TITLE
Question regarding multi-account usage

### ISSUE THREAD

**Issue by Top3-GitHub** [DevilXD/TwitchDropsMiner#414]
Hi, can i mine on many accounts in one time?

**Comment by DevilXD** [comment]
Hello o/

The miner itself as an application, supports only a single account at a time. Furthermore, Twitch has internal mechanisms that may detect a single IP address managing multiple Twitch accounts at the same time, and act accordingly - limiting the lifespan of this project (no actual account bans were ever given out to my knowledge). Doing this on 2 or 3 accounts shouldn't be too big of a deal, but anything more is considered abuse. Also, I don't really support multi-account usage, so you need to figure everything out on your own.

Regardless, all that's needed to run separate instances, is just having separate folders with a miner copy in each.

**Comment by ErrorCode313** [comment]
Could you implement the ability to use a proxy to mine, thus bypassing Twitch's IP detection mechanisms?

**Comment by Luckz** [comment]
> Could you implement the ability to use a proxy to mine, thus bypassing Twitch's IP detection mechanisms?

Considering idling unlinked games was rejected citing potential abuse: using proxies to idle points at a far clearer case of abuse.

**Comment by DevilXD** [comment]
Proxy usage is already supported, although only a basic HTTP one. Everything else in my previous comment here still stands though.

**Comment by DevilXD** [comment]
Since the question has been answered, I guess this can be closed. For future reference for anyone reading this, multi-account usage has it's own tracking issue as well: #31.

**Comment by dragongrafdiscord** [comment]
> Hello o/
> 
> The miner itself as an application, supports only a single account at a time. Furthermore, Twitch has internal mechanisms that may detect a single IP address managing multiple Twitch accounts at the same time, and act accordingly - limiting the lifespan of this project (no actual account bans were ever given out to my knowledge). Doing this on 2 or 3 accounts shouldn't be too big of a deal, but anything more is considered abuse. Also, I don't really support multi-account usage, so you need to figure everything out on your own.
> 
> Regardless, all that's needed to run separate instances, is just having separate folders with a miner copy in each.

oh hi at least 1 (cant remember if it was 2) of my accounts got banned for botting just fyi lost a like 10 year twitch account xD
*just checked my emails and yeah it was 2 one for botting and then my main bc of using the account while other one was already banned* 
![image](https://github.com/user-attachments/assets/9cd83f24-6b92-4ac7-94fb-74c4b5fb2262)
if somebody needs translation here:
"Hello ,


Twitch wants our community to be safe for everyone. That's why, among other things, we require all users to ensure that everything shared on their account complies with Twitch's Terms of Service and Community Guidelines, and based on a review of your activity or content, we have issued a warning to your account for violating the Community Guidelines. Due to the severity of the violation or the fact that you have committed multiple violations, your access to Twitch services has been suspended indefinitely.

Reason
Bypassing an account suspension

Using another account to circumvent a site-wide ban.

Examples of a policy violation include, but are not limited to
Streaming or chatting on an alternate account while a ban is in effect.
Joining another streamer's stream as a guest during a ban in effect.
Creating an alternate account during a ban in effect."

**Comment by DevilXD** [comment]
First of all, the reason for the ban is clearly stated as "Bypassing an account suspension" and "Using another account to circumvent a site-wide ban." You can only get this if you're banned from Twitch already, and then create another account. It has nothing to do with the Miner.

Second of all, this issue is already closed. If you want to provide some additional information, either use an existing issue, or make a new one. This email from Twitch isn't even worth mentioning, because the miner is clearly not the cause for the ban.
