### ISSUE TITLE
Completing one campaign completes both for the same game

### ISSUE THREAD

**Issue by mgbeck002** [DevilXD/TwitchDropsMiner#418]
I've been experiencing this with Out of the Park Baseball. They typically have an official and an affiliate campaign each day, as shown in the screenshot below.
<img width="725" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/7800296/fa2876ac-7188-415a-96c4-288bb9c30058">

So far today, only affiliates have streamed and I should still have the "Official" campaign available to me, but it's marked as completed in the application and the application will no longer join the official channel.

Inventory screenshot:
<img width="772" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/7800296/5152ddf7-d5f8-4fc8-a0e4-ca172f5c1f86">

This is with commit 91f2dacbcce14d3dbc7519bcbff61d1da5ebcb00 on Windows 11, running both as a built executable and when run as a python application directly.

**Comment by DevilXD** [comment]
Hello o/

I've roughly explained "the issue" of trying to determine if a campaign has been finished or not, here: https://github.com/DevilXD/TwitchDropsMiner/issues/334#issuecomment-1779920333

There is no fix for this, the logic works correctly. The developer of this campaign has used repeating benefits, which can "cross-claim" a campaign in the miner like that. It works like this:

- You mine a campaign which has a drop with a repeating benefit X.
- There's another campaign active at the same time, with all drops that have the same benefit to it.
- The logic processes the second campaign and determines that all drops from it have already been claimed (from the first campaign), because all benefits from it were claimed while the campaign was active.
- The result is a not-started-yet campaign being all marked as claimed and finished.

That's the bad news. The good news is that - you can force a campaign like that to appear in your inventory, by watching an applicable channel for at least one minute. Once it does so, and all drops receive a 0% progression bar, the miner will automatically pick up on that, and should continue from there - after a reload, of course. Every further campaign that runs into this issue, has to be started "manually" like this.

Please let me know if that worked out for you.

**Comment by AlKebrit** [comment]
if restarting the app fixes the problem
just use a script or something to auto kill and run the app every hour or so your problem will be fixed

**Comment by DevilXD** [comment]
Restarting the app won't fix the problem here, only manually starting a campaign will. This is an issue with how Twitch handles campaigns state, and my workaround around it works in pretty much all cases, *except* the one where you'll end up with a benefit being claimed in a campaign while another campaign was active, *and* all it has is that particular benefit only.

**Comment by AlKebrit** [comment]
it does fix my problem with rust
it keeps watching a streamer even if I claimed all his drops but once restarted it switch to a streamer that has a drop I haven't claimed.
also, it keeps switching from one campaign to another after completing a single drop of 4 drops in that campaign. it goes back to the campaign it skipped earlier when restarted

at first, I kept killing the app and running it manually but after a while. then I set it up to auto-close and open every hour. I haven't had any problems since then

**Comment by AlKebrit** [comment]
maybe you are right about it reloading but I don't know maybe cause I didn't wait for an hour to see if it functions  just like if I restarted it myself and it fixes everything without me doing anything I don't really know

**Comment by AlKebrit** [comment]
all I can say is that your app is amazing it saved me a ton of time and headache of watching streams and making sure those streams were working in the background i had bad internet I couldn't watch and play at the same time without having ping spikes and packet loss so thank you very very much

**Comment by DevilXD** [comment]
> the app keeps watching a streamer even if I claimed all his drops but once restarted it switch to a streamer that has a drop I haven't claimed.

That's an entirely different issue, tracked by #301. This issue isn't part of it. Restarting won't help here, as I said.

> maybe you are right about it reloading

I literally wrote the entire app myself, so I'm pretty sure I know how it works. Automatic reloads happen every hour on their own, there's no need to restart anything.

**Comment by AlKebrit** [comment]
> That's an entirely different issue, tracked by #301. This issue isn't part of it. Restarting won't help here, as I said.

yeah but the issue I have is for example, streamer hjune has drop hjune SAR it will watch that streamer until drop SAR is claimed then it will keep watching hjune and start progressing in another drop hjune doesn't have. it gets stuck for a while until I reopen it.

**Comment by DevilXD** [comment]
This issue is getting quite a bit of offtopic discussion, so I'll make it clear - please either respond under the relevant issue, or open a new one.

> it will keep watching hjune and start progressing in another drop hjune doesn't have

Again, that's the symptoms of #301.

> it gets stuck for a while until I reopen it.

Pressing the Reload button that can be found on the Settings tab, should also make it "unstuck". If that's so, the built-in maintenance task will automatically reload the miner for you every hour, and as I already said, there's no need for any kind of auto-restart here. If it doesn't get unstuck after pressing the Reload button, then please open another issue and describe your case.

> the other issue I had was completing one drop skips the whole campaign and switch to another campaign this is fixed for me by simply restarting the app

This is a new one to me. Campaign cannot simply be "skipped" like that. Please open a new issue and describe you case.

In any way, unless you have something specific to contribute to this exact issue, I'd like you to direct this discussion to either an existing, or a new issue.

**Comment by AlKebrit** [comment]
sorry man. i deleted my comments

**Comment by DevilXD** [comment]
> Thanks. Yeah. That workaround seems to work.

Cool =)

> For my curiosity, what part of the code is the part that claims the drops?

The exact code that performs the claim operation is here: https://github.com/DevilXD/TwitchDropsMiner/blob/b655803bf5270f0b58ec5fa3d0270e6a2049b841/inventory.py#L146-L170

But to authorize the claim, you need to have an authorization key (a string of characters obtained back from the login procedure, that authorizes each request to the Twitch servers the miner makes), and a claim ID, that's generated by Twitch once the drop progress reaches 100%.

**Comment by DevilXD** [comment]
Okay, well, there isn't much I can do here. There's no other way to determine if a campaign is finished or not, than by cross-comparing already mined drops with active campaign times, and the workaround can be used to manually "prime" the campaign for mining. I'm not sure if this is a NoFix or Solved as pretending I've answered a question, but since the "issue" is still there and it won't be worked on, I'm calling this a NoFix bug, that we just need to live with.

If a better campaign completion detection method would come up in the future, I'll be very happy to use it to avoid this issue. For now, it just has to stay as is.
