### ISSUE TITLE
Every single dev branch since November 2023 (efe601a) get detected and auto deleted by Windows Security

### ISSUE THREAD

**Issue by Fr0stPh03niX** [DevilXD/TwitchDropsMiner#420]
I have noticed from the last 2-3 months that every single build from the dev branch gets flagged as a dangerous file. It starts from the Chrome downloads and even after brute force downloading it from the browser, it will most definitely get flagged by Windows Security at some random time (most likely when am away from the PC or left the Miner unattended).

Even if I exclude the application in Windows Security exclusion, it still somehow ends up deleting it at random times. This doesn't used to happen as prevalent like now since the given build number. And this is why I am still running the older dev builds despite me wanting to try the latest ones. Any solutions to this?

**Comment by DevilXD** [comment]
Hello o/

Build version doesn't really matter, it's the AV signatures being updated that changes the detection status instead.

> Any solutions to this?

Yes - use a better / smarter antivirus engine. ESET, Kaspersky, BitDefender, AVG, etc. Otherwise, you'll have to keep dealing with Windows Security being too stupid to understand what a packaged Python interpreter executable is, and how to deal with it. If the ignore/exclusion list isn't enough, then I can't really help you. "Fixing" this would require switching the entire project to use a different packaging method, other than PyInstaller. If you'd still have no luck, you can always run the whole application from source, or build an executable yourself - some instructions for that can be found here: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

This is also a duplicate of #384, #335, #333, #315, #284, #270, #249, #217, #209 and #13. Another one to the collection :+1:
