### ISSUE TITLE
[Feature Request] Low Performance/Bandwidth Options

### ISSUE THREAD

**Issue by iXerxes** [DevilXD/TwitchDropsMiner#424]
Hi.

I use both the Windows and the Linux (Ubuntu Server) version of the miner. Both of which have some minor performance issues; maybe it's also just because I have a toaster.

- On Windows, moving/resizing the window and scrolling can be a little laggy.
- On Linux, it's the same. For me personally, however, I run it on Ubuntu Server without a GUI. Which means I also use [Xpra](https://xpra.org/index.html) to host a server for the GUI and then it can be accessed via web browser.

I appreciate that this tool has only one job, and you're careful not to creep outside of that just to serve everyone's interests/needs. But if possible, I would love it if there was an option to either disable images entirely; or use images in a lower resolution. I'm not sure if maybe there's an option to download it from Twitch in a lower resolution, or if you'd have to downscale them yourself.

Appreciate your work and effort in this tool,
Thanks :)

**Comment by DevilXD** [comment]
Hello o/

> On Windows, moving/resizing the window and scrolling can be a little laggy.  
> On Linux, it's the same.

There's nothing I can do about that. The library used for the GUI (TkInter) is pretty basic and quite old: I'm talking like, 1997 for Tk/Tcl 8.0 initial release, and Tk/Tcl 8.0.5 patch in 1999. This is around Windows 95 era. A rewrite utilizing PyQt (much more modern library) was planned, but it'd require redoing the entire GUI logic, and there are more pressing matters than that, so I'm putting it away for now. It may be something to think about for #220, but that's about it.

> I run it on Ubuntu Server without a GUI. Which means I also use [Xpra](https://xpra.org/index.html) to host a server for the GUI and then it can be accessed via web browser.  
> I would love it if there was an option to either disable images entirely; or use images in a lower resolution. I'm not sure if maybe there's an option to download it from Twitch in a lower resolution, or if you'd have to downscale them yourself.  
> you're careful not to creep outside of that just to serve everyone's interests/needs.

Yes indeed, and that's because people (like you) are trying to use this project as something it was never designed for. This isn't a miner you can run on a server - period. I don't support it. An actual display is required to use it. There's no such thing as "running on Linux without a GUI". I won't be adding anything that'll "turn off" parts of the GUI, because it's an integral part of the application, and it was *specifically designed* to have those images in place there, among other information and things.

If you're looking for something you can run on an actual server, there are other, more suited projects for this purpose, like this one: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

If you'd like to learn more about why such design decisions had to be put in place, I recommend checking out the Project Goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals
