### ISSUE TITLE
Black Desert Unlinked Account

### ISSUE THREAD

**Issue by ZethosZ** [DevilXD/TwitchDropsMiner#429]
When using a Black Desert account made using steam, twitch uses the steam account of the user for drops as opposed to a separate account. Is it possible for the tool to allow for drops to be collected if a steam account is linked for this game?

**Comment by DevilXD** [comment]
Hello o/

> twitch uses the steam account of the user for drops as opposed to a separate account.

I'm not familiar with this. How exactly does this work? Are you able to view the progress of drops earned that way on the https://www.twitch.tv/drops/inventory page?

**Comment by ZethosZ** [comment]
I am able to earn progress, however I can not claim it and it prompts me to connect my account. The video i watched on how to enable drops for the steam version must be incorrect/outdated as other sources claim that it is not possible to get drops with the steam version.

**Comment by DevilXD** [comment]
Yeah, it sounds like something outdated. Twitch drops used to be an auxiliary construct of game developers, that was based on chat presence during a stream. But ever since the official drops system was introduced, everything was moved to the Twitch's internal systems instead. Now, all you need to do is link your Twitch account to the game account, and you should be able to earn and claim whatever drops you may be interested in.
