### ISSUE TITLE
TDM showing no campaigns to farm possibly due to accounts "Not Linked"?

### ISSUE THREAD

**Issue by Majaura** [DevilXD/TwitchDropsMiner#430]
TDM showing no campaigns possibly due to accounts "Not Linked"?

I'm using the latest dev build. I've been having this issue for a long time. 
I've been having this issue for months as well!
https://i.imgur.com/ISuSv0F.png here's the screen of it telling me my accounts aren't linked, even though they are. Thanks for reading!

**Comment by DevilXD** [comment]
Hello o/

Yes, your Twitch account has to be linked to a game campaign of choice, for the miner to consider it a valid mining target.

> it telling me my accounts aren't linked, even though they are.

Well, apparently they aren't then, because the linked status is taken directly from the Twitch website. Specifically, once you go to https://www.twitch.tv/drops/campaigns and find the game and campaign in question, you should find your account connection status there as well: 

![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/632f0000-66e6-4ee3-9536-6b3007a64dc6)

If your account isn't linked properly, you'll see a "Connect" button there instead:

![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/99178353-8ffa-49ba-8863-3a954f87df13)

All you need to do to resolve this issue, is make sure it actually says "Connected" there like on the first picture, instead of the "Connect" button being there, by clicking on the button and following the linking process. If that doesn't work, please perform a clean reconnect - instructions for that can be found here: https://github.com/DevilXD/TwitchDropsMiner/issues/309#issuecomment-1749628379

**Comment by Majaura** [comment]
Omg you're absolutely right. The fresh reconnect is what's needed. There is honestly ZERO way to know that's what you have to do, so thanks so so much! You're the man, Devil. If you ever have people with this issue, I'm willing to bet they need the fresh reconnect a lot of the times.

**Comment by JonJaded** [comment]
Hey there, I have a question regarding this. I'd like to farm helldivers 2 drops, but the way their system is, you need to watch the streamer, claim the drop and only after can you then "link your account" to get an ingame redeemable code. It's impossible to redeem prior because they don't have an account system, its more of a code dispensary.

With all that said, is it possible to ignore non linked for to farm drops for this game? @DevilXD

**Comment by EffortlessFury** [comment]
I think the new Helldivers 2 campaign doesn't allow you to link until you've earned a drop. Lovely. lol

**Comment by JourneyOver** [comment]
> I think the new Helldivers 2 campaign doesn't allow you to link until you've earned a drop. Lovely. lol

it doesn't even link after you have earned your drop either from what I can tell.. After getting the drop, and going to claim it; it still doesn't allow me to actually link the account on twitchs side of things.
