### ISSUE TITLE
MinerException: GQL error: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]

### ISSUE THREAD

**Issue by woctezuma** [DevilXD/TwitchDropsMiner#435]
Starting today, I have encountered a fatal error.

```
23:07:30: Fatal error encountered:
23:07:30: 
23:07:30: Traceback (most recent call last):
23:07:30:   File "C:\TwitchDropsMiner\main.py", line 158, in main
23:07:30:     await client.run()
23:07:30:   File "C:\TwitchDropsMiner\twitch.py", line 764, in run
23:07:30:     await self._run()
23:07:30:   File "C:\TwitchDropsMiner\twitch.py", line 908, in _run
23:07:30:     await asyncio.gather(
23:07:30:   File "C:\TwitchDropsMiner\channel.py", line 277, in update_stream
23:07:30:     self._stream = await self.get_stream()
23:07:30:                    ^^^^^^^^^^^^^^^^^^^^^^^
23:07:30:   File "C:\TwitchDropsMiner\channel.py", line 259, in get_stream
23:07:30:     available_drops: JsonType = await self._twitch.gql_request(
23:07:30:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:07:30:   File "C:\TwitchDropsMiner\twitch.py", line 1566, in gql_request
23:07:30:     raise MinerException(f"GQL error: {response_json['errors']}")
23:07:30: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
23:07:30: Exiting...
23:07:30: Cannot connect to Twitch, retrying in 2 seconds...
23:07:30: Application Terminated.
23:07:30: Close the window to exit the application.
23:07:39: Cannot connect to Twitch, retrying in 2 seconds...
23:07:40: Cannot connect to Twitch, retrying in 2 seconds...
23:07:41: Cannot connect to Twitch, retrying in 2 seconds...
```

Maybe related:
- #383
- #370

**Comment by jaredkotoff** [comment]
I've been getting this too for about 3 days now. 
Im assuming that there's nothing can be done though based on other similar issues

**Comment by DevilXD** [comment]
Correct, there isn't anything that can be done on your side, as "service error" is just the Twitch website crashing and generally having internal issues. On my side, handling this in a better way is tracked by #417.

I feel there's a need to create a better logging system, because this issue is caused by a single channel, and there might be something specific about it that's causing the crash, just like what happened with the drop claiming time limit: https://github.com/DevilXD/TwitchDropsMiner/issues/347#issuecomment-1837151831

**Comment by woctezuma** [comment]
Thank you for your replies! My client works again, as Twitch's side has been fixed, I guess.

**Comment by zelda0079** [comment]
Not working today

**Comment by DevilXD** [comment]
Try it with this latest commit: https://github.com/DevilXD/TwitchDropsMiner/commit/a536dde677c7b8e61ad235efa7a41d1f415d0c8b

**Comment by jaredkotoff** [comment]
> Try it with this latest commit: [a536dde](https://github.com/DevilXD/TwitchDropsMiner/commit/a536dde677c7b8e61ad235efa7a41d1f415d0c8b)

Doesn't seem to work. The error for this `viewerDropCampaigns` service error is being thrown here: https://github.com/DevilXD/TwitchDropsMiner/blob/master/twitch.py#L1570

**Comment by woctezuma** [comment]
> Try it with this latest commit: [a536dde](https://github.com/DevilXD/TwitchDropsMiner/commit/a536dde677c7b8e61ad235efa7a41d1f415d0c8b)

I still encounter the error despite this commit.

**Comment by DevilXD** [comment]
> I still encounter the error despite this commit.

@woctezuma The commit was never supposed to resolve any issues, only add context information. This isn't a fix by any means.

> Doesn't seem to work.

@jaredkotoff That's my bad. The exception handler was added in the place where a "service error" did occur in the past, but it was actually a couple lines lower that was crashing in your case. This place can actually salvage the crash, because the stream information exists already, and just the "drops_enabled" flag is updated when necessary. Please try this latest one: https://github.com/DevilXD/TwitchDropsMiner/commit/5dea41a6abdbb8702d995d792ec895ece6b667a6
