### ISSUE TITLE
Change the Window Title to twitch account login

### ISSUE THREAD

**Issue by auuruum** [DevilXD/TwitchDropsMiner#449]
Example Twitch Drops Miner v{__version__} ({twitch_login}) (by DevilXD))

or add imput field to settings tab to set window title

**Comment by DevilXD** [comment]
Hello o/

I'm assuming this is an Enhancement proposition. While I get why something like this would be cool to have, there's several things that say otherwise:

- "Twitch login" isn't stored anywhere. The login flow saves an authentication token that is then used for all requests the app makes, and the only thing used besides it is the `user_id` which is like a ~7 digits long number. I can't remember what the verification payload returns when given an authentication token, but it there's no account name in it, displaying information like this is pretty much impossible.  
- The application starts in an unlogged state. To display it's window, a window title has to be already set at startup. There's nothing to display when the window needs to be opened. What to display until the login finishes?  
- The miner currently supports only one account, and any support regarding having multiple copies open (which I'm assuming is the reason for this enhancement request) is not supported.  
- There's no plans to add any "input field" to set the window title. It'll stay as is.

All of the above make this issue pretty much a NoFix.
