### ISSUE TITLE
Progress is being reset to 20-30 minutes before.

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#456]
I checked a drop, it had 40 minutes left. I checked now, and it was on 1:15 (one hour fifteen minutes). No idea what's happening, it's working for most drops.

This is for the "overwatch champions series campaign 4 drops".

Besides, it's impossible for me to farm the drops normally, it took me at least 20+ hours of checking and rechecking 2-3 active tabs to farm the single hour drop for Hitman 3 recently. Again, no idea what's happening.

**Comment by DevilXD** [comment]
> at least 20+ hours of checking and rechecking 2-3 active tabs

You cannot mine more than one drop at a time, and Twitch will simply not count it. If you have several tabs open in your browser, while being logged into the same account as the miner, it will negatively impact the mining process, which will appear as backwards time jumps done by the miner, when it updates it's time remaining to the actual value returned by Twitch.

You cannot watch any other streams during the mining process, otherwise the miner will show you "progress" that isn't real like that, and will generally not work like designed. There's no way to predict or mitigate this in any way, at least not anymore ever since the drops system got changed.

This is thus not a bug.
