### ISSUE TITLE
Log updates to Discord

### ISSUE THREAD

**Issue by ManiacMinor** [DevilXD/TwitchDropsMiner#459]
If I run this from my main pc and want to check the status of the miner (say a new drop was released) I have to remote onto my home machine.

This causes issues as my mobile network blocks this without vpn and at work they block both vpn and remote connections.

So normally it takes a long time to check what it is mining if anything.

Could an option be made to log via Discord webhooks?

Thanks.

**Comment by DevilXD** [comment]
Hello. Unfortunately, Discord (general webhook) integration is not planned to be added now, or in the near future. The only supposed way to interact with the miner is to use the UI it comes with.

My recommendation would be to simply use the miner on your work computer, if the networking setup allows for it (the miner only needs to be able to connect to Twitch to work), switching back-n-forth between the two instances, depending on where you're currently at. If you aren't shutting down / putting to sleep your work or home PC, you'll need to manage starting and stopping the miner at each location yourself, to ensure the two won't overlap. Overlapping the two miners on the same account like that will lead to both of them displaying false progress and generally none of them working as expected, so keep that in mind.

If your work networking setup does not allow connections to Twitch, the other thing you can do is simply trust the miner running on your home PC, making sure to pre-setup it according to your current game preferences. The priority list allows for quite a bit of flexibility with choosing the game you care about the most to not miss out on, while also prioritizing games with shorter/rarer campaigns, over games with long, filler campaigns.

Other than that, since there are much more pressing matters to be solved first, this is a no-fix for now.
