### ISSUE TITLE
[Feature Request] Unlinked Drops

### ISSUE THREAD

**Issue by iXerxes** [DevilXD/TwitchDropsMiner#468]
Currently, the miner only sees linked accounts as valid progression targets. However, [Minecraft/Twich have announced a drop](https://blog.twitch.tv/en/2024/05/15/celebrating-15-years-of-minecraft-on-twitch/) that doesn't require an account to be linked. Instead, you just watch the required channel for the required time and then you redeem a code.

Would it be possible to add support for these types of drops in the future? Obviously fetching the code is unnecessary, but doing the mining would be great, as these types of drops pop up every once in a while and can go under the radar while using the tool.

I understand you're very busy and have limited time for this project, especially with the recent Twitch changes, so I guess this is more to point something out that could be considered in the future maybe, if at all.

Thanks again for your work

**Comment by Kjerne** [comment]
TDM is not intended for/as:

Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
Being hosted on a remote server as a 24/7 miner.
Being used with more than one managed account.
Mining campaigns the managed account isn't linked to.

**Comment by iXerxes** [comment]
@Kjerne yes, I'm aware of these things, however, the thing I mentioned is literally a drop. The *only* difference is this drop doesn't require an account to be linked.

I was also mostly making this post as a note for potential future considerations, as Devil has stated that they'd like to rewrite the miner at some point.

**Comment by DevilXD** [comment]
From the article you've linked, it seems like all of that will not use the Twitch's drops system at all, and instead rely solely on the "old way" of doing the Twitch drops, which is having an external bot watch for chat participants, and then award users based on that. Since TDM does not interact with the chat, and does not maintain a Twitch presence (your account remains in the Offline status the whole time), you'll gain no progress nor any rewards. Supporting the old way of gaining Twitch rewards is not possible, due to the extensive amount of work it'd require, and the fact that everyone uses the new system that's build into Twitch for this - this is what TDM currently supports and is all about. The old way will remain unsupported.
