### ISSUE TITLE
I used the v13 version but it still doesn't work

### ISSUE THREAD

**Issue by OvErrrr** [DevilXD/TwitchDropsMiner#48]
![err](https://user-images.githubusercontent.com/113786918/190864907-0204922f-8aae-4252-8d5d-07c35460dfb4.png)

@DevilXD

**Comment by DevilXD** [comment]
Hello o/

This is an internal asyncio error, that I have no real control on. Something like this would indicate you have some kind of an internet connection issue, but that's as far as I can deduce. The error comes from a line of code that tries to access https://twitch.tv, so please ensure you can load this page in your browser just fine before trying to run the application.

Let me know if this was the issue and you've managed to solve it please.

**Comment by matarife123** [comment]
![Sin título](https://user-images.githubusercontent.com/110930030/190870786-69f635bb-76ec-44eb-b1a4-ac231b3ca3f0.png)

work for me in Windows 11

**Comment by DevilXD** [comment]
Yeah, the problem is that it works for me as well. As far as I'm aware, an unknown yet significant portion of the userbase of this miner are Chinese people who have to use a VPN with a local proxy server to be able to connect to Twitch, which results in the `aiohttp` (the underlaying library the application uses to make internet requests to Twitch) having to do quite a few more hops to reach the destination. More hops means more potential points of failure, like this one. I found some information online about this particular issue, however the recommended fix (disabling the SSL check) cannot be applied here, since it'd compromise the app's ability to verify if it's really connecting to Twitch or not, thus drastically reducing security. I'd like to avoid that if possible.

Since it didn't happen in `v12` and none of the request handling code changed beyond some additional headers, it could be just a temporary issue caused by an incorrect internet connection configuration, which I've asked the user to verify here.

**Comment by OvErrrr** [comment]
> 你好 o/
> 
> 这是一个内部的错误，我无法真正控制。像这样的东西表明你有某种互联网连接问题，但这是我能推断的。错误来自一行尝试访问 https://twitch.tv 的代码，因此请确保在尝试运行应用程序之前，您可以在浏览器中很好地加载此页面。
> 
> 让我知道这是否是问题所在，你已经设法解决了它。

Yes I have found the cause of the problem, since I am from China I have to use v2ray to access twitch. I don't know what caused the software to not pass through the proxy. My workaround was to use Proxifier to direct the software onto the proxy. Thank you for your help.

**Comment by OvErrrr** [comment]
> Hello o/
> 
> This is an internal asyncio error, that I have no real control on. Something like this would indicate you have some kind of an internet connection issue, but that's as far as I can deduce. The error comes from a line of code that tries to access https://twitch.tv, so please ensure you can load this page in your browser just fine before trying to run the application.
> 
> Let me know if this was the issue and you've managed to solve it please.

Yes I have found the cause of the problem, since I am from China I have to use v2ray to access twitch. I don't know what caused the software to not pass through the proxy. My workaround was to use Proxifier to direct the software onto the proxy. Thank you for your help.

**Comment by DevilXD** [comment]
Well, as long as it works for you :slightly_smiling_face:
