### ISSUE TITLE
Looks like automatic cleanup for the channels does not work

### ISSUE THREAD

**Issue by Nevolox** [DevilXD/TwitchDropsMiner#5]
Title already said what the issue is it does not cleanup the channels after 1h (Miner is already running for almost 9h)
![Capture](https://user-images.githubusercontent.com/50830539/150595678-89573ff3-5543-46b6-8b16-ae8c3aec643b.PNG)

**Comment by DevilXD** [comment]
Hello o/

The current latest `v8` version is missing this commit, which will be a part of the upcoming `v9`: https://github.com/DevilXD/TwitchDropsMiner/commit/9b51cf079b6e6d7b688b4eaa24d7018c76678065

What I expect has happened, is that due to this two lines of code missing, the "watch loop" has died on some kind of an exception, and the error never got printed out to you. This means it has stopped "watching" the selected channel as well. `v9` will have this issue fixed, so once you encounter an error with that version, you can file a new issue.

For now, the solution is to just restart the application. I'll keep this issue open until `v9` is released, so if anyone else would run into it, they'll see it's been reported already.

**Comment by DevilXD** [comment]
This should be now fixed in `v9`.
