### ISSUE TITLE
How do we run

### ISSUE THREAD

**Issue by HaYToKoRaZ** [DevilXD/TwitchDropsMiner#500]
How do we run it in Windows 11? Someone please explain it.
tr: Nasıl çalıştırıyoruz Windows 11'de, biri de onu anlatsın lütfen.

**Comment by DevilXD** [comment]
Hello.

This is a Python project repository. It contains Python source code, which can be ran on any platform that can run the Python interpreter. This includes Windows and Linux distributions. There is some extensive instructions explaining how to run this thing on the wiki page: https://github.com/DevilXD/TwitchDropsMiner/wiki

Alternatively, you can download a ready-made, pre-built executable, that contains a bundled Python interpreter, so that you don't have to worry about managing Python installation and project dependencies. Executables for download are available here: https://github.com/DevilXD/TwitchDropsMiner/releases

Please note that the project is currently blocked by a critical issue, that prevents it from working properly: #462. I'd recommend not using it until that issue gets fixed, as it'll simply refuse to work otherwise.

Does this explain everything?

**Comment by DevilXD** [comment]
I'm assuming the explanation was satisfying enough.
