### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by LunnaSmug246** [DevilXD/TwitchDropsMiner#501]
Is it possible to farm drops without linking the account, or does it work if I link it and then unlink it? Can you please clarify if this works or not?

**Comment by DevilXD** [comment]
Hello.

The account needs to be actively linked for the miner to be able to recognize a drop as "mineable". This is to prevent issues with claiming the drops, as well as avoid drop expiration (the drops expire after a week, so you'll need to link your account quite fast anyway). Unlinking the account will prevent the miner from recognizing a drop as mineable, and will thus simply ignore it.

Does this answer your question?

**Comment by LunnaSmug246** [comment]
Thanks, but can like farm but not click collecting  and unlink  to link it to another account?

**Comment by DevilXD** [comment]
No, because you don't need to unlink your account during normal usage. Drops are claimed as soon as they're done being mined.

It's made this way to prevent Twitch abuse, which I don't support. If you're looking for a way to get drops with an unlinked account and without claiming, you'll need to find a different project.
