### ISSUE TITLE
Autostart button doesn't work with Windows

### ISSUE THREAD

**Issue by elmolini** [DevilXD/TwitchDropsMiner#506]
Hey guys, i updated the program to a newer version and lost the dark mode and for some reason the autostart thing doesn't work anymore. Any ideas why or how could i fix this issue?

**Comment by DevilXD** [comment]
> lost the dark mode

Dark mode was never implemented. #197 tracks it's implementation. You may be confusing this miner with a forked version.

Autostart not working is probably related to #296, it's something that I actually wanted to take care of soon. You should be able to find some fix instructions there. If it won't help, please reopen this issue. Otherwise, I'm closing this as a duplicate.
