### ISSUE TITLE
Latest actions windows artifact flagged by multiple AVs

### ISSUE THREAD

**Issue by D3XX3R** [DevilXD/TwitchDropsMiner#508]
This hasn't happened to earlier builts. Probably false-positives but might be worth investigating what's causing this
[VirusTotal](https://www.virustotal.com/gui/file/9fde619f05f59f557b9c9026373310d489ddd1b9f66b3b120a25b5328fbf7e05?nocache=1)
[Hybrid-Analysis](https://www.hybrid-analysis.com/sample/9fde619f05f59f557b9c9026373310d489ddd1b9f66b3b120a25b5328fbf7e05)

**Comment by DevilXD** [comment]
> The only downside now is that the miner will query system registry (on Windows) / query autostart file existence (Linux) on each and every launch, but I consider it a small price to pay for this feature. May or may not lead to overzealous AV engines flagging the miner more, but oh well.

https://github.com/DevilXD/TwitchDropsMiner/issues/296#issuecomment-2200687905

Also, it definitely did happen before, but (most likely) in a smaller magnitude - see #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209 and #13.

I'll repeat this once again - there is no point making "this is reported as a virus" issues, because it will always be reported as a virus, and each new issue about it will be closed, just like this one. If you don't trust the executable, learn Python, study the source code, then run it from source using the interpreter downloaded from the official Python page. Or upgrade your AV engine to something better than AVG, Avast, Fortinet, McAfee, Malwarebytes, and all of the other crap AVs that only exists on VirusTotal and almost no one ever heard of.

**Comment by D3XX3R** [comment]
This is not what I meant with the issue. I personally have used your Twitch Drops Miner before and I haven't had any issues with it, that's why I was confused and thought that there's probably something new that was introduced which caused Windows Defender to flag it. I wasn't aware of your comment on #296

**Comment by DevilXD** [comment]
> caused Windows Defender to flag it.

Windows Defender was always flagging it, so I'm not sure why you think it wasn't doing so before. If you don't believe me, see #503, #420, #384, #335, #284, #270, #217 and #13. If it wasn't doing it for you, I'd recommend throughly checking if it receives regular signature updates, because it was always being flagged. Simply searching closed issues for "Windows Defender" will show you all of these above, and you're supposed to use search before making a new issue, as there's no point in creating duplicates, especially if it was already answered and closed before, with a definite "This is known and it'll forever remain like that, due to the nature of the application" message to it.

If anyone else actually uses search and gets to see this comment - no, please don't create another issue. Thanks.
