### ISSUE TITLE
Linux Mint 21.3 Cinnamon, running from latest source. Program freezes when pressing "Reload" on the settings screen and also randomly when it runs, after a reload task

### ISSUE THREAD

**Issue by Minty-stack** [DevilXD/TwitchDropsMiner#513]
I'm running the latest version cloned from here. The program will hang and become completely unresponsive every time I press "Reload" on the settings tab (for example after adding a new game to mine) - the window will still be movable, but it will not register any clicks, like trying to change to another tab. Doesn't respond to pressing the window close button either - I can only kill it by closing the terminal window it was launched from. This also happens when the program is left to run on its own - it hangs when the reload task is initiated. Below is a screenshot when running it with the -vvv parameter (it became unresponsive after the last entry, again not reacting to any clicks, had to kill the task):
![Screenshot from 2024-07-09 18-51-23](https://github.com/DevilXD/TwitchDropsMiner/assets/174660101/5b63be46-5132-495d-a1e8-b2d3435d688f)

I don't see this issue reported, so I'm unsure if it happens to anyone else - anything I can do to diagnose the cause? The terminal window shows no messages, error or otherwise, it seems like the program just freezes for some reason.

**Comment by guihkx** [comment]
Does the same happen with one of the latest [development builds](https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build)?

**Comment by Minty-stack** [comment]
Yes, I just downloaded the one from the link, logged in/activated from scratch (no copying of cookies file or anything), waited until the initial inventory loaded and tried adding Hitman World of Assassination and pressing reload - froze again, had to kill the process.

**Comment by Minty-stack** [comment]
Update: the development build also became unresponsive after the reload task.

**Comment by DevilXD** [comment]
Hello,

This behavior is certainly strange. I'd start by eliminating the PyInstaller executable being the possible culprit first. Have you tried running it from source? If you wouldn't be sure how to do so, here's some instructions that should explain it: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

**Comment by Minty-stack** [comment]
Yes, I though I mentioned that in my initial report, but turns out I haven't - apologies for that. I first encountered this freeze when running from source, so I tried building the app and it still acted the same way.

**Comment by guihkx** [comment]
This seems to have the same symptoms of #302

**Comment by Minty-stack** [comment]
Tried adding the font mentioned in that error and running from source again - no dice, completely froze on reload...

**Comment by guihkx** [comment]
Does it also freeze by simply enabling/disabling Priority Mode in Settings, and then pressing the "Reload" button after that?

I set up a virtual machine with Mint Cinnamon 21.3, and I didn't freeze for me using the latest dev build:

https://github.com/DevilXD/TwitchDropsMiner/assets/626206/586840cc-9ba8-4b17-a1ec-cc0475b29b01

Out of curiosity, are you on X11 or Wayland? If you don't know, run this on the terminal:

```
echo $XDG_SESSION_TYPE
```

**Comment by Minty-stack** [comment]
Just checked right now (running from source), and yes, it froze on me. I'm on X11.

I did notice something potentially interesting though when watching your video - even though I installed the font from the other issue, my interface looks different from yours - the box/clipboard icons (and the globe one in the settings tab, didn't take a screenshot of that) are monochrome:

![Screenshot from 2024-07-10 21-04-28](https://github.com/DevilXD/TwitchDropsMiner/assets/174660101/862b8f28-d3b0-4e41-a313-cf95f036d80e)

When I run the latest dev build through Wine, these are completely broken by the way (even though the program seems to be working fine):
![Screenshot from 2024-07-10 21-09-29](https://github.com/DevilXD/TwitchDropsMiner/assets/174660101/c8a46c9c-7f7c-4875-96a4-a37059d6e798)

I have no idea if it even matters, but just thought I'd post that, since the other issue was potentially font related.

**Comment by DevilXD** [comment]
I have an idea on what you may try. If you know how to edit some of the code, please try any combination of these:

1. Comment out L1477 in `twitch.py`. This will disable adding campaigns to the inventory display, including not fetching their respective images. This will eliminate image display issues as the possible cause.  
https://github.com/DevilXD/TwitchDropsMiner/blob/35191baaa8613395a078f3226dd05b4aeeddc921/twitch.py#L1476-L1477

2. Comment out L756, L989 and L999 in `twitch.py`. This will do the same as the above, but for channel display. You may get away with only L756 being commented out, but if any GUI errors occur, comment out the two other lines as well.  
https://github.com/DevilXD/TwitchDropsMiner/blob/35191baaa8613395a078f3226dd05b4aeeddc921/twitch.py#L753-L756  
https://github.com/DevilXD/TwitchDropsMiner/blob/35191baaa8613395a078f3226dd05b4aeeddc921/twitch.py#L987-L999

3. You can also try removing all of the emojis from around the source code, to see if they may be causing this issue to occur.

Let me know on how this goes.

**Comment by DevilXD** [comment]
> it did output this to the terminal

It comes from an unclosed connection to a particular server, that closed the connection on it's side. I normally try to catch and fix these, but the cause here may be you commenting out those lines. Without live access to the machine where this is reproducible, there's no real way for me to figure out which of the points in the code generates these, as usually what happens is that these start appearing right after I make some changes, so it's clear that I should look for the cause in the changes I've just made. Here though, it can be any request the miner makes, and they're scattered all over the code.

The good news it that you can ignore these relatively safely, as they don't really cause any malfunctions alone.

> I commented out all the lines you mention (...), and everything seems to be working now - no freezing. (...) Seems image display was the issue indeed, as you expected!

Yeah, it was more or less a blind shot, but other than populating the inventory tab and channels list, the miner doesn't do much more to the GUI, besides changing some strings and progress bars around, which probably has more of a chance of working than adding images or using emojis.

My previous message was divided into three sections of things to try. If you can, please undo as much of the changes as you can, without making it freeze again. We're trying to narrow it down to either inventory display and it's images, or channels list and it's emojis, being the cause of the freeze. Or does it have to be both things commented out for it to work?

**Comment by Minty-stack** [comment]
Done - seems the freezing is related to L1477.
Keeping that one commented and restoring L756 worked, then restoring L989 was also fine, and then restoring L999 also worked. It freezes every time with L1477 active though - regardless of whether the other three lines are commented or not.

**Comment by DevilXD** [comment]
> seems the freezing is related to L1477.

That's images then. Let's dig deeper. You can uncomment L1477, then in `gui.py`:

1. Comment out L1394 - this disables creating the campaign image.
2. Comment out the L1411-L1414 range -  this disables creating images for each individual drop.
3. Comment out L1393 - this disables fetching the campaign image from the cache.
4. Comment out L1408-L1410 - this disables fetching the images for each drop from the cache.

Same deal - we need to narrow it down to the minimum changes, that still makes it work. An important note though: point 3 cannot be applied without applying point 1 first, and sames goes for points 4 and 2. It's because the image has to be fetched from the cache first, then displayed. If you disable the display, fetching still occurs, but the image simply ends up unused, so nothing "bad" happens, beside it not showing up. If you disable fetching alongside that, the image is neither fetched nor displayed, and again, nothing bad happens. But disabling fetching and still trying to display the image will result in an error, so that's why this dependency of the two point pairs exists.

https://github.com/DevilXD/TwitchDropsMiner/blob/35191baaa8613395a078f3226dd05b4aeeddc921/gui.py#L1392-L1417

> Also, thank you so much for spending time on diagnosing an issue that might either be something on my end, or perhaps is limited to this particular version of Linux Mint, which is probably used by 1% of your users, if that. Really appreciate it!

No worries, trying to support different platforms leads me to learning a lot about the differences of them =) Autostart between Windows and Linux is already done separately, as well as duplicate start lock (which previously worked solely on Windows). Having more of this experience never hurts =)

**Comment by Minty-stack** [comment]
Okay, I honestly have no idea what's going on and I feel awful, but suddenly everything works fine again - I am baffled.

I decided to delete the whole directory and start from scratch again so I re-cloned the repo, set up environment and so on, and then decided to test run `./env/Scripts/python main.py` exactly the same as before before making any code changes. I see no updates to the repo since last week, and I did do the exact same thing twice (deleting the whole directory and re-logging in from scratch) before reporting the error, but for some reason pressing the reload button works fine now - nothing freezes, the log updates, everything is working.

I am SO sorry for taking so much of your time - I honestly have no idea what is happening - I didn't reboot the system, haven't updated it in any way, and did the exact same thing I did before reporting the error... Didn't even install any new programs at all. Apologies, truly - I feel so stupid right now... :(

Here's the screenshot showing that manual reloads are working fine now (why didn't they before?!?!), I expect a scheduled one will be fine too.

Ugh, next time I'll not just double-check, but probably check at least 10 times before I open my big dumb mouth to report an error and take the dev's time, so sorry for this. 

![Screenshot from 2024-07-12 08-11-59](https://github.com/user-attachments/assets/899643f1-85ec-442e-8847-1bdaa197c41e)

**Comment by DevilXD** [comment]
Hey, it's no worries, I'm here to help with cases like this =) Glad you've managed to get it fixed, but also kinda bummed out we don't know the real cause behind it. It seems to me that [installing that emoji font 2 days ago](https://github.com/DevilXD/TwitchDropsMiner/issues/513#issuecomment-2219863020) could have fixed it somewhat (even if it didn't do so immediately), although we've ruled out emojis already, and were rather focused on TkInter rendering images...

All in all, the end result seems to be that everything works now, although we don't know how long it'll do so. Hopefully the emoji font was the solution, and it won't reoccur anymore =)

PS: ThInter images are either fetched from the CDN, or read back from the on-disk image cache. Disk readback is done synchronously, and if that'd hang due to the OS taking a long time to open and read the image file, the entire async loop would stop until the file is done reading, and that'd cause the entire application and GUI to become unresponsive like you describe. You can try either deleting or renaming the `cache` folder, to cause it to fetch everything from the CDN again - maybe then the issue will resurface.
