### ISSUE TITLE
Connection Loss Leads to High CPU Usage

### ISSUE THREAD

**Issue by iXerxes** [DevilXD/TwitchDropsMiner#525]
I run multiple instances of the miner which will often get me rate limited, causing the miner to be disconnected from Twitch. I'm fully aware I'm not using the miner as intended, and I accept that I will be rate limited and things wont work correctly sometimes.

However, there is very important issue that occurs when the miner is trying to reconnect. When the miner gets disconnected, it will try to reconnect and the console outputs something along the lines of "Trying to reconnect to Twitch in X seconds..."

I believe this message is being spammed in an un-delayed loop, forcing the CPU to be pinned at 100% usage, and making the miner become unresponsive and slow to reconnect again. I could be wrong, but it looks like it's spamming the message for each websocket connection too, making things even worse.

Far too often I'll come back to my CPU fans being maxed to account for 100% CPU usage. If I don't catch it in time, it can (and has) go on for hours, as the load causes such significant disruption it can't reconnect again. I'm forced to terminate the miner and re-launch it.

**Comment by DevilXD** [comment]
> it looks like it's spamming the message for each websocket connection too, making things even worse.

That's correct, every ongoing request that gets cut-off by Twitch not responding will print that message in the log. Usually it's either the watch loop or inventory refresh that runs into it, so there will be only one request waiting for a reconnect. If you happen to get it while campaigns themselves are being fetched (one request per campain, usually ~50 active at once), pictures for campaigns getting fetched (`campaigns_amount` * `average_amount_of_images_per_campaign` requests active at once), or it's the websocket connection that's trying to get estabilished (up to 8 requests active at once), then you may end up with all of those requests logging in the "can't connect" message.

There's a simple solution - don't use multiple instances at the same time. I don't support it, Twitch will disconnect on you often, the miner will report false progress, and everything will just not work like you'd expect it to. If you're looking for a miner that can run on a server and/or in multiple instances, you may want to look for a [different project (example)](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2). This project is a **personal** miner, designed to be used with a single account at a time only. Definite most of general users have only one Twitch account they have to worry about anyway.

> I believe this message is being spammed in an un-delayed loop

Every "can't connect" message will wait for the amount of time stated by it before resuming, but again, there may be multiple requests happening at once, and all of them will log one of their own messages simultaneously. which can create the illusion of the delay not being there.

I won't be fixing this, since it's the effect of something I don't support, and I have more important things to work on instead. You'll need to either deal with it on your own, or simply stop using multiple instances at once.
