### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by IceShadowPhoenix** [DevilXD/TwitchDropsMiner#529]
I am currently running the TDM software on a server. Unfortunately, it crashes due to some errors. Strangely enough, they disappear again as soon as I download the updated package. I hope you understand my problem. An auto update feature that downloads and installs updates automatically and restarts the software automatically would be a fantastic feature. This way the software is always up to date and previous errors are automatically corrected with the updates. I think some people would be happy about this feature :)

**Comment by DevilXD** [comment]
Hello.

It may not be entirely clear from the Project Goals, but auto-update would just make it easier to maintain bot farms with thousands of accounts mining at once, which is why I'm saying no to this. You can see all project goals here: https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals

I'll update them so that it's clear that auto-update is not going to be a thing.

Also,  you're not supposed to run this on a server, which is also against the project goals. You may receive no support from me if you're doing that.
