### ISSUE TITLE
Not priority option

### ISSUE THREAD

**Issue by biast12** [DevilXD/TwitchDropsMiner#532]
Would love if there were an option to have a not priority list

This list should only start mining drops when all drops from the priority list and all not excluded drops are done

So the priority order would be
`priority list` => `other drops that isn't excluded or in the "not priority list"` => `not priority list`

Personally i would use this instead of the exclude list as i don't really mind it mining for drops that i won't ever use if there's nothing other left to mine

**Comment by DevilXD** [comment]
Hello. Two things here:

- What you've described can be already partially achieved, by unchecking the "Priority only" setting in the miner. That'll cause it to mine every single drop that the miner can possibly mine, even if it isn't added to the Priority list, as long as it isn't also Excluded. However, note that beyond the Priority list, there's no specific order being enforced, so it's basically an option to "let it mine whatever, in the time it'd otherwise spend idle".  
- If you require a specific order for those drops to be mined, just use the Priority list for that.

I won't be adding a 2nd priority list, because I find it quite pointless given the above.

**Comment by biast12** [comment]
Mmm the thing is it can't really, you can only make 2 priorities, the priority list and the rest, what this feature would allow is to have a `important`, `not important but still good to mine` and `not important`, rn does it only have a `important` and `not important` priority, sure you can add every single game to the priority list and order it that way, but what then when a new game/drop comes? then i would need to keep the priority list updated all the time which is just straight up imposable.

I understand that for you it might sounds stupid since the options that *exist* rn can give a somewhat but still really janky solution to this enhancement, but for me would it be extremely useful as i can fully replace it with the things i got in the excluded list.

The whole idea with the enhancement is to still allow games/drops you might not want / is less important than those that isn't a priority, but still give the chance to mine them if they're nothing else left to mine.

It's basically just the excluded list but only mine them if there's nothing else left to mine, honestly even having it as an option like that to "allow excluded games to be mined if there's nothing else to mine" would be perfect, that would really do the same just by using the excluded list.

**Comment by nudave** [comment]
Perhaps the wording is what needs to be adjusted. Instead of priority,
maybe “Inclusion Only”.  Might be a happy medium?

**Comment by DevilXD** [comment]
>  what this feature would allow is to have a important, not important but still good to mine and not important

Again, I won't be adding a second priority list, because it's entirely not needed. If you want the drops in a specific order, use the existing Priority list. If you don't care about the order and just want to get all drops you can, uncheck the Priority only option. If you don't want the miner to try mining a particular game, use the Exclude list.

> what then when a new game/drop comes? then i would need to keep the priority list updated all the time which is just straight up imposable.

I really don't like to repeat myself, so I'll just point you to #330 for you to read what I think about this. My stance doesn't change.

> it be extremely useful as i can fully replace it with the things i got in the excluded list.  
> It's basically just the excluded list but only mine them if there's nothing else left to mine,
> The whole idea with the enhancement is to still allow games/drops you might not want / is less important than those that isn't a priority, but still give the chance to mine them if they're nothing else left to mine.

The Exclude list lets you specify the games you aren't going to play, which lets the miner skip those entirely. If you do want drops from those campaigns, don't add them to the Exclude list. If you don't, you can add it there to let miner skip them. There's no middle ground here, you either want those drops or you don't - I think that's quite simple to understand. This entire "enhancement" doesn't make any remote sense, do you even know which drops you want to mine, or not? There won't ever be a "maybe mine this" option in the miner.

**Comment by biast12** [comment]
..... you don't understand what i'm saying at all.... look at the last paragraph in my last comment, i'm not looking for a full priority list, because yes that already exist so obviously i'm not asking for that?......

> It's basically just the excluded list but only mine them if there's nothing else left to mine, honestly even having it as an option like that to "allow excluded games to be mined if there's nothing else to mine" would be perfect, that would really do the same just by using the excluded list.

An option to "allow excluded games to be mined if there's nothing else to mine" would 1 not be adding another priority list, but also allow people to sort the general priority so much better than just having a priority or not.

It would be useful for people to be able to sort priority in `top priority`, `middle priority` and `not priority` instead of just `top priority` and `not priority`, most people don't just want or don't want drops to be mined.

**Comment by DevilXD** [comment]
It's you who doesn't understand what I'm saying. What I'm saying is: there won't ever be another "priority" list beyond what's already there. I am not going to implement this. Also, there's no "not priority", the Exclude list is basically "don't mine this". It doesn't have anything to do with any priorities there, the miner just doesn't mine it - ever. Any option that would overwrite that makes the meaning of the list completely pointless.

Utilize the existing lists to do what you want, and if that doesn't suit your needs, you'll need to find a different project.
