### ISSUE TITLE
[Info] Twitch-Channel-Points-Miner-v2 work for drops

### ISSUE THREAD

**Issue by Diekion** [DevilXD/TwitchDropsMiner#538]
Hello.
I'm saying this in case reviewing the code of this application helps you solve the problems or improve your application.

Testing this application that is originally for mining chat points, I realized that it is capable of mining drops.

The application in question is
https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

In my case, I use it through Docker.
https://registry.hub.docker.com/r/rdavidoff/twitch-channel-points-miner-v2/

Also, the detection time is much faster, which means that I don't lose drops that have a very short time frame. Some developers like to put 1-hour drops in 1-hour and 15-minute streams or similar. Elite Dangerous for example.

I hope it helps you.

**Comment by DevilXD** [comment]
Hello,

I am aware of that project's existence, even recommended it to others when responding to issues they've created for my miner. There isn't anything there that I could make a use out of though. Furthermore, I don't feel like just using someone else's code is the right way to go. I have to say that I've taken some inspiration from it back when this project was starting up, but that's about it as far as similarities go.

The detection being faster is done solely because the other miner works differently. I already have plans to speed my miner up (see #220) when it come to faster reloads, but it has to be done without being a nuisance to Twitch, otherwise this project won't live for long.

Other than that, since this issue isn't an actual "issue", I have to close this as Invalid. Thank you for your message =)
