### ISSUE TITLE
Purchase / Gift Subscription Drops are not ignored

### ISSUE THREAD

**Issue by FlamingFox911** [DevilXD/TwitchDropsMiner#544]
It seems like there is a new drop type. It requires users to Subscribe or Give a Sub, instead of watching participating channels for a certain amount of time.

![image](https://github.com/user-attachments/assets/eb6d9f1f-33b2-4ee6-95f5-7c877df3bff5)

The miner correctly doesn't mine this (since it's flagged as 0 minutes), but it still appears in the inventory list.

![image](https://github.com/user-attachments/assets/eb00651b-83cf-4ce8-b5ef-a996255d6d06)

**Comment by DevilXD** [comment]
Hello,

The inventory view isn't supposed to ignore any drops - if a drop appears on the Inventory or Campaigns Twitch pages, then it's going to show up in the inventory view. Drops that have a watching requirement of 0 minutes aren't considered valid mining targets, so the miner just ignores them. Everything works as intended.

What issue are you experiencing, exactly?

**Comment by FlamingFox911** [comment]
Hmm, besides that, there are no other issues. I was under the assumption that the miner was trying to get a drop for which it has no chance (due to a non-watching requirement), but as I said (and you confirmed) the miner ignores mining it. But it is still a little annoying that I still see the campaign.

Is there a chance to have a toggle to show or hide 0 minute campaigns?

**Comment by DevilXD** [comment]
Hmm, an extra toggle might not be a bad idea, but I can also just make it so that if the sub-based drops is all the campaign contains, then it won't show in the inventory view. There would need to be at least one time-based drop for a campaign to be displayed. Is that enough for you?

**Comment by FlamingFox911** [comment]
That can work. Thanks. I'd appreciate it.

Just thought of this, but as an alternative, would it be possible to give the user an option to ignore a campaign? That way, it can also allow users to disregard specific campaigns, regardless of circumstances.

**Comment by DevilXD** [comment]
A feature like that is already tracked by #170.

I'll implement the suggestion from my previous comment soon, once I can find some time for it.

**Comment by tomardo** [comment]
This same problem happens with the new campaign from Destiny 2, making the app trying to indefinitely farm the drops:


<img width="1449" height="720" alt="Image" src="https://github.com/user-attachments/assets/89e2cd30-edcb-4e30-861b-bfcdcbe59eeb" />

<img width="444" height="185" alt="Image" src="https://github.com/user-attachments/assets/b03b9b63-e8e0-48de-92e6-45ed87334836" />

**Comment by DevilXD** [comment]
@tomardo I just verified the data from Twitch directly, and there is no way for that to happen in the current version of the miner. Please ensure you're using the latest development version. The latest version won't even display the campaign in the inventory tab (like in your screenshot), because sub-only drops have a requirement of 0 minutes, and there's a check on L1301 in `gui.py` that will hide it:

https://github.com/DevilXD/TwitchDropsMiner/blob/eab58cd5f2c70fc896a9242db349bb5be7556615/gui.py#L1291-L1314

Running the miner locally confirms this, the campaign isn't even there. If this issue persists on your side, please open a new issue, since this one has already been resolved.
