### ISSUE TITLE
[REQ] Linked Only 

### ISSUE THREAD

**Issue by AirHeadsbuirse** [DevilXD/TwitchDropsMiner#545]
Not sure if this is the right spot, would it be possible to add Linked Only to the General tab ? That way we dont need to add all the linked games individually

**Comment by DevilXD** [comment]
Hello,

I'm a little bit confused at this request. What "Linked Only" you're talking about and you'd like to be added? What is it supposed to do? What do you mean by "add all the linked games individually"? There's no way on the Twitch website to bulk-link accounts in any way. Please provide a more specific description on what exactly you'd like to have added.

**Comment by KeinNameVorhanden** [comment]
My guess is that he's referring to an option similar to "Priority only" which would restrict mining to campaigns with a linked account. He might not be aware that the miner already mines only those campaigns that are linked to an account.

**Comment by DevilXD** [comment]
In that case, there already is an option like that - it's called "Priority Only", can be found in the Settings tab, and unchecking it will make it so that the miner mines all campaigns it possibly can, as long as all conditions for them are met - and that includes having a linked account to a campaign. Priority list can remain empty. That was the only mode available before the priority list got added.
