### ISSUE TITLE
[BUG] Unable to catch a stream

### ISSUE THREAD

**Issue by barbiehunter** [DevilXD/TwitchDropsMiner#551]
Not sure what you did with the update of https://github.com/DevilXD/TwitchDropsMiner/commit/a42a72bfb1e9d0e0210a81a01e80f2d1c2f0a3a6 but with the new version it have problems seeing a stream on . Picture bellow shows it catch nothing, first as i Removed the Star Wars Outlaws it catched a stream after few/severeal seconds
![librewolf_WdmjfMGP97](https://github.com/user-attachments/assets/f7a9b794-801c-4420-9c93-c14db34a1c10)

**Comment by DevilXD** [comment]
The picture shows you manually reloading the miner several times. That's unnecessary, and the miner just needs 2 minutes after a reload to pick up on the mining now. This is true since https://github.com/DevilXD/TwitchDropsMiner/commit/f705cc1527e806bb979df9e0dbd077d93728160c, which is from over 3 weeks ago. See #543 and #537.

You can see the 2 minutes delay on your picture even. Just wait - that's all there is to it.
