### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by Demo30123** [DevilXD/TwitchDropsMiner#571]
I cannot log in to other accounts, can I use this software to drop only with one account? How can I use websockets? I want to increase drops on multiple accounts.

**Comment by DevilXD** [comment]
Hello,

"Multiple accounts" is not supported. A single IP address is limited to 10 websocket connections per IP address, and each connection is limited to 50 topics, per Twitch documentation: https://dev.twitch.tv/docs/pubsub/#api-limits  The miner uses 8 out of the 10 connections, to let you access the twitch website without going over the specified limit. Note that this is a per-IP limit, not per-account one, so multiple accounts would have to share a single pool of websocket connections anyway.

Consistently going over the limit (by for ex. running multiple instances at once) will cause the miner to stop working (existing websocket connections stop receiving updates consistently), and tip-off Twitch to work on implementing measures that basically destroy this project. I'm already struggling with maintaining it as is, and it'll get discontinued and disappear if people will keep misusing it. More information can be found in the project goals: https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals

There's no way to mine on multiple accounts at once without pissing Twitch off. If you'd still want to do it, you'll need to stagger the mining sessions over multiple accounts, so that there's no more than one instance running at a time.

This is a NoFix from me. I won't be helping you here.
