### ISSUE TITLE
[ENHANCEMENT] Watch streamer with least viewers

### ISSUE THREAD

**Issue by StevensUneven** [DevilXD/TwitchDropsMiner#572]
Is it possible to add the ability to watch the streamer with the lowest number of viewers rather than streamer with most? This way we could potentially help small streamers out.

**Comment by DevilXD** [comment]
Hello,

The miner doesn't actually "watch" a stream, only pretends to be doing so. I'm actually not entirely sure if this counts as watching at all (by increasing the viewers count). The miner does the bare minimum to keep getting drop progress, without downloading any actual stream data.

On top of this, per the project goals, the intention for this application is to remain drop-focused - and that means it doesn't really matter which stream is being "watched", as long as drop progress is obtained through it. Searching for live channels sorts the results by viewers count (Twitch returns them as sorted like that), and streams with high viewers count are less likely to go offline quickly, leading to the miner having to perform less channel switching. Every switch introduces a 5 minutes penalty period, during which the mining process is disrupted and might not-count or mis-report progress on a drop. It only makes sense to keep the channels sorted by the viewers count during a reload because of all this.

Similar mechanics were already suggested in #105, and the response more or less still stands. If you're looking for an application that lets you watch particular streamers, this isn't one - it's all about the drops only, regardless of which channels are used for it.

The best you can do, is use the "Switch" button available on the channel list, to change the watched channel to a different one. This will be reset to the auto-picked channel after every reload, so usually every hour. Other than that, this unfortunately is a NoFix from me.
