### ISSUE TITLE
Simplified Chinese translation not working

### ISSUE THREAD

**Issue by zhangminghao1989** [DevilXD/TwitchDropsMiner#584]
Simplified Chinese translation not working

**Comment by DevilXD** [comment]
Hello,

Please specify how exactly is it "not working". The miner displays the default English translation, even if you select Simplified Chinese? Is this related to #585?

**Comment by JourneyOver** [comment]
This could be due to the fact that when @Suz1e made #582 he screwed up and added a extra `}` which is causing a parse error.

**Comment by zhangminghao1989** [comment]
#585 fix

**Comment by JourneyOver** [comment]
I mean you still have a parse error for the Simplified Chinese translation file regardless of the #585 PR, so... xD

**Comment by DevilXD** [comment]
@zhangminghao1989 You can use https://jsonformatter.curiousconcept.com to validate the JSON before submitting it as a PR. It's also a good reminder for me to verify this as well, before I merge a translation update.

Fixed in https://github.com/DevilXD/TwitchDropsMiner/commit/9ee872f4754f3a88043c5f94358bc22763d6058d.
