### ISSUE TITLE
Version 14 forced application update?

### ISSUE THREAD

**Issue by PhantomMist** [DevilXD/TwitchDropsMiner#595]
I am using version 14 specifically the executable. I'm trying to login but it gives me the error "exceptions.LoginException: Please update your app to continue". Do i need to update to the latest version, if so. How can i verify that the newest version is safe for my computer to run? Any help would be greatly appreciated 

![image](https://github.com/user-attachments/assets/1fbddadb-3ff6-4eaf-8ff9-ea992d94b4c6)
Here is my screenshot

**Comment by DevilXD** [comment]
Version 14 is way, way too outdated to work in any way. The only currently working version is `v16.dev`, available as the current development build. It's quite stable as it is, but I still need to deal with a few issues here and there to declare it truly stable. The changes never stop piling up, but I'm slowly working through them.

> How can I verify that the newest version is safe for my computer to run?

This is an open source application. All code is visible to you and everyone else right here in this repository. If you know how to read all or some of it, you can do this verification yourself. Otherwise, you have to rely on someone else doing that for you. Either way, you'll need to believe that it's safe, just as safe as v14 was. Behind the scenes, the twitch website is the only place from where the authorization token is obtained, and it's the only place where it's used.

If this isn't enough for you, you can wait for someone else to comment on this topic here I guess. Not using the app at all is also an option. I'm not forcing anyone to use it anyway.

**Comment by Lifeng77X** [comment]
> La version 14 est bien trop dépassée pour fonctionner de quelque manière que ce soit. La seule version actuellement en cours est `v16.dev`, disponible en tant que développement actuel. C'est assez stable, mais je dois encore traiter quelques questions ici et là pour le déclarer vraiment stable. Les changements n'arrêtent jamais de s'accumuler, mais je les travaille lentement.
> 
> > Comment puis-je vérifier que la version la plus récente est sûre pour mon ordinateur ?
> 
> Il s'agit d'une application open source. Tout code est visible pour vous et pour tout le monde ici dans ce dépôt. Si vous savez lire tout ou partie, vous pouvez faire cette vérification vous-même. Sinon, vous devez compter sur quelqu'un d'autre qui fait ça pour vous. Quoi qu'il en soit, vous aurez besoin de croire que c'est sûr, tout aussi sûr que v14 l'était. Dans les coulisses, le site de twitch est le seul endroit d'où le jeton d'autorisation est obtenu, et c'est le seul endroit où il est utilisé.
> 
> Si ce n'est pas suffisant pour vous, vous pouvez attendre que quelqu'un d'autre commente ce sujet ici, je suppose. Ne pas utiliser l'application du tout est également une option. Je ne force personne à l'utiliser de toute façon.

Hello, I just tested your version v16, but I can't log in; the "login" section is grayed out...
![image](https://github.com/user-attachments/assets/de508af1-dd1e-40a7-a1c9-959c82f5733e)

**Comment by DevilXD** [comment]
@Lifeng77X First of, don't comment under an issue, unless you're experiencing the same problem. Not being able to login has nothing to do with updating up from v14.

Second of, you can delete the cookies file to force a reauth. That should let you login properly. If not, please open a separate issue.

I'm closing this one as I'm pretty sure it's been resolved by now.
