### ISSUE TITLE
Progress is being reset (again)

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#598]
in my case, it takes around 24 hours to farm a maximum 4-6 hours drop. Not sure what's happening, how can I report this?

It's happening for The Division 2, Hearthstone, Warframe, etc.

**Comment by DevilXD** [comment]
Hello,

I'm assuming that you're referring to the miner backtracking on the progress it's showing. This is quite confusing - the real progress itself is never "reset" in any way. You can track the real progress by opening and refreshing the inventory page: https://www.twitch.tv/drops/inventory

Is the progress simply not being counted then? Please note that the usual cause for the progress desync between website/real and what the miner shows, is due to watching a stream in the browser alongside the miner running, even if the stream you're watching has no drops to it.

**Comment by notNSANE** [comment]
> Is the progress simply not being counted then? Please note that the usual cause for the progress desync between website/real and what the miner shows, is due to watching a stream in the browser alongside the miner running, even if the stream you're watching has no drops to it.

I do watch a stream in the browser at almost all times... but this wasn't an issue for all games, just specific ones like Overwatch 2. I never could get to the root of the cause.

I think Twitch just shadowban/IP bans/timeout me from getting any drops for X amount of hours because "too many requests" or something. Right now, everything is worked correctly, I think I got most

It's time I fix this the hard way and just use a second account for drops. It's very painful since I need to move all twitch likings to the other account, but unless there's a way around it with TDM, I think it's the only way to fix this longstanding issue.

**Comment by DevilXD** [comment]
I mean, I'm pretty sure that the miner has always had an "issue" with using the Twitch account in the browser to watch anything, while it was also running. To avoid this, simply don't use the account while the miner is running. Using a 2nd account to watch in the browser would also work.

These are only my speculations, but from my observations, on the Twitch side, it looks like you're watching two streams at the same time, and as far as I'm aware, the drops system is just a simple "progress gate" design, where a watch request sets off the progress advancement, then the "gate" closes for the next 20 seconds or so (where requests are ignored), and then opens for the next watch request to advance the progress again. The stream you're watching in the browser is sending those far more often than the miner does, because it has to receive the actual uninterrupted stream data. What ends up happening, is that out of all watch requests the Twitch receives, the majority of them end up being the browser stream requests, with only a few requests from the miner here and there. That makes the browser stream hit the progress gate more often than the miner can, leading to the drops system processing the browser stream, not the miner stream.

From the above, it may sound like getting any progress would always be impossible, but actually the whole miner's system synchronizes when the miner starts running. The miner sends the first requests and then starts it's wait for 20 seconds, the Twitch receives the requests and starts it's wait for 20 seconds, and then 20 seconds later, the progress gate opens just before the miner sends it's request. This makes Twitch appear as "synchronized" to the miner's requests. When you start watching in the browser alongside to this, the browser would have to do it's request in that very small amount of window time (~100 ms range) between both sides finishing their 20 seconds countdown, Twitch opening the gate, and the miner's request being received on their end. This would desync the Twitch's drops progression system from the miner, and instead sync it with the browser's stream. After starting the miner and letting it sync for a few request, starting to watch in the browser won't immediately make you lose progress, until that desync happens. The miner most likely won't be able to resync back, due to the majority of the requests being sent from the browser, but that doesn't make it impossible as the resync window remains close by, and it may actually just keep switching back occasionally. On the user's end, it will look like the miner is gaining "patchy" progress, that keeps jumping back to higher values at those times where the miner happens to resync.

As time goes on though, both miner and the browser stream will keep running more and more out of sync of each other, and that'll basically remove the possibility for resync. At that point, Twitch will keep accepting progress from only one of the streams, and the other stream won't be doing anything. This will continue until the difference in cycles becomes so large, one stream actually skips it's cycle, and they'll both resync once again, leading to more patchy progress. This will continue indefinitely, as long as both streams are running. Closing the browser stream for ~5 minutes should resync Twitch back to the miner.

I don't know if this explanation makes sense or not, but I can draw some diagrams if you'd like to understand it better - let me know if so. Also, again, this is all just my very own speculation, based on my own personal experience when running the miner and a stream in the browser at the same time. It's the only explanation that makes sense, given the results I was able to see and notice, as well as the results of people who have reported issues with their drop progress here in the past. Still, I may be just talking out of my ass, Twitch is using a completely different design, and I'm a fool for trying to educate you on how this works. Only the person who designed the Twitch drops system on their side would be able to dispel any doubts here.

**Comment by notNSANE** [comment]
I fully understand the analogy, it's fine, I understand much better what's happening now. I also see behavior like this but I don't get why it was working fine until a couple days ago, then it fully locked me out yesterday with Division 2. I had to block that game because it was resetting progress for the final drop for an entire day.

I'll close the ticket and start the painful migration. Thanks for the long explanation and your time!
