### ISSUE TITLE
Multi use

### ISSUE THREAD

**Issue by skapytek** [DevilXD/TwitchDropsMiner#602]
Hello,
wanted to ask if it is possible to run 2 instances of TwitchDropsMiner?
I want to farm more than 35 games (if i add more to the priority list its crashing), so i can run 2 instances at once (i know that i can farm only 2 drops at one time).

regards

**Comment by DevilXD** [comment]
Hello,

> i know that i can farm only 2 drops at one time

I don't know where you saw this, but it's not true. [Twitch Drops FAQ](https://help.twitch.tv/s/article/mission-based-drops) clearly states that "you" as a Twitch account user, can earn progress towards only a single drops campaign at a time. Watching two different channels won't advance two different campaigns, nor let you advance the same campaign twice as fast. It used to be possible to watch two different channels at once, to receive channel points for both - however, this miner is about drops, and drops have a strict single channel/campaign limitation.

Other than that, if you're asking about running two instances at once, that are connected to the same Twitch account, then the answer is no, due to the above. It means only one of the miners would be doing anything, while the other would be just interfering with everything. The miner is designed to fully handle a single Twitch account, and that's it. There's some existing measures to prevent launching the same instance twice for this reason already.

If you're asking about running two instances at once, that are connected to different Twitch accounts, then the answer is yes, but with a caveat - Twitch doesn't really like when multiple different Twitch accounts are "watching" different streams from the same computer/IP address, and may end up interfering with the mining process. Two or three accounts should be fine, but anything more usually ends up with nothing working and errors everywhere.

As far as the 35 games "limit" goes, as I've said somewhere else already - the miner was not designed to mine the entirety of all available campaigns on Twitch, and it makes little sense to me why would anyone even want to do that. Are you seriously playing more than 35 games at once? Drops claimed for games you don't play or have an account for, usually expire within a week or two, so there's no way to "bank" them beforehand, even if you would like to play that game in the future.

**Comment by skapytek** [comment]
I thought i am able to farm 2 drops at the same time.

I have an account for all games, but I'm not playing all of them actively. I'm a games' collector, and I'm trying to get as much dlcs, ingame items and drops as I can.

Thanks for the clarification.

**Comment by DevilXD** [comment]
> I thought i am able to farm 2 drops at the same time.

Just to 100% clarify this, for you and anyone else who might end up here later, from the FAQ I've linked earlier:

![pic1](https://github.com/user-attachments/assets/07178d7a-138e-41ca-87df-7af795637cb1)
![pic2](https://github.com/user-attachments/assets/f3c5d14d-720f-4f0b-983c-e3ef1f4a45d2)

Only one drops campaign can be progressed at a time.

> I have an account for all games, but I'm not playing all of them actively. I'm a games' collector, and I'm trying to get as much dlcs, ingame items and drops as I can.

Hmm, well, I see. I get that it's a collector's thing, and you'll probably disagree, but if you're just getting drops and not using them by playing the games, then there's no real point in getting the drops in the first place. "Having" something is meaningless if you don't get to use/experience it's results.

This miner was also not designed for that level of usage, and might not be the best tool for you. For best results, I'd recommend avoiding or excluding (even temporarily) games with campaigns having really long ACL lists. I've compiled a list of these under one of the earlier issues, here: https://github.com/DevilXD/TwitchDropsMiner/issues/554#issuecomment-2350057062
