### ISSUE TITLE
"Open Reward Campaigns"

### ISSUE THREAD

**Issue by r5vx** [DevilXD/TwitchDropsMiner#628]
This is a pretty minor thing, but I noticed that the twitch drops miner doesn't detect (or mine) the open reward campaigns, such as the fallout 76 reward requiring 15 minutes watched on any fallout 76 stream.

These drops don't seem to occur that often so its not like we are missing out on much, but if it does in fact turn out to be an easy fix then that would be nice.

Thanks for all your hard work!!

![image](https://github.com/user-attachments/assets/29a6ca6e-c9b9-46ec-9ac0-d13717b71def)

**Comment by DevilXD** [comment]
This was already explained in #468. Reward Campaigns are a completely different system, that would require substantial changes to the miner's internals. The campaign has an entirely different data structure, the rewards section is an entirely different structure, no ACL makes things simple, but the detection mechanism is based on the account being online, something the miner does not currently handle/spoof. Since it'd pretty much require me to develop a second miner within the current one, I'm not interested in supporting these.

Besides, 15 minutes for a reward is a laughably short period for the amount of work that would be needed in the miner to handle these. Just claim them the normal way. This miner was developed to deal with 7x4 hours (28 hours total) weekly campaigns, that had the drops setup in a dependency sequence (claim one to even allow gaining progress for the next one), and dealing with that was a real pain.
