### ISSUE TITLE
No active compaigns to mine drops for. Waiting for an active campaign...

### ISSUE THREAD

**Issue by Cybertat1on** [DevilXD/TwitchDropsMiner#636]
Hi, what is it? A day ago everything was working, and now this error
No active compaigns to mine drops for. Waiting for an active campaign...
![1](https://github.com/user-attachments/assets/1c0f7620-2017-4c1f-ac57-b07e735dcebd)

**Comment by DevilXD** [comment]
Hello,

This is not an error, and thus not a bug. Unless you can see "error" or "exception" stated in the message, it's never an error, simply an informational message. The message states the current situation of the miner - there's no active campaigns the miner can mine drops for, so it has to wait for an active campaign first. For that, it enters an idle state and rechecks everything every hour or so, to see if a new campaign has appeared since the last check. If not, it stays in the idle state, if so, it goes back to mining as usual.

Does this explain it?

**Comment by TheLovinator1** [comment]
Are you trying to farm Rust drops like this guy? https://github.com/DevilXD/TwitchDropsMiner/issues/637

**Comment by Cybertat1on** [comment]
> Are you trying to farm Rust drops like this guy? #637

No, I used the priority list, added POE2 and nothing else, then switched the mode and after 20 minutes everything worked. But, the most interesting thing is that before that it worked on a priority list (I added about 5 companies). Everything is working now, thank you.

**Comment by DevilXD** [comment]
If you make changes to the priority list, exclude list, or the priority mode, you need to press on the "Reload" button that you can find right under the lists on the Settings tab. Otherwise, your changes won't be immediately applied, and instead, you'll need to wait for the miner to reload on it's own before it'd start mining. The message was most likely printed before POE2 was added to the priority list, meaning that the miner has already switched to Idle state.

Again, this is not a bug. If reloading doesn't work, you can try restarting the application. If you've changed no settings, and it doesn't mine even after a restart, then it'd make sense to report it as a bug. Otherwise, just follow the instructions and use the Reload button to apply changes.
