### ISSUE TITLE
Please make it so it can just mine any drop!

### ISSUE THREAD

**Issue by murdersbane** [DevilXD/TwitchDropsMiner#643]
Sorry if this is in the wrong section. But I would really like it to just be a simple "set and forget it" bot that just mines drops Incase I don't check the bot for 1-2 days vs how it is now where I have to link things before it will even try to mine the game even if I have added it to the list of preferred options.

Maybe ad it as an option to mine anything available?

Ps love your bot tho it helps a lot. Just had issues especially when twitch doesn't want to show a game as linked even when it is

**Comment by DevilXD** [comment]
Hello,

If you have issues with Twitch incorrectly reporting your account link status, you can use the clean reconnect procedure to fix that. Some instructions for it can be found here: https://github.com/DevilXD/TwitchDropsMiner/issues/309#issuecomment-1749628379

Other than that, an option to "mine anything available" already exists, and it's under the "Priority Mode" option - just set it to anything other than "Priority list only" to let it mine any drop that can be mined. Only campaigns where you have your account linked to count as mineable though, so keep that in mind.

An option to ignore the linking status for mining purposes won't ever be added, because it's against the project goals. This topic has been already discussed many times before, so if you'd like to learn more, see the project goals and use the search function. The project goals can be found here: https://github.com/DevilXD/TwitchDropsMiner#project-goals

**Comment by murdersbane** [comment]
I do not understand why this would even be a "goal" tho. It's about twitch drops??? I will look for another miner I guess. Defeats the purpose of I have to constantly link every new campaign

**Comment by DevilXD** [comment]
If you cannot understand that I do not support people setting up mass farms for thousands of accounts (something this change would make easier to do and setup, as this has already happened before), then I cannot help you. Several feature of this miner have been limited for this very reason. If you're one of those people, then please - go away and don't even bother me.

In normal usage cases, you'll need to link your account to a campaign anyway, in order to receive the drops, so this does not impact normal users. If you really want to, for whatever reason, get drops that you won't be able to claim (because of the missing account link), then yes, you'll need to look for a different project.

Goodbye.

**Comment by DevilXD** [comment]
If you cannot understand that I do not support people setting up mass farms for thousands of accounts (something this change would make easier to do and setup, as this has already happened before), then I cannot help you. Several feature of this miner have been limited for this very reason. If you're one of those people, then please - go away and don't even bother me.

In normal usage cases, you'll need to link your account to a campaign anyway, in order to receive the drops, so this does not impact normal users. If you really want to, for whatever reason, get drops that you won't be able to claim (because of the missing account link), then yes, you'll need to look for a different project.

Goodbye.
