### ISSUE TITLE
[Question/Enhancement] Farming drops that do not have campaigns

### ISSUE THREAD

**Issue by golden865** [DevilXD/TwitchDropsMiner#644]
Hello, I hope everyone reading this is having a nice day, also thank you for creating this tool, it is super helpful!

I was wondering if it would be possible to mine drops for games that do not have drop campaigns. An example of this is zenless zone zeros latest drops, they do not have an actual twitch drop campaign, instead they just track the hours watched on streams under the category. Is it possible to make this miner watch a stream under a game category even if there is no drop campaign for it?

If not I think it would be a useful feature to add as the miner uses far less resources compared to actually watching these stream for hours on end. I'm not saying that it should be able to find or track these 'drops' but I think adding a way to manually pick a stream/category for it to watch regardless of active campaigns would be cool.

Again thanks a lot for making this miner, its very useful and I appreciate it.

 Have a nice day!

**Comment by DevilXD** [comment]
Hello,

Glad you've found the miner useful =)

> adding a way to manually pick a stream/category for it to watch regardless of active campaigns would be cool.

Per the project goals, this miner is meant to provide an automatic way of getting Twitch Drops. If there's no actual Twitch Drops to be mined, then there's no point to this application. For this reason, any way other than the currently-present Twitch campaigns is not supported, including manual channel adding and selection. 3rd party sites won't be supported either. This application is meant to handle Twitch Drops only, and nothing else. At least that's my current stance on this.

This has already been covered by #164 to some degree too. Because of the above, I'm closing this as a NoFix.
