### ISSUE TITLE
Security Advisory: Malicious Code Detection in TwitchDropsMiner

### ISSUE THREAD

**Issue by noahnao** [DevilXD/TwitchDropsMiner#654]
During compilation of TwitchDropsMiner, Windows Defender detected malicious code classified as Trojan:Win32/Malgent, specifically identified as HackTool:Win32/Malgent!MSR. This represents a severe security concern, as the malware appears to have been embedded within the compilation process. I think it is possible someone working on the project intentionally embedded malware into the program, in which case it is should be easy to find the malware as the software is open sourced.

Detection Details
Detection Tool: Windows Defender
Malware Classification: Trojan:Win32/Malgent
Specific Variant: HackTool:Win32/Malgent!MSR
Detection Context: Post-compilation scanning

Environment
Operating System: Windows 11 (23H2)
Windows build: 22631.4602
Antivirus: Windows Defender 1.421.1120.0

![billede](https://github.com/user-attachments/assets/b5cc1b67-1d16-4900-84af-ffa93fac8742)

**Comment by DevilXD** [comment]
> I think it is possible someone working on the project intentionally embedded malware into the program, in which case it is should be easy to find the malware as the software is open sourced.

I think you should take reading classes, and maybe buy some glasses, because the project description clearly states that this is expected and nothing to worry about. If this project would include any malware, it would stop existing ages ago. And don't even start me on how many "oh no, antivirus detects this as a virus" posts I had to close already.

The detection points towards the commonly used registry key used for autostarting applications, which makes a lot of sense, given the miner includes an autostart option you can toggle to enable it. If you don't toggle it, no enabling happens, and there's no autostart happening. The autostart key is queried upon application starting up, to determine if it should show itself to the user as toggled on or off. The querying is done in the read-only registry mode, but apparently that's not obvious enough to the antivirus to tell it that it's not trying to write anything. I'm leaving the rest for whoever manages those AV engines to figure it out.

This is a duplicate of #641, #634, #620, #616, #517, #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209, #137 and #13. Please always read through and search for the existing issues (even closed ones) before submitting new ones. Also, I encourage to read the project description carefully as well.

**Comment by noahnao** [comment]
> > I think it is possible someone working on the project intentionally embedded malware into the program, in which case it is should be easy to find the malware as the software is open sourced.
> 
> 
> 
> I think you should take reading classes, and maybe buy some glasses, because the project description clearly states that this is expected and nothing to worry about. If this project would include any malware, it would stop existing ages ago. And don't even start me on how many "oh no, antivirus detects this as a virus" posts I had to close already.
> 
> 
> 
> The detection points towards the commonly used registry key used for autostarting applications, which makes a lot of sense, given the miner includes an autostart option you can toggle to enable it. If you don't toggle it, no enabling happens, and there's no autostart happening. The autostart key is queried upon application starting up, to determine if it should show itself to the user as toggled on or off. The querying is done in the read-only registry mode, but apparently that's not obvious enough to the antivirus to tell it that it's not trying to write anything. I'm leaving the rest for whoever manages those AV engines to figure it out.
> 
> 
> 
> This is a duplicate of #641, #634, #620, #616, #517, #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209, #137 and #13. Please always read through and search for the existing issues (even closed ones) before submitting new ones. Also, I encourage to read the project description carefully as well.

I apologize for my previous report and thank you for the detailed explanation. I should have done a more thorough search of existing issues and read the project description more carefully before posting. I've actually been using TwitchDropsMiner for almost 2 years now and have compiled it countless times without any issues. Your explanation about the registry key for the autostart feature makes perfect sense.

I failed to connect the detection to the autostart functionality, Because it has litteraly never been a problem until this version. This has been a reliable tool for me all this time, and I should have considered that before jumping to conclusions about the Windows Defender alert.

Thank you for maintaining this useful project, and again, I'm still a little bit sussed out because, as a i said earlier, this has literally never been a problem before.​​​​​​​​​​​​​​​​

**Comment by DevilXD** [comment]
> it has litteraly never been a problem until this version.

It has always been a problem, as the linked issues suggest. You just haven't ran into a detection yet, for some reason. It seems Windows Defender isn't the smartest when it comes to detecting stuff like this, and it only happened to do a deeper scan now. Most of the previous issues were closed after detections via Windows Defender.
