### ISSUE TITLE
Fatal Error: Ran out of attempts while handling a GQL request

### ISSUE THREAD

**Issue by p-rintz** [DevilXD/TwitchDropsMiner#7]
Hi there,

after logging in, the program immediately stops with the following error:

```
Traceback (most recent call last):
   File "main.py", line 101, in <module>
   File "asyncio\base_events.py", line 616, in run_until_complete
   File "twitch.py", line 176, in run
   File "twitch.py", line 760, in fetch_inventory
   File "twitch.py", line 746, in gql_request
RuntimeError: Ran out of attempts while handling a GQL request: {'operationName': 'ViewerDropsDashboard', 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'somehashhere'}}}
```

Im using the current version v9.

**Comment by DevilXD** [comment]
Hello =)

This generally means it's having trouble fetching a list of all available campaigns, a list of which you can find here: https://www.twitch.tv/drops/campaigns

If the page above works for you correctly (lists available campaigns), please try deleting the `cookies.jar` file, and then logging in again. If the issue persists, please let me know.

The request retry system is going to be changed in the upcoming `v10`, to accommodate reporting the exact cause of running out of attempts, since the current error message is clearly missing this information. It should be out soon, once I ensure it's stable enough.
