### ISSUE TITLE
Rename mining to farming

### ISSUE THREAD

**Issue by TomerGamerTV** [DevilXD/TwitchDropsMiner#74]
There is a little typo everywhere, i know what you mean when you say mining but actually its called farming.
because you are farming hours and not "mining" them. this is not crypto miner (i hope 😉)

**Comment by DevilXD** [comment]
Hello there o/

"Mining" is intentional here, that's what I decided to call it. If you don't like it - oh well, deal with it ¯\_(ツ)_/¯

**Comment by TomerGamerTV** [comment]
k? it can still confuse people

**Comment by JourneyOver** [comment]
There is literally nothing confusing about the name of the program or what it's meant for. so imo I'm with DevilXD on this.

**Comment by TomerGamerTV** [comment]
People can mistake it for a crypto miner or a malware generator but k

**Comment by JourneyOver** [comment]
lol your one of those people who use "k" for everything.. unless someone is the dumbest person on the planet it's not hard to literally see that it is not a malware generator nor crypto miner by just looking at it for even a second.

**Comment by TomerGamerTV** [comment]
> lol your one of those people who use "k" for everything.. unless someone is the dumbest person on the planet it's not hard to literally see that it is not a malware generator nor crypto miner by just looking at it for even a second.

Is there a problem with me saying "k"? If you are going to act like another Reddit user I will just stop responding to everything you say.
And I'm pretty sure 99% of people are not going to check the code

**Comment by JourneyOver** [comment]
> Is there a problem with me saying "k"?

Maybe because it's just a dumb response and makes people look like lazy asses who can't type one extra letter.

> And I'm pretty sure 99% of people are not going to check the code

You don't even need to look at the code to know what the hell this program is, take 1 second and look at the readme and you'd have a general idea of what the program is and what it does, doesn't matter the name of said program.

but whatever this is my last response to this, as this issue was pointless to begin with  before you ever even posted it and I agree with DevilXD on `If you don't like it - oh well, deal with it ¯\_(ツ)_/¯`
