### ISSUE TITLE
error drop claim

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#82]
![Sin título](https://user-images.githubusercontent.com/110930030/204133274-e08cee35-d8af-4a6f-9933-5c1eaf480081.png)
![Sin título](https://user-images.githubusercontent.com/110930030/204132869-44b640ae-e4cf-45b0-a3ec-d122e8f1e575.png)

**Comment by DevilXD** [comment]
Hi o/

It looks like you're still using `v14`, which has been protected by the Twitch's integrity system, leading to everyone being unable to claim drops. This is already solved in `v15`, the latest master branch, but you'll need to wait for an official release if you'd like to use the executable form. Otherwise, you can run it from source by installing Python, or even build a working executable yourself - if you'd be interested in that, please let me know and I'll direct you to some instructions.

**Comment by matarife123** [comment]
I don't know anything about programming, sorry

**Comment by DevilXD** [comment]
You'll just need to wait for the `v15` release then. Only the translation part of it is missing, other than that, it's basically ready.

**Comment by matarife123** [comment]
Ok, I'll wait for the new version, thank you very much for the answer and all your work

**Comment by DevilXD** [comment]
This is now fixed in `v15`.
