### ISSUE TITLE
Why idle only for linked accounts? Suggestion: idle for anything, with sub-options.

### ISSUE THREAD

**Issue by Luckz** [DevilXD/TwitchDropsMiner#84]
I'm curious what the reason behind your linked account requirement is. I would propose checkboxes similar to Priority Only:
- idle for any available drops, but with linked accounts prioritized [hidden extra feature request: expand Priority to several tiers]
- disable prioritizing account-linked games (requires 'idle for any' to be ticked, or implies it)
- also idle 'excluded' games if there's nothing else to idle (requires 'idle for any' to be ticked, or implies it)

**Comment by DevilXD** [comment]
Hello o/

Regarding the linked account requirement, it was really just a design choice I made at some point during development. Campaigns that aren't linked are simply not worth processing, since you can't claim their drops anyway. Later on, I added an inventory view and decided to include non-linked campaigns in it's display, but that's about it - the requirement stayed.

I'm curious what the reason behind trying to mine a campaign, if you can't claim it's drops?

**Comment by matarife123** [comment]
I asked this same question, in the end I made many accounts to mine everything

**Comment by siggijarl** [comment]
You get them in your twitch inventory even if the accounts are not linked.
Then if you link the accounts in the future, you can claim everything.

**Comment by DevilXD** [comment]
I am aware of that. Still, why would you need to ever do that? There's no point in mining drops for a game you won't play, and if you are playing it, then you either already have your account linked, or you're about to do it because you want the drops anyway.

I still don't see a good argument for this being a thing.

**Comment by Luckz** [comment]
> I still don't see a good argument for this being a thing.

Well, you put it in as an artificial restriction. For example, I could idle of Naraka drops but not link (& redeem) them until I tried out the game in a free weekend and thus got a game account I could link. With TDB this won't work that easily.

There's nothing wrong with just idling for everything, is there? (As long as one blocks or just deprioritizes the really time-intensive drops-spammy games).

A sizeable part of your audience will prefer this as **a background app to forget about**\*, where other issues like auto-retry on unexpected termination also make sense. As it is, I have to check on a while to see if it TDB ran into any issues and then restart it.
The way it is now, you "force" the users to regularly check that they have everything they might want drops for linked. Assume someone just bought Escape from Tarkov, but there are no drops right now. They have to catch the drop event, just by chance or because the game notifies them, and link before it's over. Or take big AAA games like Humankind that you would want to play later when they're on sale / bundled. With this one in particular you can link accounts without owning, but various others require it.

\*: For example, Twitch-Channel-Points-Miner-v2 and Twitch-Drops-Bot are both headless. You don't even see them. It's like the entire idea to maybe run them on a Raspberry Pi, in a Docker container, and just expect them to keep working.

**Comment by DevilXD** [comment]
> other potential improvements like auto-retry on unexpected termination. (...) I have to check on a while to see if it TDM ran into any issues and then restart it. (...) A sizeable part of your audience will prefer this as a background app to forget about.

The problem is that the application terminating with a traceback is considered a non-recoverable error, as in - trying to restart may make sense for you, but it's only going to run into the same issue later on, and I don't want to end up in a situation where the application will keep looping on it's own and try to login for example, as that's a really good way for Twitch to IP ban you for a while, and in other cases, just not work at all. Instead, I'd rather try to account for every possible edge case and not end up crashing the application at all. I know this isn't really possible, but the goal is for it to be stable and reliable, at least eventually.

> For example, Twitch-Channel-Points-Miner-v2 and Twitch-Drops-Bot are both headless. You don't even see them. It's like the entire idea to maybe run them on a Raspberry Pi, in a Docker container, and just expect them to keep working.

This application was never designed with headless in mind, and turning it so cannot be done easily, as most of the internals are strictly tied with UI and procedures that update what it displays. Regarding the "keep working" part, see previous paragraph.

> There's nothing wrong with just idling for everything, is there?

Now, about the main point of this issue - yes, there is a very wrong thing that this could potentially manifest into. See, I've been contacted by many people about my miner over the past couple of months, and there was at least two cases where somebody tried to use a different miner (or this one even) on a server farm of some sorts, where they'd open tens, hundreds or even thousands of instances, each idling drops without claiming them, to amass a series of accounts with drops that can be easily claimed, and then sell those for profit. The end user would link the twitch account they've bought, claim the drops, and then unlink it or relink to another account they've bought to repeat this process.

I am very much against this. This is a hobby project of a personal miner, intended to be ran as a single instance with your primary (and only) twitch account used in it, that you'd normally use for gaming, and that's it. Every time someone asked me about the linked accounts requirement, they've intended to use more than one instance at a time to do all of this, realizing that it can't really be done with my miner - and I want it to stay that way.

If you'd happen to want to get drops for a game you're not playing yet, then unfortunately it's not something I want to support, due to the possibility of the above happening. Sorry.

If you'd want to discuss the auto-retry part of this reply, please open another issue. Otherwise, I consider my stance on this matter to be perfectly clear and this topic closed.
