### ISSUE TITLE
chrome TlsProtocolException

### ISSUE THREAD

**Issue by hadenting** [DevilXD/TwitchDropsMiner#89]
1、I can let the software access the Internet through the agent, as shown in the following figure:
![image](https://user-images.githubusercontent.com/17242018/205232445-2f2d236f-22ee-4107-999b-2a4b9a21b09d.png)
2、I can also access the Internet through a browser
3、You need to log in through a browser, but the browser automatically opened by the software cannot access the Internet. I have been waiting for v15 for several weeks, but it still hasn't been released, so I have to trouble you. Urgently want to use this software, very nice
![image](https://user-images.githubusercontent.com/17242018/205232175-3214d07c-6881-4c23-b44d-14404be93d2c.png)

**Comment by DevilXD** [comment]
Are you running this as an executable, or from source code? Also, where did you get the executable / source code from?

**Comment by hadenting** [comment]
Executable files generated by compiling

**Comment by DevilXD** [comment]
Still don't know where did you get the source code from. If this repo, please try getting the newest source code and compiling it again, because you seem to be using some very old version. Additionally, the Chrome login won't work anyway, if the application doesn't log you in without it, you have to wait 24+ hours and try again. What's the login error code you're getting?

**Comment by hadenting** [comment]
The latest version v15.dev no longer uses browser login, so this issue should be closed
